const categories={
  "Fundamentos":{icon:"🏦",color:"#1464a5"},"Identificadores":{icon:"🔢",color:"#7b61a8"},"Cuentas y débito":{icon:"💵",color:"#2d9d78"},"TDC y crédito":{icon:"💳",color:"#ef8b3a"},"Transferencias":{icon:"🔁",color:"#2dcccd"},"Internacionales":{icon:"🌎",color:"#5b78c7"},"Cheques":{icon:"🧾",color:"#9c6b3e"},"Pagos y servicios":{icon:"🧮",color:"#d28b19"},"Seguridad y fraude":{icon:"🔐",color:"#d94b59"},"Aclaraciones":{icon:"🎧",color:"#6d7890"},"Venta cruzada":{icon:"✨",color:"#6b58a5"},"Confirmar en CUC":{icon:"⚠️",color:"#b36b00"}
};

const concepts=[
{id:"banco",cat:"Fundamentos",title:"Banco",short:"Institución que administra depósitos, pagos, créditos y otros servicios financieros.",example:"Tienes $8,000 en una cuenta y además el banco te autoriza una TDC de $20,000.",dont:"No pienses que una cuenta y una tarjeta son lo mismo.",client:"“¿Por qué veo una cuenta y aparte una tarjeta?”",advisor:"Primero identifica el producto exacto del que habla el cliente.",source:"Concepto general."},
{id:"producto",cat:"Fundamentos",title:"Producto bancario",short:"Servicio financiero contratado por el cliente.",example:"Cuenta de débito, TDC, préstamo, seguro o inversión.",dont:"Un mismo cliente puede tener varios productos.",client:"“Tengo dos tarjetas y un préstamo.”",advisor:"Ubica cuál producto origina la duda antes de revisar movimientos.",source:"Manual 2022 · Anaquel de productos."},
{id:"cuenta",cat:"Fundamentos",title:"Cuenta bancaria",short:"Registro donde el banco lleva el dinero y movimientos de un cliente.",example:"Cuenta con $5,000 de saldo.",dont:"Cuenta ≠ tarjeta ≠ CLABE.",client:"“¿Mi número de tarjeta es mi cuenta?”",advisor:"Explica qué dato necesita según la operación.",source:"Manual 2022 · pagos y transferencias."},
{id:"saldo",cat:"Fundamentos",title:"Saldo",short:"Cantidad que existe en un producto en un momento determinado.",example:"Cuenta: saldo $5,000. TDC: saldo deudor $5,000.",dont:"En débito puede ser dinero del cliente; en crédito puede ser deuda.",client:"“¿Cuál es mi saldo?”",advisor:"Pregunta si se refiere a saldo total, disponible, retenido o deuda.",source:"Concepto general + manual 2022."},
{id:"disponible",cat:"Fundamentos",title:"Saldo disponible",short:"Cantidad que realmente puede usarse en ese momento.",example:"Saldo $5,000; retención $1,000; disponible $4,000.",dont:"Saldo mostrado y disponible pueden diferir.",client:"“Veo $5,000 pero solo puedo usar $4,000.”",advisor:"Revisa retenciones, bloqueos o movimientos pendientes.",source:"Manual 2022 · p.26 saldo retenido."},
{id:"abono",cat:"Fundamentos",title:"Abono",short:"Movimiento que suma dinero o reduce una deuda, según el producto.",example:"Depositas $1,000 a una cuenta o pagas $1,000 a una TDC.",dont:"En una TDC un abono no siempre cae donde el cliente imagina; existe cascada.",client:"“Hice un abono y sigo debiendo.”",advisor:"Revisa cómo se aplicó el pago.",source:"Manual 2022 · cascada de pagos."},
{id:"cargo",cat:"Fundamentos",title:"Cargo",short:"Movimiento que resta dinero de una cuenta o aumenta una deuda.",example:"Compra de $600 con TDD o TDC.",dont:"Cargo aplicado ≠ retención.",client:"“Me apareció un cargo.”",advisor:"Revisa fecha, comercio, estatus y producto.",source:"Manual 2022 · cargos y compras."},
{id:"deposito",cat:"Fundamentos",title:"Depósito",short:"Ingreso de dinero a una cuenta.",example:"Depositas $2,000 en practicaja.",dont:"Un depósito con cheque de otro banco puede verse antes de quedar disponible.",client:"“Ya deposité, ¿por qué no puedo usarlo?”",advisor:"Identifica si fue efectivo, transferencia o cheque.",source:"Manual 2022 · p.40 y p.49."},
{id:"retiro",cat:"Fundamentos",title:"Retiro / disposición",short:"Salida de dinero en efectivo.",example:"Retiras $1,500 en ATM.",dont:"Retiro de TDD usa tu dinero; disposición de TDC usa crédito y puede generar costos/intereses.",client:"“Saqué efectivo de mi tarjeta.”",advisor:"Confirma si fue débito o crédito.",source:"Manual 2022 · retiros y disposiciones."},
{id:"comision",cat:"Fundamentos",title:"Comisión",short:"Cobro por un producto, servicio u operación.",example:"Reposición, anualidad o alguna operación específica.",dont:"Comisión ≠ interés.",client:"“¿Por qué me cobraron una cuota?”",advisor:"Identifica concepto exacto, fecha y contrato vigente.",source:"Manual 2022 · accesorios/comisiones."},
{id:"iva",cat:"Fundamentos",title:"IVA",short:"Impuesto que puede aplicarse sobre determinados intereses, comisiones o servicios.",example:"Una comisión puede aparecer acompañada de IVA.",dont:"No memorices porcentajes operativos desde el manual 2022; verifica vigencia.",client:"“¿Por qué hay otro cargo junto al interés?”",advisor:"Revisa si corresponde a IVA asociado.",source:"Manual 2022 · p.25."},
{id:"udis",cat:"Fundamentos",title:"UDIS",short:"Unidades de Inversión: unidad cuyo valor en pesos cambia con el tiempo y se usa en límites/obligaciones financieras.",example:"Un límite de cuenta puede expresarse en cierto número de UDIS.",dont:"UDIS no son pesos fijos.",client:"“¿Qué significa que mi cuenta tenga un límite en UDIS?”",advisor:"Explica la idea y consulta el límite vigente en CUC.",source:"Manual 2022 · bloqueos en cuentas N2."},

{id:"numcliente",cat:"Identificadores",title:"Número de cliente",short:"Identificador de la persona dentro del banco.",example:"Un cliente puede tener varias cuentas y tarjetas bajo su registro.",dont:"No es número de cuenta, tarjeta ni CLABE.",client:"“¿Cuál de todos mis números me identifica a mí?”",advisor:"Distingue identidad del cliente vs identificador del producto.",source:"Concepto de capacitación; el manual 2022 no define aquí su longitud."},
{id:"numcontrato",cat:"Identificadores",title:"Número de contrato",short:"Identifica una relación contractual o producto del cliente con el banco.",example:"La cuenta o TDC tiene condiciones establecidas en un contrato.",dont:"Contrato ≠ CLABE.",client:"“Me piden mi contrato, ¿es la CLABE?”",advisor:"No; son identificadores con funciones distintas.",source:"Manual 2022 menciona contratos en el Anaquel, pero no define longitud."},
{id:"numcuenta",cat:"Identificadores",title:"Número de cuenta",short:"Identificador propio de una cuenta bancaria.",example:"En el esquema de CLABE del manual aparecen 10 dígitos correspondientes al número de cuenta.",dont:"No confundir con número de tarjeta.",client:"“¿Le doy mi número de cuenta para un SPEI?”",advisor:"Según el canal puede usar CLABE u otro identificador permitido; revisa la operación.",source:"Manual 2022 · p.34."},
{id:"clabe",cat:"Identificadores",title:"CLABE / Cuenta CLABE",short:"Clave Bancaria Estandarizada de 18 dígitos para identificar una cuenta en operaciones interbancarias.",example:"Para recibir una transferencia de otro banco puedes compartir tu CLABE.",dont:"En el manual “Cuenta CLABE” es el encabezado del concepto; no son dos tipos distintos de CLABE.",client:"“¿Cuenta CLABE y CLABE son diferentes?”",advisor:"Explícale que la CLABE es el identificador de 18 dígitos asociado a la cuenta.",source:"Manual 2022 · p.34."},
{id:"numtarjeta",cat:"Identificadores",title:"Número de tarjeta",short:"Número que identifica el plástico/tarjeta.",example:"El número impreso o mostrado para la TDD/TDC.",dont:"Tarjeta ≠ cuenta ≠ CLABE.",client:"“¿Puedo recibir dinero con mi tarjeta?”",advisor:"Depende del tipo de transferencia/canal; identifica qué dato acepta.",source:"Concepto general."},
{id:"bin",cat:"Identificadores",title:"BIN",short:"Rango inicial de dígitos de una tarjeta que ayuda a identificar emisor/producto.",example:"El manual usa tablas de BIN para saber qué tarjetas aplican a ciertos procesos.",dont:"No memorices BIN específicos de 2022 como vigentes.",client:"“¿Por qué el sistema reconoce qué tarjeta tengo?”",advisor:"El BIN puede ayudar a identificar el producto.",source:"Manual 2022 · p.33."},
{id:"cvv",cat:"Identificadores",title:"CVV",short:"Código de seguridad de la tarjeta usado en ciertas compras/validaciones.",example:"Compra por internet solicita datos de tarjeta y CVV.",dont:"CVV ≠ NIP ≠ Token.",client:"“¿El CVV es mi NIP?”",advisor:"No; cumplen funciones distintas.",source:"Manual 2022 menciona CVV en estados/bloqueos digitales."},
{id:"nip",cat:"Identificadores",title:"NIP",short:"Número de Identificación Personal usado para autorizar determinadas operaciones.",example:"Operación en ATM o validación con tarjeta + NIP.",dont:"NIP no debe tratarse como número de cuenta.",client:"“Me bloqueó por poner mal mi NIP.”",advisor:"Consulta estatus y proceso vigente de desbloqueo.",source:"Manual 2022 · p.45 y p.47."},
{id:"token",cat:"Identificadores",title:"Token móvil",short:"Clave irrepetible y de uso único para autorizar operaciones digitales.",example:"Autorizar una operación en app/banca digital.",dont:"Token ≠ contraseña fija.",client:"“¿Para qué sirve el token?”",advisor:"Explícalo como un factor adicional de seguridad.",source:"Manual 2022 · p.42."},
{id:"rastreo",cat:"Identificadores",title:"Clave de rastreo",short:"Identificador generado por la institución para seguir una operación SPEI.",example:"Se usa para consultar el estado del pago en Banxico.",dont:"Clave de rastreo ≠ CLABE del beneficiario.",client:"“Mi transferencia no llegó, ¿qué dato necesito?”",advisor:"La clave de rastreo ayuda a consultar el SPEI/CEP.",source:"Manual 2022 · p.34."},
{id:"referencia",cat:"Identificadores",title:"Número de referencia",short:"Dato asociado a una operación que ayuda a identificarla o rastrearla.",example:"El manual muestra referencia o clave de rastreo para consulta SPEI.",dont:"No es necesariamente el número de cuenta.",client:"“Tengo una referencia de transferencia.”",advisor:"Úsala junto con fecha/bancos según la consulta.",source:"Manual 2022 · p.34."},

{id:"tdd",cat:"Cuentas y débito",title:"TDD · Tarjeta de débito",short:"Tarjeta que normalmente permite usar el dinero disponible de una cuenta.",example:"Tienes $3,000; compras $500; quedan $2,500, salvo retenciones/otros movimientos.",dont:"Débito = dinero del cliente; no es una línea de crédito.",client:"“Mi tarjeta de débito fue rechazada.”",advisor:"Revisa saldo, rechazo, bloqueo, límites o plástico antes de asumir la causa.",source:"Manual 2022 · tarjetas de débito/cuentas."},
{id:"conchequera",cat:"Cuentas y débito",title:"Cuenta con chequera",short:"Cuenta que permite disponer de fondos mediante cheques además de otros canales.",example:"Cliente emite un cheque a un beneficiario.",dont:"No todas las cuentas incluyen chequera.",client:"“¿Puedo emitir un cheque con mi cuenta?”",advisor:"Identifica el tipo de cuenta y producto vigente.",source:"Manual 2022 · Anaquel y módulo de cheques."},
{id:"sinchequera",cat:"Cuentas y débito",title:"Cuenta sin chequera",short:"Cuenta que no usa cheques como medio de disposición.",example:"Opera con TDD, app, transferencias, ATM, etc., según producto.",dont:"No significa que no pueda recibir transferencias.",client:"“Mi cuenta no tiene cheques, ¿puedo recibir SPEI?”",advisor:"Son funciones distintas.",source:"Manual 2022 · Anaquel de productos."},
{id:"nivelescuenta",cat:"Cuentas y débito",title:"Niveles de cuenta (N2, N3, N4)",short:"Clasificación regulatoria que puede relacionarse con expediente y límites de depósitos/operación.",example:"El manual 2022 menciona una restricción de cuenta N2 al superar un umbral en UDIS.",dont:"No es un nivel VIP del cliente.",client:"“¿Qué significa N2?”",advisor:"Explica la clasificación y revisa límites vigentes en CUC.",source:"Manual 2022 · bloqueos en cuentas de débito."},
{id:"retenido",cat:"Cuentas y débito",title:"Saldo retenido",short:"Operación que reduce el disponible pero todavía no aparece como cargo definitivo en el estado de cuenta.",example:"Compra $1,000 → disponible baja $1,000 mientras el comercio termina de cobrar.",dont:"Retención ≠ doble cargo automáticamente.",client:"“Me descontaron pero no aparece en mi estado.”",advisor:"Revisa clave, fecha, importe, estatus y proceso vigente.",source:"Manual 2022 · p.26."},
{id:"transito",cat:"Cuentas y débito",title:"Movimiento en tránsito",short:"Operación pendiente de completar o contabilizar definitivamente.",example:"Compra reciente que aún está procesándose.",dont:"En tránsito ≠ necesariamente error.",client:"“¿Por qué dice pendiente?”",advisor:"Diferencia operación procesándose de cargo posteado.",source:"Manual 2022 menciona compras en tránsito en cascada/revolvente."},
{id:"bloqueocuenta",cat:"Cuentas y débito",title:"Bloqueo de cuenta",short:"Restricción que impide ciertas operaciones por una causa específica.",example:"Prevención de fraude, expediente o inactividad pueden generar bloqueos.",dont:"Bloqueo ≠ cancelación.",client:"“Tengo saldo pero no me deja usarlo.”",advisor:"Consulta el motivo exacto del bloqueo y su proceso.",source:"Manual 2022 · bloqueos en cuentas de débito."},
{id:"corresponsal",cat:"Cuentas y débito",title:"Corresponsal bancario",short:"Comercio afiliado donde pueden realizarse ciertas operaciones bancarias.",example:"Retiro con TDD en un comercio afiliado, si el servicio aplica.",dont:"No es lo mismo que banco corresponsal internacional.",client:"“Retiré en un comercio y tuve problema.”",advisor:"Clasifica como disposición en corresponsal y revisa aclaración correspondiente.",source:"Manual 2022 · p.52."},
{id:"apartados",cat:"Cuentas y débito",title:"Apartados",short:"Herramienta para separar dinero dentro de la cuenta con fines de organización.",example:"Separar $500 de cada nómina para gastos futuros.",dont:"Dinero apartado no necesariamente significa inversión.",client:"“¿Dónde quedó el dinero que aparté?”",advisor:"Revisa apartado y saldo disponible según canal actual.",source:"Manual 2022 · p.43."},
{id:"portabilidad",cat:"Cuentas y débito",title:"Portabilidad de nómina",short:"Mecanismo para que la nómina depositada originalmente en un banco se transfiera al banco elegido por el cliente.",example:"Patrón deposita en Banco A → portabilidad → recursos llegan a BBVA.",dont:"El patrón no necesariamente cambió su banco de dispersión.",client:"“Antes llegaba mi nómina y ahora no.”",advisor:"Distingue alta nueva, no recibida, intermitente o no reconocida.",source:"Manual 2022 · p.53."},

{id:"tdc",cat:"TDC y crédito",title:"TDC · Tarjeta de crédito",short:"Medio para usar una línea de crédito otorgada por el banco.",example:"Línea $20,000; compras $5,000; debes $5,000 y te quedan $15,000 disponibles.",dont:"No es dinero propio del cliente.",client:"“Tengo $20,000 en mi tarjeta.”",advisor:"Aclara si se refiere a línea total o crédito disponible.",source:"Manual 2022 · restricciones TDC."},
{id:"linea",cat:"TDC y crédito",title:"Línea de crédito (LC)",short:"Monto máximo de crédito autorizado para utilizar.",example:"LC $30,000.",dont:"Línea total ≠ saldo disponible.",client:"“Mi línea es $30,000 pero solo puedo usar $12,000.”",advisor:"Revisa saldo deudor, retenciones y restricciones.",source:"Manual 2022 · TDC y suma de líneas."},
{id:"creditodisponible",cat:"TDC y crédito",title:"Crédito disponible",short:"Parte de la línea que aún puede utilizarse.",example:"Línea $20,000 − deuda/uso $8,000 = aprox. $12,000 disponibles, sujeto a movimientos.",dont:"No es el saldo de una cuenta de débito.",client:"“¿Cuánto puedo gastar todavía?”",advisor:"Consulta disponible actual y posibles restricciones.",source:"Concepto general + manual 2022."},
{id:"saldodeudor",cat:"TDC y crédito",title:"Saldo deudor",short:"Cantidad que el cliente debe en un crédito/TDC.",example:"Saldo deudor $10,000.",dont:"Saldo deudor ≠ línea autorizada.",client:"“Tengo línea de $40,000 y saldo de $10,000.”",advisor:"Distingue deuda de capacidad disponible.",source:"Manual 2022 · p.30 suma de LC."},
{id:"corte",cat:"TDC y crédito",title:"Fecha de corte",short:"Día en que se cierra el periodo y se determina qué movimientos forman el estado de cuenta.",example:"Corte día 10: lo facturado hasta ese corte integra el periodo correspondiente.",dont:"Corte ≠ fecha límite de pago.",client:"“¿Por qué una compra de hoy no aparece en el estado anterior?”",advisor:"Puede pertenecer al periodo abierto.",source:"Manual 2022 · cascada y estados de cuenta."},
{id:"fechalimite",cat:"TDC y crédito",title:"Fecha límite de pago",short:"Último día para cubrir el pago requerido del periodo conforme al estado de cuenta.",example:"Corte 10; fecha límite posterior indicada en EDC.",dont:"No es la fecha de corte.",client:"“¿Hasta cuándo puedo pagar?”",advisor:"Consulta el EDC vigente del cliente.",source:"Manual 2022 · PPNGI/intereses."},
{id:"edc",cat:"TDC y crédito",title:"EDC · Estado de cuenta",short:"Documento que resume movimientos, saldos, pagos, comisiones y datos del periodo.",example:"Ahí ves PPNGI, pago mínimo, tasa y compras.",dont:"Saldo de app en tiempo real puede incluir movimientos posteriores al corte.",client:"“No entiendo por qué debo esto.”",advisor:"Explícalo mirando el EDC junto con el cliente.",source:"Manual 2022 · ejercicios y aclaraciones."},
{id:"ppngi",cat:"TDC y crédito",title:"PPNGI · Pago para no generar intereses",short:"Importe del periodo que debe cubrirse para evitar intereses ordinarios sobre el saldo correspondiente, conforme al producto.",example:"Compras normales $4,800 + mensualidad MSI $3,000 = PPNGI $7,800 en el ejemplo del manual.",dont:"PPNGI ≠ saldo total de todas las promociones pendientes.",client:"“Compré $18,000 a MSI, ¿por qué no me piden los $18,000 completos?”",advisor:"Explica que entra la parcialidad correspondiente más otros conceptos del corte.",source:"Manual 2022 · p.16-17."},
{id:"pagominimo",cat:"TDC y crédito",title:"Pago mínimo (PM)",short:"Importe mínimo requerido para mantener la línea al corriente; pagar solo eso deja deuda y puede generar intereses.",example:"PPNGI $15,000; PM $5,000. Pagas $5,000 y todavía queda saldo.",dont:"Pago mínimo ≠ liquidar la deuda.",client:"“Ya pagué el mínimo, ¿por qué me cobraron intereses?”",advisor:"Explica diferencia entre PM y PPNGI.",source:"Manual 2022 · p.23."},
{id:"revolvente",cat:"TDC y crédito",title:"Saldo revolvente",short:"Saldo del periodo abierto que todavía puede cambiar con nuevos cargos/abonos.",example:"Después del corte compras $2,000; forma parte del nuevo periodo.",dont:"No es lo mismo que capital diferido.",client:"“¿Por qué tengo compras que aún no salen en mi estado?”",advisor:"Puede ser saldo del corte abierto.",source:"Manual 2022 · p.16."},
{id:"capitaldiferido",cat:"TDC y crédito",title:"Capital diferido",short:"Saldo pendiente de promociones o parcialidades que se irá incorporando con el tiempo.",example:"$12,000 a 12 MSI: gran parte queda diferida y entra por mensualidades.",dont:"No es dinero perdonado; sigue siendo saldo pendiente.",client:"“¿Por qué sigo debiendo si solo pago $1,000 al mes?”",advisor:"Explica el saldo diferido restante.",source:"Manual 2022 · p.16."},
{id:"cascada",cat:"TDC y crédito",title:"Cascada de pagos",short:"Orden en que el sistema aplica los abonos entre componentes del saldo.",example:"En el ejemplo: pago $18,000 → $15,000 cubren PPNGI y $3,000 van a revolvente.",dont:"Un pago no siempre se aplica directamente al concepto que el cliente imagina.",client:"“Pagué mucho y todavía aparece saldo.”",advisor:"Revisa PPNGI, revolvente, diferido y cómo cayó el abono.",source:"Manual 2022 · p.15-20."},
{id:"interes",cat:"TDC y crédito",title:"Interés",short:"Costo en dinero por utilizar crédito/financiamiento.",example:"El saldo genera $400 de intereses según tasa y cálculo aplicable.",dont:"Interés ≠ tasa; el interés es dinero, la tasa es porcentaje.",client:"“¿Qué es este cargo de interés?”",advisor:"Revisa tasa, saldo promedio, periodo y contrato.",source:"Manual 2022 · p.24-25."},
{id:"tasa",cat:"TDC y crédito",title:"Tasa de interés",short:"Porcentaje utilizado para calcular intereses.",example:"Una tasa mensual se aplica sobre la base definida por el contrato.",dont:"Tasa ≠ CAT ≠ anualidad.",client:"“¿Mi tasa de 60 significa que pago $60?”",advisor:"No; es un porcentaje, no una cantidad fija.",source:"Manual 2022 · p.24."},
{id:"tasaanual",cat:"TDC y crédito",title:"Tasa anual",short:"Tasa expresada tomando un año como referencia.",example:"El manual muestra una tasa ordinaria anual y la convierte para un ejemplo mensual.",dont:"Tasa anual ≠ anualidad.",client:"“¿Tasa anual y anualidad son lo mismo?”",advisor:"No: una es porcentaje financiero y la otra es una comisión del producto.",source:"Manual 2022 · p.24."},
{id:"anualidad",cat:"TDC y crédito",title:"Anualidad / cuota anual",short:"Comisión periódica asociada a determinadas tarjetas, conforme al contrato.",example:"El manual usa un ejercicio de anualidad más IVA.",dont:"Anualidad ≠ interés ni tasa anual.",client:"“¿Por qué me cobraron anualidad si no compré nada?”",advisor:"Revisa producto, fecha de cargo, promociones y condiciones vigentes.",source:"Manual 2022 · ejercicios de cascada/anualidad."},
{id:"cat",cat:"TDC y crédito",title:"CAT · Costo Anual Total",short:"Indicador que ayuda a comparar el costo integral de un crédito considerando más elementos que solo la tasa.",example:"Dos tarjetas pueden tener tasas parecidas pero CAT distinto por otros costos.",dont:"CAT ≠ tasa de interés.",client:"“¿Por qué el CAT es mayor que la tasa?”",advisor:"Porque mide un costo más amplio.",source:"Concepto financiero general; confirma cifras del producto vigente."},
{id:"msi",cat:"TDC y crédito",title:"MSI · Meses sin intereses",short:"Promoción que divide una compra en parcialidades sin interés de esa promoción si se cumplen condiciones.",example:"$12,000 a 12 MSI → $1,000 por mes.",dont:"No significa que solo debas $1,000 en total.",client:"“La tienda me prometió MSI y no se aplicaron.”",advisor:"Revisa comercio, vigencia, monto, canal y promoción vigente.",source:"Manual 2022 · p.12-14."},
{id:"parcialidad",cat:"TDC y crédito",title:"Parcialidad",short:"Cada pago periódico de una compra o plan diferido.",example:"$18,000 a 6 MSI → parcialidad de $3,000.",dont:"Parcialidad ≠ saldo total pendiente.",client:"“¿Por qué solo me cobraron $3,000?”",advisor:"Puede ser la mensualidad de una promoción.",source:"Manual 2022 · ejemplo PPNGI."},
{id:"disposiciontdc",cat:"TDC y crédito",title:"Disposición de efectivo con TDC",short:"Retirar efectivo usando la línea de crédito.",example:"Sacas $3,000 del crédito en ATM.",dont:"No funciona igual que una compra normal; puede generar comisión/intereses desde la disposición según producto.",client:"“Retiré efectivo y me sigue generando interés.”",advisor:"Revisa disposición, fechas, revolvente y condiciones.",source:"Manual 2022 · p.25."},
{id:"tdcadicional",cat:"TDC y crédito",title:"TDC adicional",short:"Tarjeta adicional asociada a la línea/producto del titular principal.",example:"Titular da una adicional a un familiar.",dont:"No implica una línea totalmente independiente salvo condiciones del producto.",client:"“¿La adicional tiene su propio crédito?”",advisor:"Revisa cómo comparte línea y límites en el producto actual.",source:"Concepto de capacitación; validar producto vigente."},
{id:"sumalc",cat:"TDC y crédito",title:"Suma de líneas de crédito",short:"Proceso para unificar líneas y saldos de dos o más tarjetas cuando aplica.",example:"Tarjeta A LC $15k + Tarjeta B LC $40k → producto conservado con línea/saldo unificado según reglas.",dont:"No significa simplemente sumar disponibles sin condiciones.",client:"“Quiero quedarme con una sola tarjeta.”",advisor:"Revisa elegibilidad, saldo, producto que se conserva y políticas vigentes.",source:"Manual 2022 · p.30-31."},
{id:"puntos",cat:"TDC y crédito",title:"Puntos BBVA",short:"Programa en el que ciertas compras pueden generar puntos según producto/comercio/condiciones.",example:"Una compra puede generar puntos y algunas promociones pueden tratarlos distinto.",dont:"No todas las compras/promociones generan puntos.",client:"“¿Por qué esta compra no me dio puntos?”",advisor:"Revisa tipo de movimiento, promoción y producto.",source:"Manual 2022 · módulo Puntos BBVA."},

{id:"transferencia",cat:"Transferencias",title:"Transferencia",short:"Movimiento de dinero de una cuenta hacia otra.",example:"BBVA Luis → cuenta de Ana.",dont:"Transferencia ≠ pago de TDC necesariamente.",client:"“Mandé dinero a otra cuenta.”",advisor:"Identifica si fue interna, interbancaria, OPI o pago.",source:"Concepto general + manual 2022."},
{id:"traspaso",cat:"Transferencias",title:"Traspaso",short:"Movimiento entre cuentas, comúnmente dentro del mismo banco/cliente según contexto.",example:"Cuenta 1 de Luis → Cuenta 2 de Luis.",dont:"El término puede usarse distinto según sistema; revisa el movimiento real.",client:"“Pasé dinero entre mis cuentas.”",advisor:"Clasifica como traspaso interno si corresponde.",source:"Manual 2022 · transferencias/traspasos."},
{id:"spei",cat:"Transferencias",title:"SPEI",short:"Sistema de Pagos Electrónicos Interbancarios operado por Banco de México para transferencias entre instituciones.",example:"BBVA → Santander.",dont:"SPEI ≠ CLABE. La CLABE identifica la cuenta; SPEI es el sistema de pago.",client:"“Mi SPEI no llegó.”",advisor:"Revisa movimiento, clave de rastreo y estado en Banxico.",source:"Manual 2022 · p.34-35."},
{id:"cep",cat:"Transferencias",title:"CEP · Comprobante Electrónico de Pago",short:"Comprobante informativo emitido por Banco de México con datos de una operación SPEI confirmada.",example:"Cliente consulta CEP con datos de la transferencia.",dont:"No confundir con la clave de rastreo; la clave ayuda a localizar la operación.",client:"“¿Cómo compruebo que sí se envió?”",advisor:"Revisa si ya puede generarse CEP o consulta MI-SPEI.",source:"Manual 2022 · p.34-35."},
{id:"ordenante",cat:"Transferencias",title:"Ordenante",short:"Persona/cuenta que envía el dinero.",example:"Luis envía $2,000 → Luis es ordenante.",dont:"Ordenante ≠ beneficiario.",client:"“Yo mandé el dinero.”",advisor:"Ubica banco emisor y datos del envío.",source:"Manual 2022 · p.34."},
{id:"beneficiario",cat:"Transferencias",title:"Beneficiario",short:"Persona/cuenta que recibe el dinero.",example:"Ana recibe $2,000 → Ana es beneficiaria.",dont:"Beneficiario ≠ banco receptor.",client:"“La persona a la que le transferí no lo ve.”",advisor:"Valida cuenta beneficiaria y estado del pago.",source:"Manual 2022 · p.34."},
{id:"emisor",cat:"Transferencias",title:"Banco emisor",short:"Banco desde el que sale la transferencia.",example:"Sale de BBVA → BBVA es emisor.",dont:"Emisor ≠ receptor.",client:"“Yo envié desde BBVA.”",advisor:"Ubica institución de origen.",source:"Manual 2022 · p.34."},
{id:"receptor",cat:"Transferencias",title:"Banco receptor",short:"Banco al que se dirige la transferencia.",example:"Llega a Santander → Santander es receptor.",dont:"Banco receptor ≠ beneficiario.",client:"“Va para una cuenta de otro banco.”",advisor:"Necesitarás identificar institución receptora para seguimiento.",source:"Manual 2022 · p.34."},
{id:"speiestados",cat:"Transferencias",title:"Estados SPEI",short:"Estados que indican qué está pasando con el pago.",example:"En proceso, liquidado, rechazado, en devolución, devuelto, no encontrado.",dont:"“Liquidado” no significa lo mismo que “devuelto”.",client:"“Banxico dice devuelto.”",advisor:"Explica el significado del estado exacto, no uno genérico.",source:"Manual 2022 · p.35."},

{id:"opi",cat:"Internacionales",title:"OPI · Orden de Pago Internacional",short:"Transferencia de fondos hacia un beneficiario mediante operación internacional/divisa según el servicio.",example:"Enviar USD desde México a una cuenta en otro país.",dont:"OPI ≠ SPEI nacional.",client:"“Quiero mandar dinero a Estados Unidos.”",advisor:"Revisa divisa, banco destino, identificadores y condiciones vigentes.",source:"Manual 2022 · p.36-37."},
{id:"divisa",cat:"Internacionales",title:"Divisa",short:"Moneda utilizada en una operación internacional.",example:"USD, EUR, GBP, JPY.",dont:"Importe enviado y recibido puede variar si hay conversión.",client:"“Mandé pesos pero recibe dólares.”",advisor:"Revisa moneda de cargo/abono y tipo de cambio.",source:"Manual 2022 · p.36."},
{id:"tipocambio",cat:"Internacionales",title:"Tipo de cambio",short:"Relación de valor entre dos monedas usada para convertir importes.",example:"Convertir MXN a USD.",dont:"El monto final puede diferir por tipo de cambio y costos aplicables.",client:"“¿Por qué recibió menos?”",advisor:"Revisa conversión, divisa y posibles comisiones/intermediarios.",source:"Manual 2022 · p.36."},
{id:"swift",cat:"Internacionales",title:"SWIFT / BIC",short:"Código alfanumérico que identifica una institución financiera en transferencias internacionales.",example:"El banco receptor proporciona su SWIFT/BIC.",dont:"SWIFT identifica al banco, no necesariamente la cuenta del beneficiario.",client:"“Me piden SWIFT.”",advisor:"Distingue código del banco de cuenta/IBAN del beneficiario.",source:"Manual 2022 · p.37."},
{id:"aba",cat:"Internacionales",title:"ABA",short:"Código numérico de 9 dígitos para identificar instituciones financieras en Estados Unidos.",example:"Transferencia hacia un banco estadounidense.",dont:"ABA ≠ SWIFT ≠ número de cuenta.",client:"“Me dieron un routing de 9 dígitos.”",advisor:"Puede corresponder a ABA; valida datos requeridos para la operación.",source:"Manual 2022 · p.37."},
{id:"iban",cat:"Internacionales",title:"IBAN",short:"International Bank Account Number: identificador de cuenta usado en diversos países.",example:"Beneficiario europeo proporciona su IBAN.",dont:"México usa CLABE; IBAN se usa en otros sistemas/países.",client:"“La cuenta europea tiene letras y números.”",advisor:"Puede ser IBAN; valida formato según destino.",source:"Manual 2022 · p.37."},
{id:"transit",cat:"Internacionales",title:"Transit",short:"Código utilizado en ciertos sistemas bancarios para identificar banco/oficina en operaciones internacionales.",example:"Dato solicitado por un banco de destino según país.",dont:"No asumir que aplica a todas las transferencias.",client:"“Me dieron un transit number.”",advisor:"Revisa país y datos requeridos por el banco receptor.",source:"Manual 2022 · p.37."},
{id:"bancocorresponsal",cat:"Internacionales",title:"Banco intermediario / corresponsal",short:"Institución que ayuda a enrutar o procesar una transferencia internacional entre bancos.",example:"Banco A → corresponsal → banco beneficiario.",dont:"No confundir con corresponsal bancario de tienda/comercio.",client:"“¿Por qué aparece otro banco en la transferencia?”",advisor:"Puede ser el intermediario de la ruta internacional.",source:"Manual 2022 · p.37."},

{id:"cheque",cat:"Cheques",title:"Cheque",short:"Título de crédito mediante el cual una persona ordena al banco pagar una cantidad con cargo a sus fondos.",example:"Cheque de $5,000 a nombre de Ana.",dont:"Cheque ≠ transferencia electrónica.",client:"“Quiero cobrar un cheque.”",advisor:"Identifica tipo, beneficiario, protección, banco emisor y estatus.",source:"Manual 2022 · p.38."},
{id:"chequeportador",cat:"Cheques",title:"Cheque al portador",short:"Cheque que no señala a una persona específica como beneficiaria y contiene la leyenda correspondiente.",example:"Documento emitido “al portador”.",dont:"Tiene reglas y límites legales; verifica vigencia.",client:"“El cheque no tiene mi nombre.”",advisor:"Identifica si realmente es al portador y el proceso vigente.",source:"Manual 2022 · p.38."},
{id:"chequecert",cat:"Cheques",title:"Cheque certificado",short:"El banco certifica la existencia de recursos para respaldar el pago del cheque.",example:"Banco separa/garantiza el importe conforme al proceso.",dont:"No es igual a un cheque personal común.",client:"“Necesito garantizar que sí tenga fondos.”",advisor:"Explica el tipo de cheque y requisitos vigentes.",source:"Manual 2022 · p.38."},
{id:"chequecruzado",cat:"Cheques",title:"Cheque cruzado",short:"Cheque nominativo con dos líneas diagonales que debe abonarse en cuenta y no cobrarse en efectivo.",example:"Se deposita a una cuenta bancaria.",dont:"No se cobra como efectivo en ventanilla.",client:"“Tiene dos líneas al frente.”",advisor:"Identifica que puede ser cheque cruzado.",source:"Manual 2022 · p.38."},
{id:"chequecaja",cat:"Cheques",title:"Cheque de caja",short:"Cheque expedido por una institución de crédito para pagarse en sus propias sucursales/filiales o depositarse al beneficiario.",example:"Cliente entrega fondos y el banco emite cheque a nombre de una persona.",dont:"Según el manual no es al portador ni negociable.",client:"“Necesito un cheque emitido por el banco.”",advisor:"Revisa requisitos y vigencia actual.",source:"Manual 2022 · p.38."},
{id:"chequevent",cat:"Cheques",title:"Cheque de ventanilla",short:"Cheque emitido por la institución para cobro del interesado en condiciones específicas.",example:"Cliente sin chequera solicita un cheque en sucursal.",dont:"El manual 2022 describe condiciones de mismo día/sucursal; verifica si siguen vigentes.",client:"“No tengo chequera pero necesito cobrar.”",advisor:"Consulta proceso vigente en CUC/sucursal.",source:"Manual 2022 · p.38."},
{id:"chequeviajero",cat:"Cheques",title:"Cheque de viajero",short:"Instrumento emitido para ser pagado por la institución/sucursales/corresponsales autorizados.",example:"Uso histórico para disponer de fondos durante viajes.",dont:"Es un producto que puede no tener la misma disponibilidad actual; confirmar.",client:"“Tengo cheques de viajero.”",advisor:"Consulta vigencia y canal actual.",source:"Manual 2022 · p.39."},
{id:"negociable",cat:"Cheques",title:"Cheque negociable",short:"Cheque que puede endosarse conforme a sus condiciones.",example:"Beneficiario lo endosa a otra persona.",dont:"Negociable ≠ al portador necesariamente.",client:"“¿Puedo pasárselo a otra persona?”",advisor:"Revisa tipo de cheque y reglas de endoso.",source:"Manual 2022 · p.39."},
{id:"nonegociable",cat:"Cheques",title:"Cheque no negociable",short:"Cheque que no puede endosarse; lo cobra/deposita el beneficiario conforme aplique.",example:"Beneficiario lo deposita en su propia cuenta.",dont:"No puede cederse mediante endoso.",client:"“¿Lo puede cobrar mi hermano?”",advisor:"Si es no negociable, no mediante endoso.",source:"Manual 2022 · p.39."},
{id:"nominativo",cat:"Cheques",title:"Cheque nominativo / a la orden",short:"Cheque que señala a un beneficiario específico.",example:"“Páguese a Ana García”.",dont:"No es lo mismo que cheque al portador.",client:"“El cheque está a mi nombre.”",advisor:"Verifica tipo y si permite endoso.",source:"Manual 2022 · p.39."},
{id:"endoso",cat:"Cheques",title:"Endoso",short:"Acto mediante el cual el beneficiario transmite derechos del cheque cuando el documento lo permite.",example:"Ana endosa un cheque negociable a Carlos.",dont:"Un cheque no negociable no se endosa.",client:"“Quiero darle el cheque a otra persona.”",advisor:"Primero identifica si el cheque admite endoso.",source:"Manual 2022 · p.39."},
{id:"proteccioncheque",cat:"Cheques",title:"Protección / liberación de cheque",short:"Mecanismo de seguridad en el que ciertos cheques deben autorizarse para poder cobrarse.",example:"Titular libera folio e importe del cheque.",dont:"Cheque con fondos puede no pagarse si requiere liberación.",client:"“El beneficiario no puede cobrar mi cheque.”",advisor:"Revisa protección, importe, folio y estatus.",source:"Manual 2022 · p.39."},
{id:"suspensioncheque",cat:"Cheques",title:"Suspensión de cheque",short:"Bloqueo definitivo del pago de un cheque reportado en situaciones como robo/extravío, según proceso.",example:"Cliente reporta cheques robados.",dont:"Suspender ≠ liberar.",client:"“Perdí un cheque, no quiero que lo cobren.”",advisor:"Consulta proceso vigente de suspensión.",source:"Manual 2022 · p.39."},
{id:"camara",cat:"Cheques",title:"Cámara de Compensación",short:"Proceso/área donde se validan documentos y cobros entre bancos para cheques de otras instituciones.",example:"Cheque de Banco A depositado en BBVA se valida con el emisor.",dont:"Ver saldo reflejado no garantiza disponibilidad inmediata.",client:"“Ya veo el cheque pero no puedo gastar.”",advisor:"Explica que puede seguir en validación.",source:"Manual 2022 · p.40."},
{id:"chequedevuelto",cat:"Cheques",title:"Cheque devuelto",short:"Cheque que no pudo aplicarse y regresa con un motivo de devolución/rechazo.",example:"CCD muestra clave de cheque devuelto y motivo consultable en CUC.",dont:"No asumas causa sin revisar la clave.",client:"“Mi cheque rebotó.”",advisor:"Consulta movimiento, clave y motivo exacto.",source:"Manual 2022 · p.40."},

{id:"domiciliacion",cat:"Pagos y servicios",title:"Domiciliación",short:"Autorización para que un pago se cargue automáticamente a una cuenta/tarjeta de forma periódica o en fecha establecida.",example:"Pago automático de un servicio cada mes.",dont:"Domiciliación ≠ pago manual.",client:"“Mi servicio se cobra solo cada mes.”",advisor:"Revisa si quiere alta, cancelación, cargo no reconocido o pago no aplicado.",source:"Manual 2022 · p.52-54."},
{id:"recurrente",cat:"Pagos y servicios",title:"Cargo recurrente",short:"Cargo periódico realizado por un comercio/servicio autorizado.",example:"Suscripción mensual.",dont:"Puede parecerse a domiciliación, pero el origen/gestión puede ser distinto.",client:"“Quiero que ya no me cobren la suscripción.”",advisor:"Identifica si es cargo recurrente y consulta bloqueo/cancelación vigente.",source:"Manual 2022 · p.51 y p.54."},
{id:"preaut",cat:"Pagos y servicios",title:"Cargo preautorizado",short:"Autorización previa para que un comercio o servicio realice un cargo bajo condiciones acordadas.",example:"Hotel retiene un importe antes de cerrar el cargo final.",dont:"El manual 2022 no desarrolla este término como concepto separado; no confundas con retención o domiciliación sin revisar el caso.",client:"“El comercio apartó dinero antes del cobro final.”",advisor:"Revisa si es preautorización/retención y el estatus real.",source:"Concepto general; confirmar tratamiento operativo en CUC."},
{id:"pagoTDC",cat:"Pagos y servicios",title:"Pago de TDC",short:"Abono que reduce el saldo de una tarjeta de crédito y se aplica conforme a reglas de la cuenta.",example:"Pagas $8,000 a tu TDC desde una cuenta.",dont:"Pago de TDC ≠ transferencia a otra persona.",client:"“Pagué mi tarjeta y no se aplicó.”",advisor:"Revisa canal, fecha, tarjeta destino y cascada/aplicación.",source:"Manual 2022 · aclaraciones de pagos TDC."},
{id:"pagocheque",cat:"Pagos y servicios",title:"Pago/depósito con cheque de otro banco",short:"Cheque de otra institución usado para abonar una cuenta/TDC, sujeto a validación antes de quedar disponible.",example:"Cheque de otro banco depositado a TDD/TDC.",dont:"Que se refleje en saldo no significa que ya esté disponible.",client:"“Ya veo el depósito pero no lo puedo usar.”",advisor:"Revisa saldo buen cobro/validación.",source:"Manual 2022 · p.40."},
{id:"cie",cat:"Pagos y servicios",title:"Pago de servicio CIE",short:"Esquema para pagar servicios/convenios mediante datos de referencia del receptor.",example:"Pago de ciertos servicios o tarjetas externas como servicio CIE en el manual.",dont:"No todas las transferencias son pagos CIE.",client:"“Pagué un servicio y no aparece.”",advisor:"Revisa convenio, referencia, fecha y plazo/proceso vigente.",source:"Manual 2022 · p.43, p.49 y p.54."},
{id:"pagoservicios",cat:"Pagos y servicios",title:"Pago de servicios",short:"Pago de recibos/servicios desde canales bancarios.",example:"Pagar telefonía, luz o algún convenio desde app.",dont:"No memorices tiempos del manual 2022 como actuales.",client:"“Pagué el recibo pero la empresa no lo ve.”",advisor:"Consulta aplicación, referencia y plazo vigente antes de aclarar.",source:"Manual 2022 · p.43 y p.54."},
{id:"retirosintarjeta",cat:"Pagos y servicios",title:"Retiro sin tarjeta",short:"Retiro de efectivo mediante un código generado en canal digital, sin usar el plástico físico.",example:"Generar código y capturarlo en ATM compatible.",dont:"Código de retiro ≠ NIP habitual.",client:"“Quiero sacar dinero pero no tengo mi tarjeta.”",advisor:"Revisa función/canal vigente y condiciones de seguridad.",source:"Manual 2022 · p.43."},

{id:"autenticacion",cat:"Seguridad y fraude",title:"Autenticación",short:"Proceso para comprobar que quien solicita una consulta/operación es realmente la persona autorizada.",example:"Validaciones antes de modificar datos o realizar una operación sensible.",dont:"No inventes preguntas o niveles; usa el procedimiento vigente.",client:"“¿Por qué me hacen validar identidad?”",advisor:"Porque protege datos y operaciones; sigue MAU/CUC actual.",source:"Manual 2022 · biometría; detalle operativo debe verificarse en MAU/CUC vigente."},
{id:"mau",cat:"Seguridad y fraude",title:"MAU · Manual de Autenticación Unificado",short:"Referencia/proceso de autenticación utilizado para determinar cómo validar al cliente antes de ciertas acciones.",example:"Antes de una operación sensible, el asesor revisa qué autenticación corresponde.",dont:"MAU no es CLABE ni un dato que el cliente usa para recibir dinero.",client:"“¿Qué tengo que validar?”",advisor:"Consulta MAU vigente, no memorices un flujo viejo.",source:"Material de capacitación pública posterior al manual; el PDF 2022 no define MAU por nombre."},
{id:"biometria",cat:"Seguridad y fraude",title:"Biometría",short:"Tecnología que reconoce características físicas como rostro, huella o voz para seguridad.",example:"Huella dactilar o reconocimiento facial.",dont:"No todas las operaciones usan la misma biometría.",client:"“La app me pide rostro.”",advisor:"Identifica el proceso específico y estatus del canal.",source:"Manual 2022 · p.45."},
{id:"huellavoz",cat:"Seguridad y fraude",title:"Huella de voz",short:"Biometría basada en características de la voz para autenticación en procesos compatibles.",example:"Validación durante un canal telefónico/portal de voz.",dont:"No asumir que sustituye toda autenticación.",client:"“¿Mi voz sirve para identificarme?”",advisor:"Depende del proceso y enrolamiento vigente.",source:"Manual 2022 · p.45."},
{id:"alertas",cat:"Seguridad y fraude",title:"Alertas digitales",short:"Notificaciones sobre actividad de cuentas y operaciones mediante canales como Push, SMS o email.",example:"Aviso de una compra o movimiento.",dont:"Una alerta no siempre significa fraude; primero revisa el movimiento.",client:"“Me llegó una alerta que no reconozco.”",advisor:"Sondea inmediatamente y clasifica el evento.",source:"Manual 2022 · p.41."},
{id:"push",cat:"Seguridad y fraude",title:"Mensaje Push",short:"Notificación que llega directamente a una aplicación en el dispositivo.",example:"App avisa de una compra.",dont:"Push ≠ SMS.",client:"“Me salió un aviso dentro de la app.”",advisor:"Identifica qué operación generó la alerta.",source:"Manual 2022 · p.41."},
{id:"bloqueo",cat:"Seguridad y fraude",title:"Bloqueo",short:"Medida que impide temporal o definitivamente ciertas operaciones del producto/canal según causa.",example:"Tarjeta bloqueada por seguridad.",dont:"Bloqueo ≠ cancelación del producto.",client:"“Mi tarjeta existe pero no funciona.”",advisor:"Revisa motivo y proceso de desbloqueo/reemplazo.",source:"Manual 2022 · bloqueos y restricciones."},
{id:"restriccion",cat:"Seguridad y fraude",title:"Restricción",short:"Limitación aplicada al uso de una tarjeta, cuenta o canal.",example:"TDC con uso limitado por una estrategia de riesgo o fraude.",dont:"No todas las restricciones se eliminan por teléfono.",client:"“Tengo disponible pero me rechaza.”",advisor:"Consulta movimientos declinados y motivo exacto en CUC.",source:"Manual 2022 · restricciones de uso en tarjetas."},
{id:"phishing",cat:"Seguridad y fraude",title:"Phishing",short:"Fraude mediante correo/página falsa que busca robar datos.",example:"Correo “BBVA” con liga falsa para iniciar sesión.",dont:"No ingresar credenciales desde enlaces sospechosos.",client:"“Abrí una liga que me llegó por correo.”",advisor:"Sondea exposición de datos y movimientos no reconocidos.",source:"Manual 2022 · modalidades de fraude."},
{id:"smishing",cat:"Seguridad y fraude",title:"Smishing",short:"Fraude mediante SMS que intenta llevar al cliente a una llamada o sitio falso.",example:"“Su cuenta fue bloqueada, ingrese aquí”.",dont:"SMS legítimo no pide tratar cualquier liga como segura.",client:"“Me llegó un mensaje raro.”",advisor:"No validar la legitimidad solo por remitente; revisa fraude.",source:"Manual 2022 · modalidades de fraude."},
{id:"vishing",cat:"Seguridad y fraude",title:"Vishing",short:"Fraude mediante llamada donde alguien se hace pasar por el banco para obtener información.",example:"“Hay un cargo, dígame su NIP para cancelarlo”.",dont:"No compartir credenciales por presión telefónica.",client:"“Me hablaron supuestamente del banco.”",advisor:"Sondea qué datos compartió y si hay movimientos.",source:"Manual 2022 · modalidades de fraude."},
{id:"spoofing",cat:"Seguridad y fraude",title:"Spoofing",short:"Técnica para hacer que un número/remitente parezca legítimo aunque no lo sea.",example:"El teléfono muestra un número que parece del banco.",dont:"Ver un número conocido no garantiza legitimidad.",client:"“Pero la llamada sí mostraba BBVA.”",advisor:"Explica que el identificador puede falsificarse.",source:"Manual 2022 · modalidades de fraude."},
{id:"pharming",cat:"Seguridad y fraude",title:"Pharming",short:"Redirección/manipulación para llevar al usuario a un sitio falso aunque crea estar entrando al real.",example:"Termina en una copia de la banca en línea.",dont:"No confiar solo en la apariencia de la página.",client:"“Entré a una página igualita.”",advisor:"Sondea credenciales expuestas y actividad posterior.",source:"Manual 2022 · modalidades de fraude."},

{id:"aclaracion",cat:"Aclaraciones",title:"Aclaración",short:"Solicitud formal para investigar/corregir una operación o situación que el cliente considera incorrecta.",example:"Pago no aplicado, cargo no reconocido o retiro incorrecto.",dont:"No todo problema debe abrirse como fraude o aclaración sin sondeo.",client:"“Quiero meter una aclaración.”",advisor:"Primero identifica tipología correcta y requisitos.",source:"Manual 2022 · p.49-55."},
{id:"sondeo",cat:"Aclaraciones",title:"Sondeo",short:"Preguntas para descubrir qué ocurrió realmente antes de clasificar el caso.",example:"“¿Ambos cargos están aplicados o uno aparece pendiente?”",dont:"No asumir fraude solo porque el cliente diga “no reconozco”.",client:"“Me cobraron dos veces.”",advisor:"Pregunta fecha, comercio, estatus, importe y si realizó una operación similar.",source:"Manual 2022 · p.50."},
{id:"noreconocido",cat:"Aclaraciones",title:"Cargo / movimiento no reconocido",short:"Operación que el cliente afirma no haber realizado o autorizado.",example:"Compra o transferencia que no identifica.",dont:"Primero descarta duplicidad, comercio con otro nombre, retención u operación sí realizada.",client:"“Yo no hice esto.”",advisor:"Sondea y si corresponde aplica proceso de seguridad/aclaración vigente.",source:"Manual 2022 · aclaraciones y fraude."},
{id:"duplicado",cat:"Aclaraciones",title:"Cargo duplicado",short:"Mismo cobro aplicado más de una vez.",example:"Dos cargos posteados de $500 del mismo comercio.",dont:"Un cargo + una retención no necesariamente son duplicado real.",client:"“Veo dos cobros iguales.”",advisor:"Compara estatus de ambos movimientos.",source:"Manual 2022 · p.52-54."},
{id:"devolucion",cat:"Aclaraciones",title:"Devolución / reembolso",short:"Importe regresado por un comercio u operación.",example:"Tienda devuelve $1,500 por una compra cancelada.",dont:"En TDC el abono puede caer en cascada y no justo en el concepto que el cliente esperaba.",client:"“Me devolvieron pero mi mensualidad sigue.”",advisor:"Revisa cómo se aplicó el abono y el saldo resultante.",source:"Manual 2022 · ejercicios p.58-59."},
{id:"bonificacion",cat:"Aclaraciones",title:"Bonificación",short:"Abono realizado para devolver o ajustar un importe.",example:"Bonificación de una comisión cuando procede.",dont:"Bonificación ≠ devolución del comercio necesariamente.",client:"“Me dijeron que me bonificarían.”",advisor:"Revisa fecha, concepto y estatus del abono.",source:"Manual 2022 · aclaraciones/anualidad."},
{id:"folio",cat:"Aclaraciones",title:"Folio",short:"Número que identifica una aclaración o gestión.",example:"Se usa en el asunto al enviar documentos de una aclaración.",dont:"Folio ≠ referencia SPEI.",client:"“¿Cómo doy seguimiento a mi aclaración?”",advisor:"Ubica folio y canal donde se inició.",source:"Manual 2022 · p.55."},
{id:"dictamen",cat:"Aclaraciones",title:"Dictamen",short:"Resultado/resolución de una aclaración, con explicación del motivo cuando aplica.",example:"Carta dictamen enviada al correo del cliente.",dont:"Abrir aclaración no garantiza resolución a favor.",client:"“¿Por qué salió en contra?”",advisor:"Consulta dictamen y explica el motivo registrado.",source:"Manual 2022 · p.55."},
{id:"udr",cat:"Aclaraciones",title:"UDR · retención/cancelación",short:"Área/proceso al que el manual 2022 transfiere ciertos casos de cancelación de TDC tras validar condiciones.",example:"Cliente quiere cancelar una TDC elegible y se transfiere según política.",dont:"No memorices VDN, semáforos ni reglas 2022 como vigentes.",client:"“Quiero cancelar mi tarjeta.”",advisor:"Valida condiciones y usa el flujo actual de CUC.",source:"Manual 2022 · p.29-30."},

{id:"ventacruzada",cat:"Venta cruzada",title:"Venta cruzada",short:"Ofrecer un producto adicional relevante después de atender la necesidad principal, si corresponde.",example:"Resuelves una consulta y existe una oferta adecuada de crédito/seguro/TDC.",dont:"No sacrificar la solución del cliente por vender.",client:"Llama por una consulta y tiene una oferta personalizada.",advisor:"Primero resuelve; después presenta la oferta con claridad y sin presionar.",source:"Enfoque del puesto + prácticas de atención."},
{id:"oferta",cat:"Venta cruzada",title:"Oferta personalizada",short:"Producto/preaprobación mostrada para un cliente según campañas/criterios del banco.",example:"Oferta de préstamo o TDC visible en sistema.",dont:"Oferta visible ≠ contratación automática.",client:"“¿Qué me están ofreciendo?”",advisor:"Explica características y condiciones vigentes antes de contratar.",source:"Manual 2022 · app/campañas y alertas."},
{id:"efi",cat:"Venta cruzada",title:"EFI · Efectivo Inmediato",short:"Uso de parte de la línea disponible de una TDC para recibir efectivo en una cuenta bajo condiciones de una oferta.",example:"Cliente convierte parte de su línea disponible en un depósito y lo paga en parcialidades según plan.",dont:"No es dinero gratis ni un aumento de línea.",client:"“Me ofrecen efectivo inmediato.”",advisor:"Explica monto, plazo, costo/tasa y efecto sobre línea según oferta actual.",source:"Material de capacitación; el manual 2022 menciona EFI en promociones/aclaraciones."},
{id:"consumo",cat:"Venta cruzada",title:"Crédito al consumo",short:"Préstamo destinado a necesidades personales/consumo, pagado conforme a un plan.",example:"Cliente recibe un préstamo y lo paga en mensualidades.",dont:"Crédito al consumo ≠ TDC, aunque ambos son crédito.",client:"“Quiero un préstamo.”",advisor:"Revisa oferta, tasa, plazo, pago y costo total.",source:"Manual 2022 · p.50."},
{id:"seguro",cat:"Venta cruzada",title:"Seguro",short:"Producto que cubre determinados riesgos a cambio de una prima, conforme a condiciones.",example:"Seguro asociado a auto, vida u otro riesgo.",dont:"Seguro ≠ crédito.",client:"“¿Qué cubre este seguro?”",advisor:"Explica cobertura, exclusiones, costo y vigencia del producto específico.",source:"Manual 2022 · Anaquel menciona Seguros; detalle depende del producto."},

{id:"movilidad",cat:"Confirmar en CUC",title:"Movilidad de saldos",short:"Término operativo que necesitas validar en el material vigente antes de memorizar una definición.",example:"Podría referirse a un proceso específico de saldos/productos, pero el manual compartido no lo define claramente con ese nombre.",dont:"No inventar una definición para el examen.",client:"Si aparece en capacitación, anota el contexto exacto.",advisor:"Busca el nombre literal en CUC y registra qué producto, requisitos y efecto tiene.",source:"No definido de forma suficiente en el PDF 2022 recuperado."},
{id:"ibr",cat:"Confirmar en CUC",title:"IBR / IVR (por confirmar)",short:"Acrónimo pendiente: con la información disponible no es seguro qué término escuchaste.",example:"Podría ser IVR en contexto telefónico, pero no debe asumirse.",dont:"No memorizar una expansión inventada.",client:"—",advisor:"Anota la frase completa o toma contexto de la diapositiva y lo validamos.",source:"No localizado de forma clara en el PDF 2022."},
{id:"opt",cat:"Confirmar en CUC",title:"“OPT usuarios recuperación” (por confirmar)",short:"Apunte que no aparece con claridad suficiente en el manual para definirlo con seguridad.",example:"Puede haber confusión con OTP u otro acrónimo interno.",dont:"No asumir que es OTP sin verificar.",client:"—",advisor:"Busca el acrónimo exacto en CUC o en la presentación actual.",source:"No localizado de forma clara en el PDF 2022."},
{id:"ascenso",cat:"Confirmar en CUC",title:"Ascenso / cambio de producto",short:"Término que puede referirse a una migración o cambio de tarjeta/producto, pero la regla exacta depende del catálogo vigente.",example:"Cambiar de un producto a otro con distintas características.",dont:"No asumir elegibilidad, comisiones o conservación de línea.",client:"“¿Puedo cambiar mi tarjeta por otra?”",advisor:"Revisa campaña/producto, elegibilidad y proceso actual.",source:"El PDF 2022 no define de forma completa un proceso llamado “ascenso”."}
];

const cases=[
{tag:"TDC · pagos",q:"“Pagué $5,000 a mi tarjeta y todavía debo. ¿Por qué?”",steps:["Identifica TDC y consulta el estado de cuenta.","Revisa PPNGI, pago mínimo, revolvente y capital diferido.","Confirma cómo se aplicó el abono en la cascada.","Explícalo con cantidades, sin decir solo ‘así lo hizo el sistema’.","Si hay discrepancia real, busca la tipología de aclaración vigente."]},
{tag:"TDD · rechazo",q:"“Tengo dinero y la tarjeta no pasa.”",steps:["Confirma TDD y saldo disponible.","Revisa movimientos declinados/rechazo.","Valida límites, bloqueo, restricción o posible daño de plástico.","Busca el motivo exacto en CUC.","Da la solución/canal que marque el proceso actual."]},
{tag:"Retención",q:"“Me cobraron dos veces la misma compra.”",steps:["Compara ambos movimientos.","Pregunta si los dos están aplicados o uno sigue pendiente/retenido.","Si hay retención, explica diferencia entre autorización y cargo definitivo.","Si ambos están posteados, identifica tipología de duplicidad."]},
{tag:"SPEI",q:"“Hice una transferencia y la otra persona dice que no llegó.”",steps:["Confirma fecha, importe, banco receptor y cuenta beneficiaria.","Obtén clave de rastreo/referencia.","Consulta estado SPEI/CEP o guía al cliente según proceso.","Diferencia liquidado, rechazado, devuelto y en proceso.","Solo abre aclaración si el flujo vigente lo indica."]},
{tag:"Fraude",q:"“Me hablaron del banco, di datos y ahora hay una transferencia que no reconozco.”",steps:["Prioriza seguridad.","Sondea qué datos compartió y qué canales están comprometidos.","Aplica autenticación y bloqueo conforme MAU/CUC actual.","Identifica movimiento no reconocido y tipología correcta.","No improvises pasos de seguridad."]},
{tag:"Cheque",q:"“Deposité un cheque de otro banco y ya veo el saldo, pero no puedo retirarlo.”",steps:["Identifica que es cheque de otro banco.","Explica que puede estar en validación/cámara de compensación.","Consulta saldo buen cobro/estatus en sistema.","No confirmes disponibilidad antes de la validación.","Usa plazos y canal vigentes del CUC, no los de 2022."]},
{tag:"MSI",q:"“La tienda decía 12 MSI, pero mi compra salió normal.”",steps:["Revisa comercio, fecha, importe y canal de compra.","Consulta si existía promoción vigente y términos.","Verifica si el movimiento era elegible.","Si corresponde, sigue proceso de oferta/promoción no aplicada."]},
{tag:"Anualidad",q:"“No compré nada y me cobraron una anualidad.”",steps:["Identifica el concepto como comisión del producto, no compra.","Revisa fecha, producto y condiciones/promociones.","Diferencia anualidad de tasa anual e intereses.","Si reclama improcedencia, clasifica aclaración según CUC."]},
{tag:"Domiciliación",q:"“Mi préstamo estaba domiciliado y este mes no se cobró.”",steps:["Confirma fecha programada.","Revisa que hubiera saldo suficiente.","Valida si la cuenta tenía bloqueos/restricciones.","Identifica si la domiciliación seguía activa.","Aplica aclaración solo si corresponde."]},
{tag:"Cancelación TDC",q:"“Quiero cancelar mi tarjeta ahora mismo.”",steps:["Identifica TDC titular/producto.","Revisa saldo, movimientos pendientes y aclaraciones según proceso actual.","Informa efectos relevantes que marque CUC (por ejemplo cargos recurrentes/puntos si aplica).","Transfiere/canaliza conforme el flujo vigente."]},
{tag:"Portabilidad",q:"“Siempre me llegaba mi nómina a BBVA y esta quincena no llegó.”",steps:["Confirma que se trata de portabilidad y no depósito directo del patrón.","Revisa si es alta nueva, no recibida o intermitente.","Consulta estatus y banco de origen.","Usa plazos/proceso vigentes del CUC."]},
{tag:"OPI",q:"“Mandé dólares al extranjero y llegaron menos.”",steps:["Identifica OPI y divisas de cargo/abono.","Revisa tipo de cambio y bancos intermediarios.","Valida datos SWIFT/ABA/IBAN según destino.","Consulta comisiones y nivel de servicio vigentes.","Si solicita aclaración, usa proceso actual."]},
{tag:"Seguridad",q:"“Me llegó una alerta de inicio de sesión que no reconozco.”",steps:["Sondea si el cliente ingresó o activó el canal.","Pregunta si compartió datos, recibió llamada o perdió el teléfono.","Aplica protección/bloqueo conforme MAU/CUC.","Revisa movimientos recientes.","Clasifica fraude/aclaración correctamente."]},
{tag:"Venta cruzada",q:"“Ya me resolvió lo de mi saldo. ¿Qué era eso que me dijo de un préstamo?”",steps:["Confirma que la necesidad principal ya quedó resuelta.","Explica qué producto/oferta es.","Menciona monto, plazo, tasa/costo y pagos según la oferta vigente.","No prometas aprobación distinta a lo mostrado.","Verifica comprensión antes de contratar."]}
];

const quiz=[
{q:"¿Cuál frase resume mejor una TDD?",o:["Dinero prestado por el banco","Acceso al dinero disponible de una cuenta","Una CLABE física","Un préstamo internacional"],a:1,e:"TDD normalmente usa el dinero disponible del cliente en su cuenta."},
{q:"¿Qué identifica la CLABE?",o:["La persona","Una cuenta para operaciones interbancarias","El NIP","El contrato completo"],a:1,e:"La CLABE tiene 18 dígitos y sirve para identificar la cuenta en transferencias interbancarias."},
{q:"En el manual, “Cuenta CLABE” significa…",o:["Un segundo tipo de CLABE","El encabezado del concepto CLABE asociado a la cuenta","Una clave de seguridad","Una cuenta sin tarjeta"],a:1,e:"No son dos CLABE diferentes; el manual usa “Cuenta CLABE” como encabezado."},
{q:"¿Pago mínimo y PPNGI son lo mismo?",o:["Sí","No; el mínimo puede dejar deuda e intereses","Solo si hay MSI","Solo en débito"],a:1,e:"El pago mínimo mantiene la cuenta al corriente, pero no sustituye al PPNGI."},
{q:"¿Qué es una tasa?",o:["Una cantidad fija en pesos","Un porcentaje usado para calcular costo financiero","La anualidad","Un impuesto"],a:1,e:"La tasa es porcentaje; el interés es el importe en dinero resultante del cálculo."},
{q:"¿Anualidad y tasa anual son lo mismo?",o:["Sí","No: anualidad es comisión; tasa anual es porcentaje financiero","Solo en TDD","Depende del SPEI"],a:1,e:"Son conceptos completamente distintos."},
{q:"Un saldo retenido…",o:["Siempre es un doble cargo","Reduce disponible pero aún puede no estar en el EDC como cargo definitivo","Es una CLABE bloqueada","Es una anualidad"],a:1,e:"El manual define la retención justo así."},
{q:"SPEI es…",o:["Un número de cuenta","El sistema de pagos interbancarios","Un tipo de cheque","Una tasa"],a:1,e:"SPEI es la infraestructura de pago; la CLABE es un identificador de cuenta."},
{q:"¿Qué ayuda a rastrear un SPEI?",o:["BIN","Clave de rastreo","CVV","NIP"],a:1,e:"La clave de rastreo/referencia se usa para consultar el pago."},
{q:"Si Banxico marca un SPEI como “Devuelto”…",o:["El beneficiario ya lo tiene","El monto regresó/debe regresar al ordenante según estado","Es una anualidad","La CLABE cambió"],a:1,e:"Devuelto significa que el banco beneficiario devolvió el pago."},
{q:"SWIFT/BIC identifica principalmente…",o:["Al banco en una transferencia internacional","El NIP","La anualidad","Un cheque"],a:0,e:"SWIFT/BIC identifica la institución financiera."},
{q:"ABA se usa especialmente para…",o:["México","Estados Unidos","Solo cheques BBVA","Token móvil"],a:1,e:"El manual describe ABA como código de 9 dígitos de instituciones en EE.UU."},
{q:"Un cheque no negociable…",o:["Puede endosarse ilimitadamente","No puede endosarse","Siempre es al portador","Es un SPEI"],a:1,e:"El manual indica que no puede endosarse."},
{q:"¿Qué hace la protección de cheques?",o:["Aumenta la línea de crédito","Ayuda a controlar/autorizarlos para cobro","Genera puntos","Cambia la CLABE"],a:1,e:"Ciertos cheques deben liberarse para poder cobrarse."},
{q:"Si un cheque de otro banco se refleja pero no está disponible…",o:["Siempre es fraude","Puede seguir en validación/cámara de compensación","Ya se perdió","Es un cargo recurrente"],a:1,e:"El manual advierte que reflejado no significa disponible."},
{q:"Vishing es fraude por…",o:["SMS","Llamada","Correo","Cheque"],a:1,e:"Vishing = llamada fraudulenta."},
{q:"Smishing es fraude por…",o:["SMS","Llamada","Cheque","ATM"],a:0,e:"Smishing = mensajes de texto falsos."},
{q:"¿Cuál es la primera habilidad ante “no reconozco este cargo”?",o:["Abrir fraude de inmediato","Sondear qué pasó realmente","Vender una TDC","Cancelar la cuenta"],a:1,e:"El manual insiste en sondear antes de elegir la tipología."},
{q:"MAU se relaciona principalmente con…",o:["Transferencias internacionales","Autenticación del cliente","Puntos","Cheques"],a:1,e:"MAU es el Manual de Autenticación Unificado."},
{q:"En una llamada, ¿qué va primero?",o:["Venta cruzada","Resolver/clasificar correctamente la necesidad principal","Ofrecer seguro","Leer promociones"],a:1,e:"La atención principal debe resolverse antes de una oferta adicional."}
];

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let selectedCat="Todos", query="", favorites=new Set(JSON.parse(localStorage.getItem("bancaFavs")||"[]"));

function saveFavs(){localStorage.setItem("bancaFavs",JSON.stringify([...favorites])); updateFavCount();}
function updateFavCount(){ $("#favCount").textContent=favorites.size; }
function cardHTML(c){const color=categories[c.cat]?.color||"#1464a5";return `<article class="concept-card" data-id="${c.id}" style="--accent:${color}"><div class="concept-head"><div class="concept-main"><div class="concept-titleline"><h3>${categories[c.cat]?.icon||"📘"} ${c.title}</h3><span class="badge">${c.cat}</span></div><p class="short">${c.short}</p></div><button class="fav ${favorites.has(c.id)?"on":""}" aria-label="Favorito">★</button><button class="expand" aria-label="Abrir">⌄</button></div><div class="concept-body"><div class="detail-block"><b>Ejemplo rápido</b><p>${c.example}</p></div><div class="detail-block"><b>No lo confundas con…</b><p>${c.dont}</p></div><div class="detail-block"><b>Cliente podría decir</b><p>${c.client}</p></div><div class="detail-block"><b>Como asesor piensa</b><p>${c.advisor}</p></div><div class="source-note">Fuente/nota: ${c.source}</div></div></article>`}

function renderChips(){const names=["Todos",...Object.keys(categories)];$("#categoryChips").innerHTML=names.map(n=>`<button class="chip ${n===selectedCat?"active":""}" data-cat="${n}">${n==="Todos"?"✨":categories[n].icon} ${n}</button>`).join("");$$('.chip').forEach(b=>b.onclick=()=>{selectedCat=b.dataset.cat;renderChips();renderConcepts();});}
function filtered(){const q=query.trim().toLowerCase();return concepts.filter(c=>(selectedCat==="Todos"||c.cat===selectedCat)&&(!q||[c.title,c.short,c.example,c.dont,c.client,c.advisor,c.cat].join(" ").toLowerCase().includes(q)));}
function bindCards(root){root.querySelectorAll('.concept-card').forEach(card=>{card.querySelector('.expand').onclick=e=>{e.stopPropagation();card.classList.toggle('open')};card.querySelector('.concept-head').onclick=e=>{if(e.target.closest('.fav')||e.target.closest('.expand'))return;card.classList.toggle('open')};card.querySelector('.fav').onclick=e=>{e.stopPropagation();const id=card.dataset.id;favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavs();card.querySelector('.fav').classList.toggle('on',favorites.has(id));renderFavorites();};});}
function renderConcepts(){const arr=filtered();$("#resultSummary").textContent=`${arr.length} concepto${arr.length===1?"":"s"}${selectedCat!=="Todos"?` en ${selectedCat}`:""}`;const grid=$("#conceptGrid");grid.innerHTML=arr.length?arr.map(cardHTML).join(""):`<div class="empty">No encontré conceptos con esa búsqueda.</div>`;bindCards(grid);}
function renderFavorites(){const arr=concepts.filter(c=>favorites.has(c.id));const grid=$("#favGrid");grid.innerHTML=arr.length?arr.map(cardHTML).join(""):`<div class="empty">Todavía no guardas conceptos. Marca ⭐ en cualquiera.</div>`;bindCards(grid);}
function renderCases(){ $("#caseGrid").innerHTML=cases.map((c,i)=>`<article class="case-card"><span class="case-tag">${c.tag}</span><h3>Caso ${i+1}</h3><div class="client-quote">${c.q}</div><details><summary>¿Cómo lo pensaría?</summary><ol>${c.steps.map(s=>`<li>${s}</li>`).join("")}</ol><p class="source-note">Los pasos son una guía mental de estudio. La operación exacta se valida en CUC/MAU vigente.</p></details></article>`).join("");}

function switchTab(id){$$('.tabpage').forEach(p=>p.classList.toggle('active',p.id===id));$$('.navtab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));window.scrollTo({top:document.querySelector('.topnav').offsetTop,behavior:'smooth'});if(id==='favoritos')renderFavorites();}
$$('.navtab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));
$("#searchInput").addEventListener('input',e=>{query=e.target.value;renderConcepts();});$("#clearSearch").onclick=()=>{$("#searchInput").value="";query="";selectedCat="Todos";renderChips();renderConcepts();};

$("#randomBtn").onclick=()=>{const c=concepts[Math.floor(Math.random()*concepts.length)];$("#randomContent").innerHTML=`<div class="random-card"><div class="random-cat">${categories[c.cat].icon} ${c.cat}</div><h3>${c.title}</h3><p><strong>Qué es:</strong> ${c.short}</p><p><strong>Ejemplo:</strong> ${c.example}</p><p><strong>No confundas:</strong> ${c.dont}</p></div>`;$("#randomDialog").showModal();};$("#closeRandom").onclick=()=>$("#randomDialog").close();

let qset=[],qi=0,score=0,answered=false;
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startQuiz(){qset=shuffle(quiz).slice(0,10);qi=0;score=0;answered=false;$("#quizRestart").classList.add('hidden');showQ();}
function showQ(){answered=false;const q=qset[qi];$("#quizProgress").textContent=`${qi+1} / ${qset.length}`;$("#quizScore").textContent=`${score} correctas`;$("#quizBar").style.width=`${((qi+1)/qset.length)*100}%`;$("#quizQuestion").textContent=q.q;$("#quizOptions").innerHTML=q.o.map((o,i)=>`<button class="quiz-option" data-i="${i}">${o}</button>`).join("");$("#quizExplain").className='quiz-explain';$("#quizExplain").textContent='';$("#quizNext").classList.add('hidden');$$('.quiz-option').forEach(b=>b.onclick=()=>answerQ(Number(b.dataset.i)));}
function answerQ(i){if(answered)return;answered=true;const q=qset[qi];if(i===q.a)score++;$$('.quiz-option').forEach((b,idx)=>{b.disabled=true;if(idx===q.a)b.classList.add('correct');else if(idx===i)b.classList.add('wrong');});$("#quizScore").textContent=`${score} correctas`;$("#quizExplain").textContent=q.e;$("#quizExplain").classList.add('show');$("#quizNext").classList.remove('hidden');}
$("#quizNext").onclick=()=>{if(qi<qset.length-1){qi++;showQ();}else{$("#quizQuestion").textContent=`Terminaste: ${score} de ${qset.length} correctas`;$("#quizOptions").innerHTML='';$("#quizExplain").className='quiz-explain show';$("#quizExplain").textContent=score>=8?'Vas muy bien. Ahora intenta explicar los conceptos sin leerlos.':'Repasa tus errores y vuelve a intentarlo; la meta es entender la lógica, no memorizar letras.';$("#quizNext").classList.add('hidden');$("#quizRestart").classList.remove('hidden');}};$("#quizRestart").onclick=startQuiz;

renderChips();renderConcepts();renderCases();renderFavorites();updateFavCount();startQuiz();
