// v19 · Amplía el diccionario estable de app.js sin reemplazarlo.
(function(){
  if(typeof concepts==='undefined' || typeof categories==='undefined') return;
  const add=(c)=>{if(!concepts.some(x=>x.id===c.id)) concepts.push(c);};

  categories['Seguros']={icon:'◇',color:'#087f5b'};
  categories['Certificación']={icon:'●',color:'#c7352d'};
  categories['Crédito y nómina']={icon:'◆',color:'#1769aa'};

  [
    {id:'poliza',cat:'Seguros',title:'Póliza',short:'Contrato/documento que define qué seguro existe, quién está asegurado, coberturas, sumas, vigencia, exclusiones y condiciones.',example:'Antes de afirmar que un robo está cubierto, se revisa la póliza y la cobertura contratada.',dont:'Póliza ≠ cobertura individual; la póliza contiene las condiciones del seguro.',client:'“¿Dónde dice lo que sí me cubre?”',advisor:'Ubica la póliza y la cobertura exacta antes de prometer un beneficio.',source:'BBVA Seguros México · conceptos contractuales; condiciones del producto vigente.'},
    {id:'prima-seguro',cat:'Seguros',title:'Prima de seguro',short:'Precio que el cliente paga por mantener la protección del seguro conforme a su forma de pago.',example:'Una póliza puede tener prima mensual, semestral o anual según el producto.',dont:'Prima ≠ deducible.',client:'“¿Por qué tengo que pagar cada mes si todavía no he usado el seguro?”',advisor:'La prima paga la cobertura durante su vigencia; el deducible solo aparece en ciertos siniestros/coberturas.',source:'BBVA Seguros México · productos y condiciones vigentes.'},
    {id:'cobertura-seguro',cat:'Seguros',title:'Cobertura',short:'Riesgo, evento o servicio específico que la póliza protege.',example:'En auto puede existir responsabilidad civil, robo total o daños materiales según el plan.',dont:'Tener “un seguro” no significa que todos los eventos estén cubiertos.',client:'“¿Mi seguro cubre este daño?”',advisor:'Primero revisa el nombre de la cobertura, límites y exclusiones.',source:'BBVA Seguros México · coberturas por producto.'},
    {id:'suma-asegurada',cat:'Seguros',title:'Suma asegurada',short:'Monto máximo o beneficio establecido para una cobertura, sujeto a las condiciones de la póliza.',example:'Un seguro de vida define una suma asegurada para beneficiarios cuando procede el siniestro.',dont:'Suma asegurada ≠ lo que necesariamente se paga en cualquier caso.',client:'“¿Ese monto me lo pagan siempre?”',advisor:'Explica que depende de cobertura, siniestro, límites y condiciones.',source:'BBVA Seguros México · seguros de vida/daños.'},
    {id:'deducible',cat:'Seguros',title:'Deducible',short:'Parte de ciertos daños o pérdidas que corresponde pagar al asegurado cuando la cobertura lo establece.',example:'En un siniestro de auto puede existir un deducible antes de que opere la indemnización correspondiente.',dont:'Deducible ≠ prima.',client:'“¿Por qué tengo que pagar algo si tengo seguro?”',advisor:'Porque algunas coberturas comparten el costo mediante deducible; revisa el porcentaje/monto de la póliza.',source:'BBVA Educación Financiera · deducible; póliza vigente.'},
    {id:'siniestro',cat:'Seguros',title:'Siniestro',short:'Evento ocurrido que puede activar una cobertura del seguro.',example:'Choque, robo o fallecimiento pueden ser siniestros si encajan en la cobertura contratada.',dont:'Siniestro ≠ aprobación automática del pago.',client:'“Tuve un accidente, ¿qué hago?”',advisor:'Identifica el seguro y canaliza al proceso de reporte; la aseguradora valida cobertura y documentos.',source:'BBVA Seguros México · atención de siniestros.'},
    {id:'beneficiario-seguro',cat:'Seguros',title:'Beneficiario',short:'Persona designada para recibir un beneficio cuando el producto y el evento cubierto lo establecen.',example:'En un seguro de vida, los beneficiarios pueden recibir la suma asegurada cuando procede.',dont:'Beneficiario ≠ necesariamente contratante o asegurado.',client:'“Soy familiar, ¿automáticamente soy beneficiario?”',advisor:'No lo confirmes por parentesco; la designación y el trámite deben validarse.',source:'BBVA Seguros México · vida y trámites de fallecimiento.'},
    {id:'asegurado-contratante',cat:'Seguros',title:'Asegurado vs contratante',short:'Asegurado es quien o lo que está protegido; contratante es quien celebra el contrato y asume las obligaciones de pago.',example:'Una persona puede contratar una póliza y designar a otras personas como beneficiarias.',dont:'Contratante ≠ beneficiario necesariamente.',client:'“Yo pago el seguro, ¿entonces yo recibo el beneficio?”',advisor:'Revisa los roles definidos en la póliza.',source:'Concepto asegurador general + documentación contractual BBVA Seguros.'},
    {id:'vigencia-seguro',cat:'Seguros',title:'Vigencia',short:'Periodo durante el cual la póliza se encuentra activa conforme a sus condiciones.',example:'Un siniestro ocurrido fuera de la vigencia puede tener tratamiento distinto.',dont:'Fecha de contratación ≠ garantía de que hoy siga vigente.',client:'“¿Mi seguro todavía está activo?”',advisor:'Confirma fecha de inicio, fin, pagos y estatus del producto.',source:'BBVA Seguros México · póliza/condiciones vigentes.'},
    {id:'exclusiones-seguro',cat:'Seguros',title:'Exclusiones',short:'Situaciones que la póliza establece expresamente como no cubiertas.',example:'Una cobertura puede excluir determinados usos, eventos o circunstancias.',dont:'“Cobertura amplia” no significa “cubre absolutamente todo”.',client:'“Pero me dijeron que era amplio.”',advisor:'Explica cobertura y exclusión concreta del contrato.',source:'BBVA Seguros México · condiciones generales.'},
    {id:'seguro-vida',cat:'Seguros',title:'Seguro de vida',short:'Protección que puede pagar una suma asegurada a beneficiarios por fallecimiento cubierto y, según el producto, incluir beneficios adicionales.',example:'Al fallecer el asegurado, los beneficiarios presentan el trámite correspondiente.',dont:'No todos los seguros de vida tienen las mismas coberturas.',client:'“Mi familiar tenía un seguro de vida.”',advisor:'Identifica póliza/producto y canaliza al trámite de siniestro/fallecimiento vigente.',source:'BBVA Seguros México · Seguros de Vida.'},
    {id:'seguro-auto',cat:'Seguros',title:'Seguro de auto',short:'Protección para riesgos del vehículo y responsabilidad frente a terceros conforme al plan contratado.',example:'Un choque puede activar responsabilidad civil o daños materiales según cobertura.',dont:'Seguro de auto ≠ cobertura total sin límites.',client:'“Choqué, ¿me cubre?”',advisor:'Revisa plan, cobertura, deducible, vigencia y exclusiones.',source:'BBVA Seguros México · Seguro de Auto.'},
    {id:'seguro-salud',cat:'Seguros',title:'Seguro de salud / gastos médicos',short:'Producto que brinda respaldo o servicios ante gastos de salud según su cobertura.',example:'Puede incluir atención médica, estudios, hospitalización o reembolso según el producto.',dont:'No todos los hospitales, médicos o eventos aplican igual.',client:'“¿Puedo atenderme donde yo quiera?”',advisor:'Consulta red, cobertura, deducible/copago y condiciones del seguro específico.',source:'BBVA Seguros Salud México · productos vigentes.'},
    {id:'seguro-hogar',cat:'Seguros',title:'Seguro de hogar',short:'Protección para vivienda, contenidos y/o asistencias frente a riesgos definidos.',example:'Puede incluir robo de pertenencias, daños accidentales o asistencias, según plan.',dont:'Hogar ≠ seguro de celular específico.',client:'“¿Mi computadora está protegida?”',advisor:'Revisa contenidos, suma asegurada, cobertura y exclusiones.',source:'BBVA Seguros México · Seguros de Hogar.'},
    {id:'seguro-objetos',cat:'Seguros',title:'Seguros de objetos personales',short:'Familia de productos para proteger tarjetas, efectivo retirado, celular u otros objetos según producto.',example:'Seguro de celular o seguro de retiro de efectivo.',dont:'No asumir que un seguro cubre todos los objetos.',client:'“Quiero proteger mi celular.”',advisor:'Busca el producto específico y explica cobertura, costo y condiciones.',source:'BBVA Seguros México · Objetos Personales.'},

    {id:'edc-envio',cat:'Certificación',title:'Envío / consulta de estado de cuenta',short:'Solicitud para obtener el EDC de un producto y periodo por un canal autorizado.',example:'Cliente necesita el estado de cuenta del mes anterior en PDF.',dont:'EDC ≠ lista de movimientos recientes.',client:'“Mándeme mi estado de cuenta.”',advisor:'Identifica producto, periodo, canal disponible y autenticación vigente.',source:'Manual 2022 · solicitudes de EDC + BBVA México · consulta digital.'},
    {id:'actualiza-correo',cat:'Certificación',title:'Actualización de correo',short:'Cambio del correo registrado en el contexto que corresponda: datos, alertas, comunicación o servicio.',example:'Cliente ya no tiene acceso al correo anterior.',dont:'No asumas que cambiarlo en un sistema actualiza todos los servicios.',client:'“Quiero cambiar mi correo.”',advisor:'Pregunta para qué servicio/dato y sigue autenticación/canal vigente.',source:'Manual 2022 · modificación de datos; detalle actual: CUC.'},
    {id:'actualiza-telefono',cat:'Certificación',title:'Actualización de teléfono',short:'Cambio del número telefónico registrado o asociado a determinados servicios.',example:'Cliente perdió la línea anterior y tiene un número nuevo.',dont:'Teléfono de contacto puede tener implicaciones distintas a teléfono de seguridad/alertas.',client:'“Ya no tengo ese número.”',advisor:'Identifica servicio afectado y usa el proceso exacto; no improvises.',source:'Manual 2022 · modificación de datos; detalle actual: CUC.'},
    {id:'actualiza-domicilio',cat:'Certificación',title:'Actualización de domicilio',short:'Cambio de la dirección registrada en los productos/datos donde corresponda.',example:'Cliente se mudó.',dont:'No todos los productos o canales piden los mismos requisitos.',client:'“Mi dirección está vieja.”',advisor:'Identifica producto y consulta documentación/canal vigente.',source:'Manual 2022 · modificación de datos; detalle actual: CUC.'},
    {id:'cancelacion-inactividad',cat:'Certificación',title:'Cancelación por inactividad',short:'Terminación de una cuenta o servicio por falta de actividad cuando se cumplen las condiciones aplicables al producto.',example:'BBVA publica avisos de cancelación por inactividad para determinados productos, pero las reglas varían por contrato/producto.',dont:'Inactividad ≠ bloqueo ≠ cancelación automática en todos los productos.',client:'“No uso mi cuenta desde hace tiempo, ¿ya la cancelaron?”',advisor:'Consulta el producto, saldo, estatus y regla vigente; no uses un plazo genérico.',source:'Manual 2022 + avisos/contratos BBVA; confirmar regla exacta en CUC.'},
    {id:'fallecimiento-tramite',cat:'Certificación',title:'Trámite por fallecimiento',short:'Proceso para gestionar productos de una persona fallecida, según producto, solicitante y documentación aplicable.',example:'Beneficiario consulta recursos de una cuenta o un seguro de vida.',dont:'No es una disposición normal de la cuenta del titular.',client:'“Mi familiar falleció, ¿qué hago con su cuenta?”',advisor:'Identifica producto y relación del solicitante; usa la guía vigente de fallecimiento.',source:'BBVA México · Guía para trámites de fallecidos.'},
    {id:'movilidad-saldos-v19',cat:'Certificación',title:'Movilidad de saldos · confirmar proceso',short:'Nombre interno de certificación que todavía requiere validar su definición literal en CUC; existen casuísticas cercanas de traspaso de saldo a favor de TDC.',example:'Cliente pide mover un saldo a favor de una TDC hacia otro producto.',dont:'No asumir que todo traspaso o transferencia se llama “movilidad de saldos”.',client:'“Quiero pasar ese saldo.”',advisor:'Pregunta origen, destino y naturaleza del saldo; después busca el nombre exacto en CUC.',source:'Manual 2022 · traspasos/saldo a favor; “movilidad de saldos” exacta no definida de forma suficiente.'},

    {id:'capital-credito',cat:'Crédito y nómina',title:'Capital de un crédito',short:'Monto principal prestado, antes de separar los costos financieros que se generen.',example:'Préstamo inicial de $50,000.',dont:'Capital ≠ total de pagos futuros.',client:'“¿Por qué terminaré pagando más que lo que me prestaron?”',advisor:'Separa capital de intereses/impuestos/comisiones aplicables.',source:'Concepto general de crédito + productos BBVA.'},
    {id:'plazo-credito',cat:'Crédito y nómina',title:'Plazo',short:'Tiempo acordado para pagar un crédito.',example:'Préstamo a 24 meses.',dont:'Plazo mayor no significa automáticamente crédito más barato.',client:'“¿A cuántos meses lo puedo sacar?”',advisor:'Revisa los plazos disponibles en la oferta vigente.',source:'BBVA México · Préstamos Personales/Nómina.'},
    {id:'saldo-insoluto',cat:'Crédito y nómina',title:'Saldo insoluto',short:'Capital que aún permanece pendiente de pago en un crédito.',example:'Después de amortizar capital, el saldo insoluto disminuye.',dont:'Saldo insoluto ≠ suma de todos los pagos futuros.',client:'“¿Cuánto capital me falta?”',advisor:'Distingue saldo principal de intereses/costos futuros.',source:'Concepto general de crédito.'},
    {id:'capacidad-pago',cat:'Crédito y nómina',title:'Capacidad de pago',short:'Evaluación de cuánto puede pagar una persona de acuerdo con sus ingresos, obligaciones e historial.',example:'Dos clientes con el mismo sueldo pueden recibir ofertas distintas.',dont:'Una oferta no se determina solo por sueldo.',client:'“¿Por qué me ofrecen menos que a otra persona?”',advisor:'La evaluación es individual; no prometas montos fuera de la oferta.',source:'BBVA México · préstamos y evaluación de crédito.'},
    {id:'efi-v19',cat:'Crédito y nómina',title:'EFI · Efectivo Inmediato',short:'Oferta para disponer de dinero de la línea disponible de una TDC y pagarlo a plazo cuando BBVA selecciona al cliente.',example:'Cliente con TDC recibe una invitación de Efectivo Inmediato en sus canales.',dont:'EFI ≠ saldo propio ≠ incremento de línea.',client:'“Me salió una oferta de efectivo.”',advisor:'Explica que usa crédito, reduce línea disponible y tiene tasa/plazo/costos de la oferta.',source:'BBVA México · Efectivo Inmediato + capacitación pública EFI 2026.'},
    {id:'ife-efi',cat:'Confirmar en CUC',title:'IFE vs EFI',short:'Para el producto de efectivo desde la línea de TDC, el término público verificado es EFI = Efectivo Inmediato. Si tu capacitación dice literalmente IFE, hay que validar qué significa allí.',example:'En material público de BBVA, “IFE” también puede aparecer como referencia histórica a identificación oficial; no debe asumirse como EFI.',dont:'No cambiar una sigla interna de memoria.',client:'—',advisor:'Busca la sigla literal y su contexto en CUC/presentación actual.',source:'BBVA México · Efectivo Inmediato; IFE como producto no confirmado.'},
    {id:'portabilidad-v19',cat:'Crédito y nómina',title:'Portabilidad de nómina',short:'Transferencia automática de la nómina desde la cuenta donde deposita la empresa hacia la cuenta elegida en otro banco.',example:'La empresa deposita en el banco origen y después el dinero se transfiere automáticamente a BBVA.',dont:'Portabilidad ≠ que la empresa cambie directamente el banco donde deposita.',client:'“¿Tengo que avisarle a mi trabajo?”',advisor:'Explica origen/destino y confirma estatus de la portabilidad vigente.',source:'BBVA México · Portabilidad de nómina.'},
    {id:'tasa-interes-v19',cat:'Crédito y nómina',title:'Tasa de interés',short:'Porcentaje usado para calcular el costo financiero de un crédito.',example:'Un préstamo puede manejar una tasa anual fija conforme a la oferta.',dont:'Tasa ≠ interés en pesos ≠ CAT.',client:'“¿Ese porcentaje es todo lo que voy a pagar?”',advisor:'Explica que la tasa es un componente; revisa CAT, comisiones y condiciones cuando corresponda.',source:'BBVA México · préstamos/TDC; concepto financiero.'},
    {id:'anualidad-v19',cat:'TDC y crédito',title:'Anualidad / comisión por administración de tarjeta',short:'Nombre común para la comisión por administración de la tarjeta del titular; BBVA usa actualmente esa denominación formal.',example:'Una tarjeta puede cobrarla cada año y otra tener costo $0 según el producto.',dont:'Anualidad ≠ tasa anual de interés.',client:'“¿Todas las tarjetas cobran anualidad?”',advisor:'No: consulta la tarjeta vigente y sus comisiones.',source:'BBVA México · tarjetas de crédito, 2026.'}
  ].forEach(add);

  if(typeof cases!=='undefined'){
    const extras=[
      {tag:'Fallecimiento',q:'“Mi papá falleció y tenía una cuenta en BBVA. ¿Puedo retirar el dinero?”',steps:['Identifica el producto de la persona fallecida.','Identifica quién se comunica y qué relación/trámite solicita.','No lo trates como un retiro normal ni reveles información sin el proceso de autenticación/legitimación aplicable.','Usa la guía vigente de fallecimiento para documentación, beneficiarios o sucesión.','Si existe seguro/crédito relacionado, revisa su proceso por separado.']},
      {tag:'Estado de cuenta',q:'“Necesito mi estado de cuenta de hace dos meses y no sé cómo obtenerlo.”',steps:['Identifica el producto y periodo exactos.','Distingue EDC de movimientos recientes.','Revisa el canal digital o proceso de envío disponible.','Aplica la autenticación que corresponda.','No prometas una ruta antigua si la app cambió.']},
      {tag:'Actualización',q:'“Cambié de número y ya no tengo acceso al anterior.”',steps:['Identifica qué número quiere modificar y qué servicios dependen de él.','Sondea si el problema también afecta App/Alertas.','Usa la autenticación vigente para el cambio.','Explica qué servicios quedarán actualizados según el proceso real.','Si no se puede resolver por ese canal, da la alternativa autorizada.']},
      {tag:'Inactividad',q:'“No he usado mi cuenta desde hace mucho. ¿La cancelaron?”',steps:['No asumas que inactividad significa cancelación.','Consulta tipo de cuenta, saldo y estatus actual.','Identifica si existe bloqueo, cuenta inactiva, recursos pendientes o cancelación.','Aplica la regla del producto vigente; los plazos no son universales.','Explica el siguiente paso autorizado.']},
      {tag:'Seguros',q:'“Quiero un seguro, pero no sé cuál necesito.”',steps:['Pregunta qué quiere proteger: salud, familia, auto, hogar, mascota u objetos.','Pregunta qué riesgo le preocupa y si ya tiene otra cobertura.','Busca el producto vigente que responda a esa necesidad.','Explica prima, cobertura, suma asegurada, deducible y exclusiones relevantes.','No prometas que “cubre todo” ni fuerces la contratación.']},
      {tag:'EFI',q:'“En mi app dice Efectivo Inmediato. ¿Ese dinero ya es mío?”',steps:['Identifica que se trata de EFI y una TDC.','Aclara que es crédito disponible convertido en una disposición, no saldo propio.','Revisa monto, plazo, tasa y condiciones de la oferta concreta.','Explica que impacta la línea disponible y genera pagos.','Confirma comprensión antes de cualquier contratación.']},
      {tag:'Movimiento en tránsito',q:'“La compra dice movimiento en tránsito. ¿Ya me cobraron?”',steps:['Identifica producto y movimiento.','Revisa si es retenido/en tránsito o ya aplicado.','Explica que un movimiento en tránsito todavía se está procesando.','Compara saldo/disponible y si existe otro movimiento igual.','Solo abre aclaración si el proceso vigente lo indica.']}
    ];
    extras.forEach(c=>{if(!cases.some(x=>x.tag===c.tag && x.q===c.q)) cases.push(c);});
  }

  if(typeof quiz!=='undefined'){
    [
      {q:'¿Prima y deducible significan lo mismo?',o:['Sí','No: prima es el costo del seguro y deducible es la parte que puede asumir el asegurado en ciertos siniestros','Solo en auto','Solo en vida'],a:1,e:'Son conceptos distintos; la póliza define cómo aplican.'},
      {q:'¿Qué documento define coberturas y exclusiones de un seguro?',o:['CLABE','Póliza','CEP','BIN'],a:1,e:'La póliza contiene las condiciones del seguro.'},
      {q:'Si el cliente dice “mi cuenta está inactiva”, ¿debes asumir que ya está cancelada?',o:['Sí','No; primero se consulta estatus, producto y regla vigente','Solo si tiene TDD','Solo si es nómina'],a:1,e:'Inactividad, bloqueo y cancelación son estados/procesos distintos.'},
      {q:'En portabilidad, ¿dónde deposita primero la empresa?',o:['Siempre directamente en BBVA','En la cuenta/banco de origen registrado por la empresa, y después se transfiere al destino','En SPEI de Banxico','En una TDC'],a:1,e:'La portabilidad mantiene la cuenta origen y transfiere automáticamente hacia el banco elegido.'},
      {q:'EFI significa públicamente en BBVA…',o:['Estado Financiero Interno','Efectivo Inmediato','Envío Fiscal Internacional','Estrategia de Fraude Interno'],a:1,e:'EFI = Efectivo Inmediato, una oferta ligada a la línea de una TDC.'},
      {q:'¿Qué es saldo insoluto?',o:['La suma de todos los pagos futuros','El capital que todavía queda pendiente','La anualidad','El saldo retenido'],a:1,e:'Saldo insoluto es el principal pendiente de pago.'},
      {q:'Movimiento en tránsito significa…',o:['Fraude confirmado','Operación que todavía se está procesando','Cuenta cancelada','Cheque endosado'],a:1,e:'No es un cargo definitivo por definición; hay que revisar el estatus.'},
      {q:'Ante fallecimiento del titular, ¿se maneja la cuenta como un retiro normal?',o:['Sí','No; debe seguirse el trámite específico vigente','Solo si llama un familiar','Solo si no hay seguro'],a:1,e:'Es un proceso sensible con validación de solicitante, producto y documentación.'}
    ].forEach(q=>{if(!quiz.some(x=>x.q===q.q)) quiz.push(q);});
  }

  if(typeof renderChips==='function') renderChips();
  if(typeof renderConcepts==='function') renderConcepts();
  if(typeof renderCases==='function') renderCases();
  if(typeof renderFavorites==='function') renderFavorites();
  if(typeof startQuiz==='function') startQuiz();
})();