// v19 · Ruta completa de estudio: conceptos base + certificación + productos BBVA.
// Fuente conceptual: Manual Banca Remota dic. 2022 + páginas públicas BBVA/Banxico consultadas en 2026.
// Los datos que cambian (tasas, montos, plazos, autenticación, restricciones y escalamiento) se validan siempre en CUC vigente.
(function(){
  if(typeof guideTopics==='undefined' || !Array.isArray(guideTopics)) return;

  function S(t,what,purpose,when,how,example,client,advisor,warning){
    const p=[];
    if(what) p.push(`<p><strong>Qué es:</strong> ${what}</p>`);
    if(purpose) p.push(`<p><strong>Para qué sirve:</strong> ${purpose}</p>`);
    if(when) p.push(`<p><strong>Cuándo aparece:</strong> ${when}</p>`);
    if(how) p.push(`<p><strong>Cómo funciona / se usa:</strong> ${how}</p>`);
    return {t,body:p.join(''),example,client,advisor,warning};
  }

  const topics=[
    {
      id:'fundamentos',title:'Conceptos básicos: banco, cliente, producto y dinero',level:'Bloque 1 · Base',
      source:'Conceptos generales + Manual Banca Remota 2022',
      intro:'Primero ubica las piezas. Si distingues persona, producto, cuenta, tarjeta, saldo y movimiento, después todo lo demás se vuelve más fácil.',
      memory:['Persona → cliente · Lo que contrata → producto · Donde se registra dinero → cuenta · Lo que ocurre → movimiento'],
      related:['Banco','Cliente','Producto','Cuenta','Tarjeta','Saldo','Cargo','Abono'],
      sections:[
        S('Banco','Institución financiera que administra depósitos, pagos, créditos y otros servicios.','Conecta a clientes con cuentas, medios de pago, financiamiento, ahorro y protección.','Cada vez que el cliente guarda, mueve, paga, pide prestado o protege dinero.','Cada servicio se maneja como un producto con reglas y canales propios.','Un cliente puede tener una cuenta de débito, una TDC, un préstamo y un seguro al mismo tiempo.','“Tengo varias cosas con BBVA y no sé cuál revisar.”','Primero identifica el producto; después el movimiento o solicitud.'),
        S('Cliente','La persona que tiene una relación con el banco.','Permite separar a la persona de los productos que posee.','En cualquier consulta o servicio.','Un mismo cliente puede tener varios contratos, cuentas, tarjetas y créditos.','Luis es el cliente; su cuenta, su TDC y su préstamo son productos distintos.','“¿Mi número de cliente es el de mi tarjeta?”','No: identifica a la persona, no al plástico.'),
        S('Producto bancario','Servicio financiero contratado o utilizado por el cliente.','Define qué reglas, saldos, costos y procesos aplican.','Cuando el cliente habla de cuenta, TDD, TDC, crédito, seguro, cheque, nómina, etc.','Antes de resolver una llamada, clasifica el producto correcto.','Una compra en TDD y una compra en TDC pueden verse parecidas, pero afectan dinero distinto.','“Mi tarjeta no pasa.”','Pregunta si es débito o crédito antes de asumir la causa.'),
        S('Cuenta','Registro bancario donde se controlan saldos y movimientos.','Recibir, guardar y mover dinero según el producto.','Depósitos, retiros, transferencias, pagos y consultas.','Puede estar asociada a tarjeta, CLABE, servicios digitales y otras funciones.','Una cuenta puede tener $5,000 aunque la tarjeta física sea solo un medio para usarla.','“¿Mi cuenta y mi tarjeta son lo mismo?”','Cuenta ≠ tarjeta ≠ CLABE.'),
        S('Saldo','Cantidad que muestra un producto en un momento determinado.','Saber cuánto dinero hay o cuánto se debe, según el producto.','Consultas de cuenta, TDD, TDC, crédito y movimientos.','En débito suele hablarse de dinero; en crédito puede hablarse de saldo deudor o disponible.','Cuenta: saldo $5,000. TDC: saldo deudor $5,000.','“¿Cuál es mi saldo?”','Pregunta si busca saldo total, disponible, retenido o deuda.'),
        S('Cargo y abono','Cargo es un movimiento que resta dinero o aumenta deuda; abono suma dinero o reduce deuda.','Interpretar los movimientos del cliente.','Compras, pagos, depósitos, devoluciones y comisiones.','El efecto depende del producto: un abono a TDC reduce deuda; un abono a cuenta aumenta saldo.','Pago de $1,000 a TDC = abono que reduce deuda.','“Hice un abono y todavía debo.”','Revisa cómo se aplicó el pago y qué otros saldos existen.'),
        S('Disponible','Monto que realmente puede utilizarse en ese momento.','Evita confundir saldo mostrado con dinero utilizable.','Retenciones, movimientos en tránsito, bloqueos o línea de crédito.','Puede diferir del saldo por operaciones pendientes o restricciones.','Saldo $5,000 con retención $1,000 puede dejar menos disponible.','“Veo el dinero pero no me deja usarlo.”','Piensa en retenido, tránsito, límites o bloqueo.')
      ]
    },
    {
      id:'identificadores',title:'Identificadores: cliente, contrato, cuenta, tarjeta, CLABE y BIN',level:'Bloque 2 · Base',
      source:'Manual 2022 + capacitación pública BBVA 2025/2026 + BBVA México',
      intro:'Son números que identifican cosas diferentes. Aprender esta separación evita errores en transferencias, consultas y autenticación.',
      memory:['Persona → número de cliente · Producto → contrato/cuenta · Tarjeta → número de tarjeta · Interbancario → CLABE'],
      related:['Número de cliente','Contrato','Cuenta','Tarjeta','CLABE','BIN','CVV','NIP'],
      sections:[
        S('Número de cliente','Identificador de la persona dentro del banco.','Relacionar a una persona con sus productos.','Consultas y procesos donde se identifica al cliente.','No sustituye número de cuenta, tarjeta o CLABE.','Un cliente puede tener varias cuentas bajo el mismo registro.','“¿Cuál número me identifica a mí?”','Número de cliente identifica a la persona.'),
        S('Número de contrato','Identificador de la relación contractual o producto.','Ubicar el contrato y sus condiciones.','Cuando se revisan condiciones, productos o solicitudes.','Su uso exacto depende del producto y del sistema.','Una TDC tiene un contrato asociado con condiciones particulares.','“¿Contrato es lo mismo que CLABE?”','No; cumplen funciones diferentes.'),
        S('Número de cuenta','Identificador propio de una cuenta.','Ubicar una cuenta concreta del cliente.','Depósitos, consultas y operaciones según el canal.','No debe confundirse con el número del plástico.','La cuenta permanece como producto aunque la tarjeta sea repuesta.','“¿Mi número de tarjeta es mi cuenta?”','No: primero distingue producto y dato solicitado.'),
        S('CLABE','Clave Bancaria Estandarizada de 18 dígitos.','Identificar una cuenta para operaciones interbancarias en México.','Transferencias entre bancos y recepción de recursos.','Se comparte la CLABE de la cuenta receptora cuando el canal la solicita.','Para recibir una transferencia desde otro banco, el cliente puede proporcionar su CLABE.','“¿Cuenta CLABE y CLABE son cosas distintas?”','No; “Cuenta CLABE” suele ser solo una forma de nombrar el dato asociado a la cuenta.'),
        S('Número de tarjeta','Identificador de una tarjeta física o digital.','Realizar y rastrear operaciones vinculadas al plástico/tarjeta.','Compras, ciertos pagos o consultas.','Puede ser distinto de la cuenta y de la CLABE.','Una reposición puede implicar nuevos datos de tarjeta.','“¿Le doy mi tarjeta para una transferencia?”','Confirma qué identificador acepta la operación.'),
        S('BIN / IIN','Rango inicial de dígitos que ayuda a identificar emisor y tipo de tarjeta.','Reconocer características del producto o aplicar procesos específicos.','Validaciones y consultas de tarjetas.','No memorices rangos viejos; los listados operativos deben revisarse vigentes.','El sistema puede reconocer el tipo de tarjeta por sus primeros dígitos.','“¿Qué es BIN?”','Explícalo como identificador inicial de la tarjeta, no como dato de cuenta.',null,'BIN específicos de 2022 no deben memorizarse como vigentes.'),
        S('CVV, NIP y Token','Tres elementos de seguridad distintos.','Autorizar o proteger operaciones de tarjeta y canales digitales.','Compras, ATM y operaciones digitales, según el caso.','CVV se asocia a compras con tarjeta; NIP autoriza ciertas operaciones; Token genera claves de un solo uso.','Una compra digital puede usar CVV; un ATM puede pedir NIP.','“¿Mi CVV es mi NIP?”','No; separa siempre qué factor de seguridad corresponde.',null,'No solicites ni compartas datos sensibles fuera del proceso autorizado.')
      ]
    },
    {
      id:'app',title:'App BBVA y canales digitales',level:'Bloque 3 · App',
      source:'BBVA México · App BBVA y funcionalidades',
      intro:'Entender lo que el cliente ve en su celular te ayuda a traducir frases como “me aparece pendiente”, “no veo mi CLABE” o “no encuentro el pago”.',
      memory:['Primero pregunta qué producto abrió y qué pantalla está viendo.'],
      related:['App BBVA','Movimientos','Estado de cuenta','Tarjeta digital','Retiro sin tarjeta'],
      sections:[
        S('Tus productos en la App','La app agrupa los productos compatibles del cliente.','Consultar cuentas, tarjetas, saldos, movimientos y operar.','Cuando el cliente describe algo que ve en su celular.','Primero selecciona el producto y después la función disponible.','El cliente ve una cuenta y una TDC en la misma app.','“Entré a mi app y veo dos saldos.”','Pregunta cuál producto seleccionó.'),
        S('Consulta de saldo y movimientos','Funciones para ver saldos y operaciones recientes.','Identificar qué ocurrió y en qué estado está.','Compras, transferencias, cargos, abonos y aclaraciones.','Al abrir un movimiento pueden mostrarse detalles como fecha, importe y comercio.','Un cliente ve una compra reciente y quiere saber si ya quedó aplicada.','“Veo un movimiento raro.”','Pide que identifique importe, fecha, descripción y estatus.'),
        S('Estado de cuenta digital','Documento periódico que resume movimientos y datos del producto.','Revisar un periodo completo y sus saldos.','Aclaraciones, fechas de corte, pagos y comprobación.','En productos compatibles puede consultarse o descargarse desde canales digitales.','Cliente necesita revisar compras del mes anterior.','“¿Dónde veo mi estado de cuenta?”','Distingue estado de cuenta de la lista de movimientos del día.'),
        S('Tarjeta digital','Versión digital asociada a una tarjeta física compatible.','Comprar por internet sin usar los mismos datos visibles del plástico.','Compras digitales y administración desde app.','BBVA publica que la tarjeta digital puede manejar número y CVV distintos al plástico y un CVV dinámico.','Cliente quiere comprar en línea sin usar el CVV físico.','“¿Mi tarjeta digital es otra cuenta?”','No; es otra forma de usar la tarjeta/producto.',null,'La ruta exacta de pantalla puede cambiar con actualizaciones.'),
        S('Retiro sin tarjeta','Servicio para disponer de efectivo sin insertar el plástico.','Retirar para uno mismo o, en modalidad compatible, compartir una clave para otra persona.','Cuando el cliente no tiene la tarjeta física o desea generar un retiro desde la app.','BBVA ofrece retiro con clave y también opciones con QR según el canal.','Cliente genera un retiro y acude a un ATM BBVA.','“Generé un retiro y no sé qué sigue.”','Identifica si pregunta por generación, cobro, vigencia o un problema en ATM.',null,'Montos, vigencias y rutas exactas deben consultarse en la información vigente.'),
        S('Oportunidades / ofertas','Sección donde pueden aparecer ofertas preaprobadas o productos disponibles para ciertos clientes.','Mostrar opciones personalizadas de crédito u otros productos.','Cuando el cliente recibe una invitación en la app.','La disponibilidad depende del perfil y de la oferta vigente.','Puede aparecer una invitación de Efectivo Inmediato.','“Me salió una oferta de dinero.”','Identifica el producto antes de explicarlo; no lo confundas con saldo propio.')
      ]
    },
    {
      id:'autenticacion',title:'Autenticación y MAU',level:'Bloque 4 · Certificación fuerte',
      source:'Manual 2022 + capacitación pública BBVA; pasos exactos: CUC vigente',
      intro:'Autenticar no es “hacer preguntas por hacer”. Es comprobar que atiendes a la persona autorizada antes de consultar o ejecutar lo que corresponda.',
      memory:['Autenticar = proteger identidad y producto · El nivel depende de la solicitud.'],
      related:['MAU','Autenticación','Biometría','Huella de voz','Seguridad'],
      sections:[
        S('Autenticación','Proceso de validación de identidad del cliente.','Evitar que terceros consulten o modifiquen información sin autorización.','Antes de determinadas consultas, cambios, contrataciones u operaciones.','Se sigue el nivel y flujo definido para ese proceso en el MAU/CUC vigente.','Una actualización de datos puede requerir un nivel diferente a una consulta general.','“¿Por qué me validan si ya dije mi nombre?”','Explica que la validación protege su información y producto.',null,'No memorices preguntas o pasos antiguos ni improvises controles.'),
        S('MAU','Referencia interna al marco/manual de autenticación usado para definir cómo validar al cliente.','Unificar la seguridad antes de atender procesos sensibles.','Cuando el proceso exige autenticación.','Se consulta la versión vigente y se ejecuta exactamente como corresponda.','Un proceso puede indicar que antes de operar se complete la autenticación aplicable.','“¿Qué validación toca?”','Busca el proceso y nivel vigente, no uses memoria de una presentación vieja.',null,'Los pasos exactos son operativos y cambian; CUC vigente manda.'),
        S('Biometría','Tecnología que compara rasgos físicos o de comportamiento, como rostro, huella o voz.','Reducir suplantación de identidad y reforzar seguridad.','En canales y procesos que tengan biometría habilitada.','El sistema captura/valida el factor biométrico según el canal.','Una reactivación digital puede usar reconocimiento facial.','“¿Por qué me pide mi rostro?”','Explícalo como una validación de identidad del canal.'),
        S('Autenticar vs identificar','Identificar es ubicar quién dice ser el cliente; autenticar es comprobarlo con el mecanismo autorizado.','Evitar confundir tener datos con haber validado identidad.','En llamadas con información sensible o acciones sobre productos.','Sigue el flujo oficial antes de revelar o modificar información.','Saber número de cuenta no basta por sí solo para autorizar cualquier operación.','“Ya le di mi número de cuenta.”','Tener un dato no sustituye la autenticación requerida.'),
        S('Regla de seguridad','Nunca omitir, inventar o debilitar controles para “ayudar más rápido”.','Proteger al cliente, al banco y la operación.','Siempre que exista un paso de seguridad.','Si el proceso no puede completarse, sigue la alternativa o canal autorizados.','Si una validación falla, no se brinca el control.','“¿No puede hacer una excepción?”','Mantén el proceso y explica el motivo con lenguaje simple.',null,'No compartas rutas internas sensibles ni procedimientos para evadir controles.')
      ]
    },
    {
      id:'debito',title:'Cuentas de débito con y sin chequera',level:'Bloque 5 · Certificación fuerte',
      source:'Manual 2022 + catálogo público de cuentas BBVA 2026',
      intro:'Débito usa dinero que ya está en una cuenta. Aquí debes distinguir producto, chequera, nivel, disponible, bloqueos e inactividad.',
      memory:['Débito = dinero de la cuenta · Chequera es una característica del producto.'],
      related:['TDD','Cuenta con chequera','Cuenta sin chequera','Niveles','UDIS','Bloqueo'],
      sections:[
        S('Tarjeta de débito (TDD)','Medio asociado a una cuenta para usar el dinero disponible.','Comprar, retirar y operar según las funciones del producto.','Compras, ATM, consultas y pagos.','El cargo se descuenta de la cuenta, salvo operaciones pendientes o retenidas.','Cuenta con $3,000; compra por $500 reduce el disponible.','“Mi débito no pasa.”','Revisa disponible, estatus, restricciones, límites y plástico.'),
        S('Cuenta con chequera','Cuenta que permite emitir cheques además de otros medios de disposición.','Pagar mediante cheque cuando el producto lo permite.','Cuando el cliente tiene chequera y pregunta por emisión, protección o cobro.','Los cheques se rigen por condiciones de la cuenta y procesos de protección/liberación.','Cliente emite un cheque nominativo a un proveedor.','“¿Puedo girar un cheque?”','Confirma que su producto sea con chequera y revisa el proceso vigente.'),
        S('Cuenta sin chequera','Cuenta que no utiliza cheques como medio de disposición.','Operar por tarjeta, app, transferencias, ATM u otros canales disponibles.','En productos digitales o cuentas que no incluyen chequera.','No tener chequera no impide necesariamente recibir transferencias.','Una cuenta digital puede operar sin talonario de cheques.','“Si no tengo cheques, ¿puedo recibir SPEI?”','Son funciones distintas.'),
        S('Niveles de cuenta','Clasificación regulatoria asociada a identificación, expediente y límites de operación/deposición.','Aplicar controles acordes al nivel de identificación del cliente.','Al revisar límites, expediente o restricciones.','El manual 2022 menciona niveles N2-N4, pero los límites exactos deben validarse hoy.','Una cuenta puede requerir completar expediente para ampliar capacidades.','“¿Qué significa que mi cuenta sea N2?”','Explícalo como nivel regulatorio, no como nivel VIP.',null,'No memorices umbrales en UDIS de material antiguo.'),
        S('UDIS','Unidades de Inversión cuyo valor en pesos cambia con el tiempo.','Expresar ciertos límites, obligaciones o referencias regulatorias.','En algunos límites de cuenta o productos.','Se convierte a pesos usando el valor vigente correspondiente.','Un límite regulatorio puede expresarse en UDIS y no en un monto fijo de pesos.','“¿UDIS son pesos?”','No; es una unidad cuyo valor cambia.'),
        S('Cuenta activa, bloqueada e inactiva','Estados diferentes de un producto.','Saber si la cuenta puede operar y qué proceso corresponde.','Cuando el cliente tiene saldo pero no puede usarlo o lleva tiempo sin actividad.','Se consulta el estatus exacto y la causa en sistema.','Una cuenta bloqueada puede seguir existiendo aunque no permita ciertas operaciones.','“¿Mi cuenta está cancelada porque no puedo usarla?”','No asumas cancelación: confirma estatus y motivo.')
      ]
    },
    {
      id:'movimientos',title:'Saldos, retenidos y movimientos en tránsito',level:'Bloque 6 · Certificación fuerte',
      source:'Manual 2022 + BBVA México 2026 · saldo retenido',
      intro:'Este tema explica muchos “me quitaron dinero”, “me cobraron doble” o “veo el cargo pero todavía no aparece bien”.',
      memory:['Pendiente/retenido no equivale automáticamente a cargo definitivo.'],
      related:['Saldo retenido','Movimiento en tránsito','Aplicado','Declinado','Disponible'],
      sections:[
        S('Saldo retenido','Importe apartado temporalmente por una operación que aún puede estar pendiente de confirmación.','Reservar fondos mientras la operación se completa o libera.','Compras, reservaciones u operaciones que todavía no quedan definitivas.','Reduce el disponible mientras está retenido; el resultado final depende del procesamiento.','Hotel retiene un importe como garantía y después lo libera o aplica.','“Me quitaron dinero pero no veo el cargo final.”','Revisa si aparece como retenido o en tránsito y no lo trates como doble cargo automáticamente.'),
        S('Movimiento en tránsito','Operación que todavía se está procesando o contabilizando.','Distinguir lo pendiente de lo ya aplicado.','Compras o movimientos recientes.','BBVA puede mostrar la leyenda de tránsito mientras aún no impacta de forma definitiva el saldo utilizado/disponible.','Compra reciente aparece pendiente y luego cambia a aplicada.','“Dice movimiento en tránsito, ¿ya se cobró?”','Explica que está en procesamiento y revisa su estado actual.',null,'Los tiempos exactos dependen del tipo de operación y deben consultarse vigentes.'),
        S('Movimiento aplicado','Operación ya contabilizada conforme al producto.','Saber que el cargo o abono ya forma parte del saldo registrado.','Después del procesamiento.','Se refleja como movimiento definitivo en la cuenta o tarjeta.','Una compra pasa de pendiente a aplicada.','“Ya aparece en mi estado.”','Ahora revisa si el monto/comercio son correctos.'),
        S('Declinado / rechazado','Intento de operación que no fue autorizado o procesado.','Diferenciar un intento fallido de un cargo aplicado.','Compras, retiros o transferencias rechazadas.','La causa puede ser saldo, restricción, seguridad, límites, datos u otras condiciones.','Una compra no pasa aunque la tarjeta esté físicamente presente.','“Me rechazaron la compra.”','Consulta el motivo disponible antes de culpar al comercio o asumir fraude.'),
        S('Doble cargo aparente','Dos registros similares que pueden ser dos cargos, una retención más un cargo, o un error real.','Evitar aclaraciones mal clasificadas.','Cuando el cliente ve importes repetidos.','Compara fecha, estatus, comercio e importe de ambos registros.','Un movimiento pendiente y otro aplicado pueden parecer duplicados.','“Me cobraron dos veces.”','Sondea y compara los dos movimientos antes de abrir aclaración.'),
        S('Qué preguntar','Fecha, importe, comercio, producto, estatus, si existe otro movimiento similar y qué cambió en el disponible.','Construir el diagnóstico correcto.','Antes de clasificar una aclaración de movimiento.','Empieza por hechos visibles, no por conclusiones.','“No reconozco esto.” → primero identifica exactamente qué ve.','“No sé qué pasó.”','Producto → movimiento → estado → evidencia visible.')
      ]
    },
    {
      id:'restricciones',title:'Restricciones, bloqueos y tarjeta rechazada',level:'Bloque 7 · Certificación fuerte',
      source:'Manual Banca Remota 2022; tratamiento actual: CUC vigente',
      intro:'Una restricción no significa automáticamente fraude ni cancelación. Hay que identificar qué está restringido y por qué.',
      memory:['Rechazo ≠ bloqueo ≠ cancelación ≠ fraude.'],
      related:['Restricción','Bloqueo','Rechazo','Límite','Inactividad'],
      sections:[
        S('Restricción','Condición que limita el uso de un producto o una operación.','Evitar operaciones que no cumplen reglas, seguridad o condiciones del producto.','Tarjetas, cuentas, transferencias y canales.','El sistema muestra un estatus o motivo que guía el siguiente paso.','Una TDD puede tener saldo y aun así no permitir una operación.','“Tengo dinero, ¿por qué no me deja pagar?”','Consulta la restricción específica y no prometas desbloqueo sin revisar.'),
        S('Bloqueo','Estado que impide total o parcialmente operar un producto o canal.','Proteger al cliente o cumplir requisitos operativos/regulatorios.','Robo, fraude, expediente, inactividad u otras causas.','El tratamiento cambia según el tipo de bloqueo.','Tarjeta bloqueada por robo requiere un flujo distinto a una cuenta con expediente pendiente.','“¿Puede quitarme el bloqueo?”','Primero identifica la causa y el proceso autorizado.'),
        S('Tarjeta rechazada','Operación de tarjeta que no fue autorizada.','Señalar que la compra/retiro no se completó en ese intento.','TPV, compras digitales o disposiciones.','Revisa estatus, saldo/línea, límites, vigencia, restricciones y seguridad.','Compra declinada por una causa de seguridad.','“Mi tarjeta ya no sirve.”','No concluyas eso sin revisar el motivo.'),
        S('Límite de uso','Tope configurado o contractual para determinadas operaciones.','Controlar cuánto puede utilizarse en un periodo/canal.','Cuando una operación supera el límite permitido.','Puede existir límite del producto, del canal o configurado por el usuario.','Compra supera un límite configurado aunque exista saldo.','“Tengo saldo y no pasa.”','Revisa límites además de disponible.'),
        S('Inactividad','Falta de actividad durante un periodo relevante para el producto/proceso.','Aplicar reglas de administración, seguridad o regulación.','Cuando una cuenta o servicio lleva tiempo sin uso.','El efecto exacto depende del producto y de la normativa/proceso vigente.','Una cuenta inactiva no es sinónimo automático de “desapareció”.','“No usé mi cuenta por años.”','Consulta estatus, recursos y ruta vigente.',null,'Los plazos del manual 2022 no deben tratarse como regla vigente sin validar CUC.')
      ]
    },
    {
      id:'fraudes',title:'Fraudes y cargos no reconocidos',level:'Bloque 8 · Certificación fuerte',
      source:'Manual 2022 + Centro de Ayuda BBVA 2026',
      intro:'El objetivo es proteger primero y clasificar bien. “No reconozco” no significa por sí solo que ya confirmaste un fraude.',
      memory:['Sondea antes de tipificar · Seguridad primero.'],
      related:['Cargo no reconocido','Phishing','Smishing','Vishing','Spoofing','Pharming'],
      sections:[
        S('Cargo no reconocido','Movimiento que el cliente no identifica como propio.','Iniciar la revisión y, si corresponde, una aclaración o medida de seguridad.','Cuando aparece una compra, pago o disposición desconocida.','Revisa comercio, fecha, adicional, suscripciones, duplicados y contexto antes de concluir.','Una suscripción olvidada puede parecer fraude.','“Yo no hice esa compra.”','Sondea primero y sigue el proceso vigente de aclaración/seguridad.'),
        S('Phishing','Engaño mediante correos o sitios falsos para obtener datos.','Robar credenciales o información financiera.','Mensajes que piden abrir enlaces o “validar” información.','El atacante imita una comunicación legítima.','Correo que aparenta ser del banco y lleva a una página falsa.','“Me llegó un correo de BBVA para validar mis claves.”','Indica usar canales oficiales y sigue el protocolo de seguridad.'),
        S('Smishing','Phishing realizado por SMS o mensajería.','Obtener datos o dirigir a enlaces fraudulentos.','Mensajes de texto sobre supuestos cargos, premios o bloqueos.','Usa urgencia para provocar una acción rápida.','SMS: “tu cuenta será bloqueada, entra aquí”.','“Me llegó un mensaje con una liga.”','No validar la liga; orientar a canal oficial.'),
        S('Vishing','Fraude por llamada telefónica en el que alguien se hace pasar por una entidad confiable.','Obtener datos, códigos o inducir transferencias.','Llamadas sobre supuestos cargos o emergencias.','El defraudador usa presión y guiones convincentes.','Llamada que pide compartir un código para “cancelar” una compra.','“Me hablaron del banco y di información.”','Prioriza protección y proceso de fraude vigente.'),
        S('Spoofing','Suplantación de identificadores, por ejemplo un número telefónico o remitente.','Hacer que una comunicación falsa parezca legítima.','Llamadas o mensajes donde el remitente aparenta ser BBVA.','El identificador visible no prueba por sí solo que la llamada sea del banco.','El teléfono muestra un nombre conocido, pero el interlocutor pide datos indebidos.','“Me salió el número del banco.”','Explica que no debe confiar solo en el identificador.'),
        S('Pharming','Redirección maliciosa hacia un sitio falso aunque el usuario intente entrar a uno legítimo.','Capturar información o credenciales.','Navegación web comprometida.','El usuario puede terminar en una réplica del sitio original.','Página similar al banco solicita datos inusuales.','“La página se veía igual.”','Recomienda usar canales oficiales y seguir el proceso de seguridad.'),
        S('Qué revisar antes de tipificar','Producto, canal, comercio, fecha, monto, tarjetas adicionales, suscripciones y si compartió datos.','Elegir el proceso correcto y evitar falsas conclusiones.','Siempre que el cliente diga “no reconozco”.','El manual insiste en sondear antes de clasificar.','Un cargo duplicado y un fraude requieren tratamientos distintos.','“No reconozco.”','Haz preguntas suficientes para entender hechos, no para confirmar tu primera hipótesis.')
      ]
    },
    {
      id:'cheques',title:'Cheques',level:'Bloque 9 · Certificación fuerte',
      source:'Manual Banca Remota 2022 · pp. 38-40; procesos vigentes: CUC',
      intro:'Empieza por qué es un cheque y luego separa tipo, endoso, protección, depósito y devolución.',
      memory:['Cheque = orden de pago contra una cuenta · Depósito con cheque ≠ dinero disponible inmediato.'],
      related:['Cheque','Nominativo','Portador','Endoso','Protección','Suspensión','Buen cobro'],
      sections:[
        S('Cheque','Título/documento mediante el cual se ordena al banco pagar una cantidad con cargo a fondos de una cuenta.','Realizar pagos usando una cuenta con chequera.','Cuando el producto permite emisión y el cliente entrega el documento a un beneficiario.','Se llena conforme a sus requisitos y se presenta para cobro o depósito.','Cliente emite un cheque por $5,000 a un proveedor.','“¿Qué es un cheque?”','Piensa: emisor → cuenta → beneficiario → importe → estatus.'),
        S('Cheque al portador','Cheque que no designa a una persona específica como beneficiario, cuando legalmente/procedimentalmente aplica.','Permitir cobro conforme a las reglas aplicables al documento.','En cheques emitidos bajo esa modalidad.','El tratamiento depende de límites y normativa vigente.','Documento con leyenda “al portador”.','“¿Lo puede cobrar cualquiera?”','No generalices: revisa las reglas y límites vigentes.',null,'No memorices montos máximos antiguos.'),
        S('Cheque nominativo / a la orden','Cheque emitido a nombre de una persona o empresa.','Dirigir el pago a un beneficiario identificado.','Pagos donde se quiere identificar al beneficiario.','El beneficiario aparece en el documento y, si procede, puede existir endoso.','Cheque a nombre de una empresa.','“Está a mi nombre, ¿puedo depositarlo?”','Revisa requisitos del tipo de cheque y cuenta.'),
        S('Endoso','Acto mediante el cual se transmiten derechos de ciertos cheques cuando está permitido.','Permitir que otro beneficiario reciba derechos sobre el documento.','Solo en cheques negociables y bajo requisitos aplicables.','Se formaliza conforme a reglas del documento.','Beneficiario endosa un cheque negociable a otra persona.','“¿Puedo endosarlo?”','Primero identifica si el cheque es negociable y qué requisitos aplican.'),
        S('Cheque cruzado','Cheque con dos líneas paralelas que restringe su cobro en efectivo.','Dar mayor control al dirigirlo a depósito en cuenta.','Cuando el documento está cruzado.','Se deposita en cuenta en lugar de cobrarse en efectivo.','Cheque cruzado entregado a un proveedor.','“¿Por qué no me lo pagan en ventanilla?”','Explica la restricción propia del tipo de cheque.'),
        S('Cheque certificado y de caja','Certificado: banco confirma/provisiona fondos según el proceso; de caja: lo expide la propia institución.','Dar mayor certeza de pago en operaciones específicas.','Pagos donde se requiere un instrumento emitido o respaldado por el banco.','El proceso y vigencia dependen del tipo de cheque.','Compra importante pagada con cheque de caja.','“¿Es igual que un cheque normal?”','No; identifica quién lo emite y cómo se respalda.'),
        S('Protección, liberación y suspensión','Servicios/acciones para controlar si un cheque puede pagarse o para impedir su pago por una causa válida.','Reducir riesgo de alteración, falsificación, robo o extravío.','Cuentas con chequera y cheques sujetos al esquema de protección.','El cliente registra/libera o suspende conforme al proceso vigente.','Cheque protegido no se paga hasta cumplir la liberación correspondiente.','“Mi cheque está protegido.”','Revisa folio, importe, estatus y proceso CUC.',null,'Los pasos exactos y montos piso cambian; valida CUC.'),
        S('Cheque de otro banco y saldo a buen cobro','Depósito de cheque que requiere validación/compensación antes de estar realmente disponible.','Evitar tratar un documento pendiente como efectivo ya cobrado.','Depósitos de cheques de otra institución.','El banco valida con el emisor; puede aplicarse o devolverse.','El saldo puede verse reflejado antes de que esté disponible para usar.','“Ya lo veo en saldo, ¿ya puedo gastarlo?”','No confirmes disponibilidad solo porque se vea reflejado; revisa buen cobro/estatus.',null,'Los tiempos exactos del manual 2022 deben validarse vigentes.'),
        S('Cheque devuelto','Cheque que no pudo ser pagado/aplicado por una causa específica.','Identificar motivo y proceso de recuperación del documento o aclaración.','Cuando la cámara/validación rechaza el cheque.','Se consulta la clave/motivo y se sigue la ruta vigente.','Cheque devuelto por inconsistencia o falta de fondos.','“¿Por qué regresaron mi cheque?”','Busca el motivo exacto; no adivines.')
      ]
    },
    {
      id:'edc',title:'Estado de cuenta y envío',level:'Bloque 10 · Certificación fuerte',
      source:'Manual 2022 + BBVA México · consulta de estado de cuenta',
      intro:'El estado de cuenta es una fotografía del periodo. No es lo mismo que ver movimientos recientes en la app.',
      memory:['EDC = estado de cuenta · periodo, saldos, movimientos y datos del producto.'],
      related:['EDC','Fecha de corte','Movimientos','Envío','PDF'],
      sections:[
        S('Estado de cuenta (EDC)','Documento que resume movimientos, saldos y datos relevantes de un producto durante un periodo.','Revisar formalmente qué ocurrió y qué se debe pagar o comprobar.','Cuentas, TDC y otros productos que emiten EDC.','Se genera por periodos y puede consultarse por canales habilitados.','Cliente revisa los movimientos del mes anterior.','“¿Mi lista de movimientos es mi estado de cuenta?”','No; el EDC cubre un periodo y reúne información del producto.'),
        S('Periodo del EDC','Rango de fechas que cubre el documento.','Saber qué movimientos deben aparecer en ese estado de cuenta.','Al buscar una compra, pago o comisión.','Compara fecha de operación con el periodo/corte.','Compra posterior al corte puede aparecer en el siguiente EDC.','“No aparece mi compra de ayer.”','Revisa primero si corresponde al periodo.'),
        S('Envío / consulta digital','Acceso al EDC por app, bbva.mx u otros canales disponibles.','Obtener el documento sin depender de papel.','Cuando el cliente necesita consultar, descargar o recibir su estado.','BBVA publica consulta/descarga digital para productos compatibles.','Cliente descarga el PDF para revisar movimientos.','“Necesito que me manden mi estado.”','Identifica producto, periodo y canal habilitado.',null,'La ruta exacta de envío y autenticación se valida en CUC vigente.'),
        S('Fecha de corte','Día en que se cierra el periodo de una TDC u otro producto con ciclos.','Separar qué movimientos entran en el periodo actual y cuál será el saldo facturado.','TDC y productos con ciclos.','Movimientos posteriores pasan al ciclo siguiente según reglas del producto.','Compra del día posterior al corte normalmente queda para el nuevo ciclo.','“¿Por qué no está en este estado?”','Compara fecha de compra con corte.'),
        S('Qué revisar en un EDC','Titular/producto, periodo, movimientos, cargos, abonos, saldos y, en crédito, fechas y pagos requeridos.','Responder dudas de forma ordenada.','Aclaraciones y consultas de pago.','Lee primero encabezado/periodo y luego los movimientos.','Cliente pregunta por una comisión específica del mes.','“No entiendo mi estado.”','No expliques todo: ubica la duda concreta y el renglón relacionado.')
      ]
    },
    {
      id:'actualizacion',title:'Actualización de correo, teléfono y domicilio',level:'Bloque 11 · Certificación fuerte',
      source:'Manual 2022 + procesos actuales por validar en CUC',
      intro:'“Quiero actualizar mis datos” es demasiado amplio. Primero identifica exactamente qué dato quiere cambiar y para qué servicio.',
      memory:['Dato → canal → autenticación → efecto.'],
      related:['Correo','Teléfono','Domicilio','Alertas','Datos personales'],
      sections:[
        S('Actualización de correo','Cambio del correo registrado para comunicaciones o servicios que lo utilicen.','Mantener canales de contacto y recepción de información correctos.','Cuando el cliente cambió de correo o detecta uno incorrecto.','La ruta y autenticación dependen del servicio/producto afectado.','Cliente ya no usa el correo anterior.','“Quiero cambiar mi correo.”','Pregunta si se refiere a datos generales, alertas, estado de cuenta u otro servicio.',null,'No asumas que todos los sistemas actualizan el dato al mismo tiempo.'),
        S('Actualización de teléfono','Cambio del número celular/teléfono asociado a datos o servicios.','Mantener contacto, alertas y factores de seguridad cuando corresponda.','Cambio de número, pérdida de línea o registro incorrecto.','Puede afectar canales digitales y requerir validaciones específicas.','Cliente cambió de compañía y número.','“Ya no tengo el celular anterior.”','Identifica qué servicio usa ese teléfono y sigue el proceso exacto.',null,'Por seguridad, el tratamiento del teléfono puede ser más sensible.'),
        S('Actualización de domicilio','Cambio de dirección registrada.','Mantener datos contractuales, correspondencia y verificaciones actualizados.','Mudanza o corrección de domicilio.','Puede requerir documentación/canal diferente según producto.','Cliente se mudó y quiere recibir correspondencia correctamente.','“Mi dirección está vieja.”','Confirma producto y requisitos vigentes.'),
        S('Alertas BBVA','Servicio de notificaciones asociado a operaciones y seguridad.','Informar movimientos y eventos relevantes.','Cuando el cliente cambia datos de contacto o no recibe alertas.','Revisa qué dato está asociado y si el servicio está activo.','Cliente cambió teléfono y dejó de recibir notificaciones.','“Ya no me llegan mensajes.”','No lo trates solo como cambio de teléfono: revisa también el servicio de alertas.'),
        S('Datos vs seguridad','Algunos datos son contacto; otros funcionan también como factores o vínculos de seguridad.','Evitar cambios indebidos.','Cuando la modificación puede afectar acceso o autenticación.','Aplica el flujo autorizado y no reveles datos previos innecesariamente.','Cambiar un teléfono asociado al canal digital puede requerir más controles.','“Solo cambie el número, no pasa nada.”','Explica que ciertos datos también protegen la cuenta.')
      ]
    },
    {
      id:'pagos',title:'Pagos de servicios, domiciliación y cargos recurrentes',level:'Bloque 12 · Certificación fuerte',
      source:'Manual 2022 + BBVA México · pagos y servicios digitales',
      intro:'Los tres pueden verse como “cobros de servicios”, pero no son lo mismo y la cancelación/aclaración cambia según el tipo.',
      memory:['Pago manual ≠ domiciliación ≠ cargo recurrente.'],
      related:['Pago de servicios','CIE','Domiciliación','Cargo recurrente','Duplicado'],
      sections:[
        S('Pago de servicios','Pago que el cliente realiza a una empresa o institución desde un canal bancario.','Cubrir recibos u obligaciones.','Luz, telefonía, instituciones, servicios CIE y otros disponibles.','Se captura/selecciona el servicio y los datos requeridos en el canal.','Cliente paga un recibo desde la app.','“Pagué mi servicio pero la empresa no lo refleja.”','Revisa fecha, referencia, estatus y comprobante antes de determinar aclaración.'),
        S('CIE','Esquema/referencia usada por BBVA para recibir pagos de servicios o convenios.','Identificar a la empresa y aplicar el pago al concepto correcto.','Pagos a empresas/instituciones afiliadas.','El cliente captura convenio/referencia según el servicio.','Pago a institución usando datos CIE.','“Me piden una referencia.”','Distingue convenio, referencia e importe; un dato erróneo puede cambiar el tratamiento.'),
        S('Domiciliación','Autorización para que ciertos recibos se carguen automáticamente a una cuenta conforme al acuerdo.','Evitar pagar manualmente cada periodo.','Servicios periódicos como recibos.','El cargo se intenta conforme a la instrucción registrada y condiciones del servicio.','Recibo mensual se cobra automáticamente.','“Quiero quitar el cobro automático.”','Confirma si es domiciliación a cuenta o cargo recurrente a tarjeta.'),
        S('Cargo recurrente','Cobro periódico que un comercio realiza normalmente sobre una tarjeta autorizada.','Pagar suscripciones o servicios repetitivos.','Streaming, membresías, seguros u otros comercios.','El comercio presenta cargos periódicos mientras exista la autorización/relación.','Suscripción mensual se carga a la TDC.','“Cancelé la tarjeta y volvió a cobrar.”','Identifica comercio, autorización y proceso de bloqueo/cancelación vigente.'),
        S('Pago duplicado','Mismo servicio aparentemente pagado dos veces.','Determinar si hubo dos pagos reales, uno manual más domiciliación, o un error de aplicación.','Cuando el cliente ve dos cargos similares.','Compara canal, fecha, referencia y origen de cada movimiento.','Cliente paga manualmente y además se ejecuta la domiciliación.','“Me cobraron dos veces el recibo.”','Pregunta si uno fue manual y el otro automático.'),
        S('Pago no aplicado','El banco muestra una salida/pago, pero el proveedor no lo reconoce todavía o lo rechazó.','Determinar si está en proceso, aplicado, devuelto o requiere aclaración.','Servicios CIE y otros pagos.','Revisa estatus y datos capturados, luego sigue el proceso vigente.','Empresa dice no haber recibido un pago que el cliente ve en su cuenta.','“Ya pagué y me cortaron el servicio.”','No prometas devolución inmediata; identifica el estado real.',null,'Tiempos de aplicación cambian por servicio; valida CUC/información vigente.')
      ]
    },
    {
      id:'fallecimiento',title:'Fallecimientos',level:'Bloque 13 · Certificación fuerte',
      source:'Guía pública BBVA para trámites de fallecidos 2026; proceso operativo: CUC vigente',
      intro:'Es un proceso sensible. La prioridad es identificar qué producto tenía la persona fallecida y qué solicita quien se comunica.',
      memory:['No inventes requisitos · Producto + solicitante + trámite + documentación vigente.'],
      related:['Fallecimiento','Beneficiario','Sucesión','Cancelación','Saldos','Seguros de vida'],
      sections:[
        S('Trámite por fallecimiento','Proceso para informar el fallecimiento y gestionar productos/saldos de la persona titular.','Cancelar productos, entregar saldos a quien corresponda o activar coberturas según producto.','Cuando un familiar, beneficiario o representante informa el fallecimiento.','La ruta cambia si se trata de cuentas, créditos, auto, seguros u otros productos.','Familiar solicita saber qué hacer con una cuenta del titular fallecido.','“Mi familiar falleció, ¿qué necesito?”','Primero identifica producto y relación del solicitante; después usa la guía vigente.',null,'No listes documentos de memoria si no tienes el proceso actual frente a ti.'),
        S('Beneficiario','Persona designada para recibir un beneficio o recursos conforme al producto y reglas aplicables.','Determinar a quién puede corresponder un pago o saldo.','Cuentas, seguros y otros productos con designación de beneficiarios.','La institución valida la designación y documentación antes de entregar recursos.','Seguro de vida paga la suma asegurada a beneficiarios cuando procede.','“¿Cómo sé si soy beneficiario?”','No confirmes solo por parentesco; sigue la validación del trámite.'),
        S('Sucesión','Proceso legal para transmitir bienes de una persona fallecida.','Resolver derechos patrimoniales cuando corresponde.','Puede ser testamentaria o intestamentaria.','Se tramita por las vías legales aplicables y puede intervenir albacea/representación.','No existe beneficiario aplicable y se requiere acreditar sucesión.','“No dejó testamento.”','No des asesoría legal; explica que puede requerirse sucesión y consulta la guía oficial.'),
        S('Cuentas y saldos','Recursos de depósito/inversión que deben tratarse conforme a beneficiarios, sucesión y proceso aplicable.','Entregar recursos a quien legalmente corresponda y cancelar productos.','Fallecimiento de titular de cuenta.','BBVA publica un trámite específico para cancelación de productos y entrega de saldos.','Beneficiario solicita saldo de una cuenta.','“Quiero retirar el dinero de la cuenta.”','No operes como una disposición normal; usa el proceso de fallecimiento.'),
        S('Seguros de vida','Cobertura que puede pagar una suma asegurada a beneficiarios por fallecimiento, según póliza.','Dar respaldo económico conforme a la cobertura contratada.','Al fallecer la persona asegurada y cumplirse condiciones.','Se reporta siniestro y se entrega documentación según póliza/proceso.','Beneficiarios reclaman un Seguro de Vida.','“Tenía un seguro con BBVA.”','Pide identificar póliza/producto y canaliza al proceso de siniestro correspondiente.'),
        S('Créditos y fallecimiento','Créditos pueden tener seguros o políticas específicas que determinen el saldo pendiente.','Definir cómo se liquida o continúa la obligación.','Cuando el titular de un crédito fallece.','Debe revisarse el contrato, seguro y proceso del producto.','Un crédito de nómina puede estar vinculado a seguro de vida según su contratación.','“¿La deuda desaparece?”','No generalices; revisa el producto y cobertura aplicable.')
      ]
    },
    {
      id:'nomina',title:'Nómina y portabilidad de nómina',level:'Bloque 14 · Producto fuerte',
      source:'BBVA México 2026 · Portabilidad de nómina + Manual 2022',
      intro:'Nómina es el dinero que paga el empleador; portabilidad es el mecanismo para que ese dinero termine automáticamente en otra cuenta elegida.',
      memory:['Portabilidad no cambia dónde deposita la empresa: transfiere después al banco elegido.'],
      related:['Nómina','Portabilidad','Cuenta nómina','Banco origen','Banco destino'],
      sections:[
        S('Cuenta de nómina','Cuenta utilizada para recibir pagos del empleador.','Recibir sueldo y operar los recursos.','Cuando la empresa deposita periódicamente al trabajador.','El abono llega a la cuenta donde el empleador tiene registrada la nómina.','Empresa deposita cada quincena.','“¿Mi nómina es un préstamo?”','No: nómina es ingreso; préstamo de nómina es un crédito diferente.'),
        S('Portabilidad de nómina','Servicio que transfiere automáticamente la nómina recibida en un banco hacia la cuenta elegida en otro banco.','Permitir al trabajador elegir dónde usar su nómina sin pedir a la empresa que cambie el depósito.','Cuando el cliente recibe nómina en un banco y quiere usar otro como destino.','La empresa sigue depositando en la cuenta origen; después se transfiere automáticamente al banco destino.','Nómina llega al Banco A y se transfiere a BBVA.','“¿Tengo que avisarle a Recursos Humanos?”','La portabilidad se gestiona entre bancos; explica que la cuenta origen sigue existiendo.'),
        S('Banco origen y destino','Origen es donde la empresa deposita; destino es donde el cliente quiere recibir finalmente los recursos.','Entender por qué ambas cuentas participan.','Alta, seguimiento o aclaración de portabilidad.','La transferencia se produce después de recibir la nómina en origen.','Banco origen recibe $10,000 y envía lo correspondiente a destino.','“¿Por qué veo primero el depósito en el otro banco?”','Porque ese banco sigue siendo el receptor inicial de la nómina.'),
        S('Portabilidad no recibida','Caso en el que la nómina llegó al origen pero el cliente no ve la transferencia esperada al destino.','Investigar estatus y causa.','Aclaraciones de portabilidad.','Confirma que realmente hubo abono de nómina, que la portabilidad esté activa y el movimiento esperado.','Cliente recibió nómina en origen, pero no en BBVA.','“No llegó mi portabilidad.”','Separa: no recibió nómina vs recibió nómina pero no se transfirió.'),
        S('Cancelación / cambio de portabilidad','Baja o modificación de la instrucción de portabilidad.','Dejar de transferir automáticamente o cambiar el banco destino.','Cuando el cliente cambia de preferencia.','Se sigue la ruta vigente y se confirma el estado de la solicitud.','Cliente quiere regresar la nómina al banco anterior.','“Quiero cancelar la portabilidad.”','Verifica si hay otra portabilidad activa y el proceso actual.',null,'Plazos exactos de alta/baja cambian; usa CUC/BBVA vigente.')
      ]
    },
    {
      id:'movilidad',title:'Movilidad de saldos y traspasos',level:'Bloque 15 · Certificación fuerte',
      source:'Tema interno de certificación + Manual 2022 · traspasos; definición exacta: CUC vigente',
      intro:'El nombre “movilidad de saldos” aparece en tu capacitación, pero la fuente 2022 no define un único proceso con ese nombre. Aquí separo los conceptos cercanos sin inventar la ruta interna.',
      memory:['Saldo a favor ≠ línea disponible ≠ transferencia ≠ pago.'],
      related:['Movilidad de saldos','Saldo a favor','Traspaso','TDC','Transferencia'],
      sections:[
        S('Movilidad de saldos','Nombre interno de un tema/proceso que debe confirmarse literalmente en tu CUC.','Probablemente clasifica situaciones donde un saldo se mueve o se solicita mover entre productos, pero no conviene asumir más.','Cuando tu material o sistema use ese nombre exacto.','Busca en CUC producto origen, producto destino, condiciones y efecto en saldo.','El cliente pide “mover” un saldo y primero hay que saber de qué producto a cuál.','“Quiero pasar este saldo.”','Pregunta: ¿saldo de qué producto, hacia cuál y por qué?',null,'No memorices una definición inventada: confirma la ficha exacta en CUC.'),
        S('Saldo a favor en TDC','Monto que queda a favor del cliente cuando los abonos superan el saldo deudor aplicable.','Representar dinero abonado en exceso o devoluciones que dejan balance favorable.','Pagos excedentes, devoluciones o ajustes.','El tratamiento para disponer o traspasar ese saldo depende del proceso vigente.','Cliente pagó de más y su TDC muestra saldo a favor.','“¿Puedo pasar ese dinero a mi cuenta?”','Identifica saldo a favor real y consulta la ruta de traspaso.'),
        S('Traspaso','Movimiento de recursos entre productos/cuentas cuando el servicio lo permite.','Reubicar fondos según una instrucción válida.','Solicitudes de mover dinero entre productos.','El manual 2022 menciona solicitudes de traspaso de saldo a favor de TDC como una casuística.','Cliente solicita mover un saldo a favor.','“Me equivoqué y quiero moverlo.”','Verifica origen, destino, naturaleza del saldo y si el proceso aplica.'),
        S('Transferencia equivocada','Transferencia enviada por error a una cuenta/beneficiario.','Distinguirla de movilidad de saldo interna.','Cuando el cliente dice que se equivocó al transferir.','Se identifica tipo de transferencia, estatus y proceso de aclaración/recuperación aplicable.','Cliente transfiere a un destinatario incorrecto.','“Mandé el dinero a quien no era.”','No lo confundas con pago a TDC ni con saldo a favor.'),
        S('Línea de crédito disponible','Parte de la línea autorizada que el cliente todavía puede usar.','Medir capacidad de compra/disposición en TDC.','Cuando el cliente pregunta cuánto crédito tiene disponible.','No es un saldo depositado que se pueda mover como dinero propio.','Línea $20,000; deuda $5,000; queda capacidad disponible.','“Quiero pasar mi línea a mi cuenta.”','Aclara que crédito disponible no es lo mismo que saldo a favor; podría existir un producto como EFI si tiene oferta.')
      ]
    },
    {
      id:'consumo',title:'Crédito de consumo y préstamos personales',level:'Bloque 16 · Producto fuerte',
      source:'BBVA México 2026 · préstamos personales y de nómina + capacitación',
      intro:'Un crédito de consumo entrega dinero para necesidades personales y se devuelve en pagos. Aquí importan capital, plazo, tasa, pago, saldo insoluto y capacidad de pago.',
      memory:['Crédito = dinero prestado que se devuelve · Tasa = porcentaje · Interés = costo resultante.'],
      related:['Crédito de consumo','Capital','Plazo','Mensualidad','Tasa','Saldo insoluto','CAT'],
      sections:[
        S('Crédito de consumo','Financiamiento destinado a necesidades personales, no necesariamente ligado a una compra específica.','Cubrir gastos, proyectos o imprevistos y pagarlos a lo largo del tiempo.','Préstamos personales, de nómina y otros créditos al consumo.','El banco entrega capital y el cliente lo devuelve según plazo, pagos, tasa y contrato.','Cliente recibe $30,000 y los paga en mensualidades.','“¿Es dinero mío?”','Es dinero prestado; genera una obligación de pago.'),
        S('Capital','Monto principal prestado o saldo principal pendiente.','Distinguir la deuda base de intereses/comisiones.','Al contratar y durante la amortización.','Cada pago puede reducir capital además de cubrir otros conceptos.','Préstamo inicial de $50,000.','“¿Por qué pago más de lo que me prestaron?”','Porque el costo puede incluir intereses, IVA y comisiones según contrato.'),
        S('Plazo','Tiempo acordado para pagar el crédito.','Distribuir la deuda en pagos.','Desde contratación hasta liquidación.','Un plazo más largo suele repartir pagos en más periodos, pero el costo total puede cambiar.','Crédito a 24 meses.','“¿Puedo escoger cuánto tiempo?”','Depende de la oferta/producto; consulta opciones vigentes.'),
        S('Pago fijo / mensualidad','Importe periódico previsto por el plan de crédito.','Amortizar la deuda de forma ordenada.','Cada fecha de pago.','Puede incluir capital, intereses e impuestos conforme al contrato.','Pago mensual programado durante el plazo.','“¿Mi pago siempre será igual?”','Depende del tipo de crédito; revisa si la tasa/pago son fijos.'),
        S('Saldo insoluto','Capital que todavía no se ha pagado.','Calcular deuda pendiente e intereses según el producto.','Después de uno o varios pagos.','Va disminuyendo conforme se amortiza capital.','Después de varios pagos, el saldo insoluto es menor que el crédito original.','“¿Cuánto me falta realmente?”','Distingue saldo insoluto de total de pagos futuros.'),
        S('Capacidad de pago','Evaluación de cuánto puede pagar una persona sin comprometer en exceso sus finanzas.','Ayudar a determinar si un crédito es adecuado y cuánto puede otorgarse.','Evaluación y oferta de crédito.','El banco considera ingresos, deudas, historial y otros factores.','Dos clientes con mismo ingreso pueden recibir ofertas diferentes.','“¿Por qué no me prestan lo mismo que a otra persona?”','Las ofertas dependen de evaluación individual.')
      ]
    },
    {
      id:'efi',title:'EFI · Efectivo Inmediato',level:'Bloque 17 · Producto fuerte',
      source:'Capacitación pública BBVA EFI 2026 + BBVA México · Efectivo Inmediato',
      intro:'La sigla que sí aparece públicamente en capacitación BBVA es EFI: Efectivo Inmediato. Es una oferta para disponer de parte de la línea de una TDC y pagarla a plazo.',
      memory:['EFI = Efectivo Inmediato · usa línea de TDC, no saldo de cuenta.'],
      related:['EFI','Efectivo Inmediato','TDC','Línea de crédito','Oferta preaprobada'],
      sections:[
        S('EFI / Efectivo Inmediato','Producto/oferta que permite disponer de efectivo usando crédito disponible de una TDC, cuando BBVA ofrece la invitación.','Obtener liquidez sin hacer una compra con la tarjeta.','Cuando el cliente tiene TDC, crédito disponible y una oferta vigente/preaprobada.','El cliente elige monto y plazo dentro de la oferta; el dinero se deposita/dispone según canal y se paga conforme al plan.','Cliente tiene una invitación de Efectivo Inmediato en Oportunidades.','“Me ofrecen efectivo desde mi tarjeta.”','Aclara que consume crédito y genera pagos/costos según la oferta.'),
        S('Oferta preaprobada','Invitación que BBVA muestra a determinados clientes después de una evaluación.','Definir quién puede contratar EFI y bajo qué condiciones.','App, bbva.mx, ATM u otros canales cuando exista oferta.','No todos los clientes tienen la misma oferta ni siempre está disponible.','Cliente A ve EFI y cliente B no.','“¿Por qué a mí no me aparece?”','No prometas disponibilidad; depende de la evaluación/oferta.'),
        S('Línea disponible usada por EFI','Crédito disponible de la TDC del que se toma el monto.','Financiar el efectivo entregado.','Al contratar EFI.','La disposición reduce capacidad disponible y se convierte en una obligación a plazo.','TDC con línea disponible permite tomar una parte como EFI.','“¿Es dinero gratis de mi línea?”','No; es financiamiento que debe pagarse.'),
        S('Tasa fija preferencial','Tasa definida para la disposición EFI según la oferta, que BBVA publicita como preferencial frente a ciertas disposiciones ordinarias.','Calcular el costo del financiamiento durante el plazo.','Cuando se contrata la oferta.','Se mantiene conforme a las condiciones de esa disposición.','Cliente compara EFI con retirar efectivo normal de TDC.','“¿Qué tasa me van a cobrar?”','Consulta la tasa exacta de SU oferta; no uses una tasa genérica.'),
        S('Plazo y pagos','Número de periodos elegidos para liquidar la disposición.','Convertir el monto en pagos programados.','Al contratar y durante la vigencia.','Cada disposición puede tener condiciones propias; los pagos aparecen relacionados con la TDC.','Cliente toma EFI y lo paga en parcialidades.','“¿Puedo adelantar?”','BBVA publica pagos anticipados sin penalización en este producto, pero revisa la oferta/contrato vigente.'),
        S('IFE vs EFI','IFE puede aparecer como identificación antigua (Instituto Federal Electoral) en documentos; para el producto de efectivo, la sigla pública verificada es EFI.','Evitar memorizar una sigla equivocada.','Cuando en notas de capacitación veas “IFE” y el contexto sea un producto de TDC.','Confirma el nombre literal en tu CUC o presentación.','“Me dijeron IFE, ¿es Efectivo Inmediato?”','Si el contexto es disposición de la TDC, busca “EFI / Efectivo Inmediato” y confirma.',null,'No cambies una sigla interna sin validar si tu material realmente usa otra.')
      ]
    },
    {
      id:'tdc',title:'Tarjeta de crédito, tasa, anualidad, pagos y CAT',level:'Bloque 18 · Producto fuerte',
      source:'Manual 2022 · cascada de pagos + BBVA México 2026',
      intro:'Este es uno de los temas más importantes: línea, saldo deudor, corte, fecha límite, PPNGI, pago mínimo, intereses, comisiones, anualidad y CAT.',
      memory:['Tasa ≠ interés ≠ comisión ≠ anualidad ≠ CAT.'],
      related:['TDC','Línea','Corte','PPNGI','Pago mínimo','Tasa','Interés','Anualidad','CAT'],
      sections:[
        S('Tarjeta de crédito (TDC)','Medio de pago que utiliza una línea de crédito autorizada por el banco.','Comprar o disponer usando crédito y pagar después.','Compras, cargos recurrentes, promociones y disposiciones.','Cada operación consume parte de la línea y forma saldo deudor según el ciclo.','Línea $20,000 y compra $3,000 → aumenta deuda y reduce disponible.','“¿Por qué debo si todavía tengo disponible?”','Deuda y disponible son conceptos opuestos dentro de la línea.'),
        S('Línea de crédito','Monto máximo de crédito autorizado para utilizar.','Definir capacidad disponible de la TDC.','Compras y disposiciones.','Al pagar capital/deuda, parte de la línea puede liberarse nuevamente conforme al producto.','Línea $30,000; usas $10,000; queda capacidad para más operaciones.','“¿La línea es dinero mío?”','No; es crédito autorizado.'),
        S('Fecha de corte','Día que cierra un ciclo de la TDC.','Determinar qué movimientos forman el estado de cuenta de ese periodo.','Cada ciclo mensual.','Lo posterior al corte pasa al siguiente ciclo según reglas.','Compra después del corte aparece en el próximo estado.','“¿Por qué no está en mi estado?”','Compara fecha de compra y fecha de corte.'),
        S('Fecha límite de pago','Fecha máxima indicada para cubrir el pago requerido del periodo.','Evitar atrasos conforme al estado de cuenta.','Después del corte.','El cliente debe pagar al menos lo exigido antes de esa fecha.','Estado indica fecha límite y opciones de pago.','“¿Hasta cuándo puedo pagar?”','Usa la fecha mostrada en el EDC vigente.'),
        S('Pago mínimo','Cantidad mínima exigida para mantener el crédito al corriente.','Evitar incumplimiento inmediato, aunque no liquida toda la deuda.','Cada estado de cuenta cuando existe saldo.','Pagar solo el mínimo puede dejar saldo financiado que genere intereses.','Deuda alta, pago mínimo pequeño: el resto sigue pendiente.','“Si pago el mínimo ya no pago intereses?”','No necesariamente; pago mínimo no es lo mismo que PPNGI.'),
        S('PPNGI','Pago para no generar intereses indicado para el periodo.','Cubrir el saldo facturado que debe pagarse para evitar intereses ordinarios sobre el componente correspondiente, según producto/EDC.','Después del corte, antes de la fecha límite.','El manual lo coloca como la primera referencia de la cascada de pagos.','Cliente cubre el PPNGI completo del estado.','“¿Cuál pago evita intereses?”','Revisa el PPNGI mostrado en el estado; no lo confundas con saldo total o mínimo.'),
        S('Cascada de pagos','Orden en que un pago se aplica a componentes del saldo de TDC.','Explicar por qué un abono puede no reducir exactamente el saldo que el cliente imaginaba.','Cuando existen PPNGI, revolvente, promociones/diferidos y otros componentes.','El manual 2022 separa PPNGI, pago mínimo, revolvente y capital diferido; la aplicación exacta se consulta en sistema.','Cliente paga y cree que abonó a una promoción específica.','“Pagué, ¿por qué sigue apareciendo la promoción?”','Revisa composición y aplicación del pago antes de explicar.'),
        S('Saldo revolvente','Saldo financiado de la TDC que puede generar intereses conforme al contrato.','Permitir que parte de la deuda continúe al siguiente ciclo.','Cuando no se liquida el saldo aplicable.','El saldo pendiente sigue formando parte de la deuda y puede generar intereses.','Cliente paga menos que el monto para no generar intereses.','“¿Qué es revolvente?”','Explícalo como deuda que sigue financiándose.'),
        S('Tasa de interés','Porcentaje usado para calcular el costo del financiamiento.','Determinar cuánto cuesta usar crédito cuando corresponde cobrar intereses.','TDC, préstamos y otros financiamientos.','La tasa se aplica según contrato y base de cálculo; el resultado monetario es el interés.','Dos tarjetas pueden tener tasas diferentes.','“¿Tasa e interés son lo mismo?”','Tasa = porcentaje; interés = monto/costo calculado.'),
        S('Interés','Costo monetario derivado de financiar una deuda conforme a una tasa y reglas del producto.','Cobrar el uso del crédito a lo largo del tiempo.','Cuando el saldo genera intereses según contrato.','No se calcula simplemente como “tasa × lo que faltó” sin revisar la metodología del producto.','Saldo financiado durante el ciclo genera interés.','“¿Por qué me cobraron interés si pagué algo?”','Revisa PPNGI, saldo promedio/base de cálculo y fechas.'),
        S('Comisión','Cobro por un servicio, producto u operación específico.','Remunerar ciertos servicios o eventos contractuales.','Contratación, administración, disposición u otras operaciones cuando aplique.','Debe corresponder a un concepto previsto y vigente.','Una disposición puede tener comisión distinta al interés.','“¿Comisión es interés?”','No; son conceptos diferentes.'),
        S('Anualidad / administración de tarjeta','Nombre común de la comisión periódica por administración del titular; BBVA hoy la denomina “comisión por administración de la tarjeta del titular” en su oferta.','Cubrir la administración del producto cuando la tarjeta la contempla.','Según el contrato/tarjeta.','Puede existir, ser $0 o variar por producto; no todas las tarjetas cobran lo mismo.','Una tarjeta puede no cobrar esta comisión y otra sí.','“¿Todas tienen anualidad?”','No; revisa el producto vigente.',null,'No memorices importes porque cambian por tarjeta y fecha.'),
        S('CAT','Costo Anual Total: indicador estandarizado para comparar el costo integral de un crédito.','Comparar créditos incorporando varios costos bajo una metodología común.','Publicidad, contratos y comparación de productos de crédito.','Se expresa como porcentaje informativo; no equivale a “lo que pagarás exactamente” cada año.','Dos créditos con tasas parecidas pueden tener CAT distinto por otros costos.','“¿CAT es la tasa?”','No; la tasa es un componente y el CAT integra más elementos.'),
        S('Meses sin intereses (MSI)','Promoción para pagar una compra en parcialidades sin interés por ese financiamiento si se cumplen condiciones.','Distribuir el costo de una compra.','Comercios/promociones participantes.','Cada mensualidad entra al esquema de pago del estado según la promoción.','Compra de $12,000 a 6 MSI → seis parcialidades de $2,000, si aplica.','“¿Puedo dejar de pagar la mensualidad?”','No; MSI no significa que no exista pago mensual.',null,'Promociones y condiciones vigentes se revisan en la guía actual.')
      ]
    },
    {
      id:'seguros',title:'Seguros: conceptos, productos y venta responsable',level:'Bloque 19 · Producto fuerte',
      source:'BBVA Seguros México 2026 + educación financiera BBVA',
      intro:'Seguros es un mundo propio. Aprende primero el vocabulario: riesgo, póliza, prima, cobertura, suma asegurada, deducible, beneficiario, siniestro, vigencia y exclusiones.',
      memory:['Seguro = transferir/proteger un riesgo bajo condiciones de una póliza.'],
      related:['Seguro','Póliza','Prima','Cobertura','Deducible','Siniestro','Beneficiario','Suma asegurada'],
      sections:[
        S('Seguro','Contrato de protección frente a riesgos definidos en una póliza.','Reducir el impacto económico de ciertos eventos inesperados.','Vida, auto, hogar, salud, objetos, accidentes y otros riesgos.','El cliente paga una prima y la aseguradora cubre eventos previstos bajo condiciones.','Seguro de auto cubre determinados daños conforme al plan contratado.','“¿Para qué necesito un seguro?”','Relaciona la protección con una necesidad real, no con presión de venta.'),
        S('Póliza','Documento/contrato que establece coberturas, sumas, vigencia, exclusiones, asegurados y condiciones.','Saber exactamente qué está contratado.','Después de contratar y durante cualquier aclaración o siniestro.','Se consulta antes de prometer que algo está cubierto.','Cliente cree tener robo parcial, pero hay que confirmarlo en su póliza.','“¿Mi seguro cubre esto?”','Primero revisa cobertura y condiciones.'),
        S('Prima','Precio que se paga por el seguro.','Mantener la cobertura contratada conforme al esquema de pago.','Contratación y renovaciones/pagos.','Puede pagarse en la periodicidad definida por el producto.','Seguro con prima mensual.','“¿Prima es deducible?”','No: prima es costo del seguro; deducible es participación del asegurado en ciertos siniestros.'),
        S('Cobertura','Riesgo o evento que el seguro protege.','Definir qué situaciones pueden generar indemnización o servicio.','Al contratar y al reportar un siniestro.','Cada producto tiene coberturas básicas y/o opcionales.','Auto: responsabilidad civil, daños materiales o robo total según plan.','“¿Qué incluye mi seguro?”','Enumera solo lo que realmente aparece en su póliza/producto.'),
        S('Suma asegurada','Monto máximo o beneficio establecido para una cobertura.','Delimitar cuánto puede pagar la aseguradora cuando procede.','Indemnizaciones de vida, daños y otras coberturas.','Se aplica conforme a la póliza, deducibles, límites y condiciones.','Seguro de vida establece una suma para beneficiarios.','“¿Eso es lo que me van a pagar siempre?”','Es un límite/beneficio contractual; el pago real depende del siniestro y condiciones.'),
        S('Deducible','Parte del costo de ciertos siniestros que corresponde al asegurado.','Compartir el costo del riesgo en coberturas que lo contemplan.','Frecuente en auto y otros seguros de daños.','El asegurado cubre el deducible y la aseguradora cubre lo procedente conforme a póliza.','Daño de auto sujeto a deducible contratado.','“¿Por qué pago si tengo seguro?”','Porque algunas coberturas incluyen deducible.'),
        S('Siniestro','Evento ocurrido que puede estar cubierto por el seguro.','Activar el proceso de asistencia, ajuste o indemnización.','Accidente, robo, fallecimiento, enfermedad u otro evento cubierto.','Se reporta y la aseguradora valida hechos/documentos contra póliza.','Choque de auto se reporta como siniestro.','“Tuve un accidente, ¿qué hago?”','Identifica seguro y emergencia; canaliza al proceso de siniestros.'),
        S('Beneficiario','Persona que puede recibir el beneficio de ciertas coberturas, especialmente vida.','Definir quién recibe la suma asegurada cuando ocurre el evento cubierto.','Seguros de vida y productos similares.','Debe constar conforme a la póliza y se valida en el trámite.','Titular designa a familiares como beneficiarios.','“¿Mi familia recibe el seguro automáticamente?”','Depende de beneficiarios y condiciones; revisa la póliza.'),
        S('Asegurado, contratante y beneficiario','Asegurado es la persona/riesgo protegido; contratante celebra/paga el seguro; beneficiario recibe el beneficio cuando aplica.','Evitar confundir roles.','Cuando quien paga no es exactamente quien recibe el beneficio.','La póliza define cada rol.','Una persona contrata un seguro de vida sobre sí misma y designa beneficiarios.','“Yo pago, entonces yo soy beneficiario?”','No necesariamente; revisa los roles de la póliza.'),
        S('Vigencia y renovación','Vigencia es el periodo en que la cobertura está activa; renovación prolonga o inicia un nuevo periodo según condiciones.','Saber si el seguro estaba activo cuando ocurrió el evento.','Contratación, vencimiento y siniestros.','Se verifica fecha de inicio/fin y reglas de renovación.','Accidente fuera de vigencia puede no estar cubierto.','“¿Todavía está activo?”','Consulta vigencia real, no solo fecha de contratación.'),
        S('Exclusiones','Situaciones expresamente no cubiertas por la póliza.','Delimitar el alcance del seguro.','Al explicar cobertura o analizar un siniestro.','Se revisan en condiciones generales/específicas.','Cierto uso del vehículo puede estar excluido según póliza.','“Pero mi seguro dice cobertura amplia.”','“Amplia” no significa todo; revisa exclusiones.'),
        S('Seguro de vida','Seguro que paga un beneficio a beneficiarios por fallecimiento cuando procede, y puede incluir otras coberturas.','Dar respaldo económico a la familia.','Necesidad de protección familiar, créditos u objetivos patrimoniales.','Se contrata una suma/cobertura y, ante siniestro, se valida la reclamación.','Familia recibe apoyo económico si se cumplen condiciones.','“¿Qué protege un seguro de vida?”','Explica finalidad y luego las coberturas exactas del producto.'),
        S('Seguro de auto','Seguro que protege riesgos relacionados con el vehículo y responsabilidad frente a terceros según plan.','Cubrir daños, robo, responsabilidad y asistencias cuando estén contratadas.','Propietarios/conductores.','BBVA ofrece coberturas básicas y opcionales; puede existir deducible.','Choque con daños materiales.','“¿Me cubre cualquier choque?”','Revisa plan, cobertura, deducible y exclusiones.'),
        S('Seguro de salud / gastos médicos','Productos que apoyan con gastos o servicios de salud según cobertura.','Reducir impacto económico de atención médica.','Urgencias, estudios, hospitalización u otros eventos según producto.','Cada seguro define red, reembolso, topes, deducibles/copagos o beneficios.','Seguro cubre determinados gastos hospitalarios.','“¿Puedo ir a cualquier hospital?”','No generalices; depende del producto y póliza.'),
        S('Seguro de hogar y objetos','Protección para vivienda, pertenencias u objetos específicos.','Cubrir daños, robo o asistencias definidos.','Propietarios/inquilinos o clientes con bienes a proteger.','Se seleccionan coberturas y sumas según producto.','Seguro de hogar cubre ciertos daños a inmueble/contenidos.','“¿Mi celular entra en hogar?”','Depende del alcance; puede existir un seguro específico de celular.'),
        S('Seguros BBVA disponibles','BBVA publica categorías de auto/moto, vida, salud, hogar, ahorro, accidentes/enfermedades, mascotas y objetos personales, entre otras.','Entender que “seguro” no es un solo producto.','Venta cruzada y consultas generales.','Primero detecta qué quiere proteger el cliente y después busca el producto adecuado.','Cliente preocupado por robo de celular vs cliente que busca proteger a su familia.','“¿Qué seguro me conviene?”','Haz sondeo de necesidad, presupuesto y riesgo; no recites todo el catálogo.'),
        S('Venta responsable de seguros','Ofrecer solo cuando existe una necesidad real y explicar condiciones relevantes.','Evitar venta por presión y reducir malas expectativas.','Después de resolver la necesidad principal o cuando el cliente pregunta por protección.','Sondea: qué quiere proteger, qué riesgo le preocupa, qué ya tiene y cuánto puede pagar.','Cliente comenta que acaba de comprar auto.','“¿Algo más?”','Puedes explorar protección de auto si es pertinente, explicando cobertura y costo con claridad.',null,'Nunca prometas cobertura que no esté en la póliza.')
      ]
    },
    {
      id:'transferencias',title:'Transferencias, SPEI, CEP y OPI',level:'Bloque 20 · Producto y operación',
      source:'Manual 2022 + BBVA México + Banco de México; horarios/importes vigentes se consultan actuales',
      intro:'Para transferencias piensa: origen, destino, banco, identificador, estatus y comprobante. Después separa SPEI nacional de OPI internacional.',
      memory:['Interbancaria México → SPEI/CLABE · Comprobante → CEP · Internacional → OPI/SWIFT.'],
      related:['Transferencia','SPEI','CEP','CLABE','Clave de rastreo','OPI','SWIFT'],
      sections:[
        S('Transferencia','Envío de dinero de una cuenta a otra.','Mover recursos sin usar efectivo.','Entre cuentas propias, BBVA u otros bancos.','Se selecciona origen, beneficiario/destino, importe y se autoriza por el canal.','Cliente envía dinero desde su cuenta BBVA a otra cuenta.','“Quiero transferir.”','Identifica si es propia, BBVA, interbancaria o internacional.'),
        S('SPEI','Sistema de Pagos Electrónicos Interbancarios operado por Banco de México.','Procesar transferencias entre instituciones participantes en México.','Transferencias interbancarias compatibles.','El banco ordenante envía la instrucción al sistema y el banco receptor procesa el abono.','BBVA → otro banco mediante SPEI.','“No llegó mi SPEI.”','Revisa clave de rastreo/referencia, banco, fecha, importe y estatus.'),
        S('CEP','Comprobante Electrónico de Pago generado cuando existe la información requerida de una operación SPEI.','Acreditar datos y estatus de un pago interbancario.','Seguimiento de transferencias SPEI.','Se consulta con datos de la operación en el portal de Banco de México o enlaces disponibles.','Cliente descarga CEP para demostrar un pago.','“¿El CEP significa que ya está en la cuenta?”','Interpreta el estatus y no confundas comprobante con disponibilidad final en casos excepcionales.'),
        S('Clave de rastreo','Identificador asignado a una transferencia SPEI para seguimiento.','Buscar el pago y distinguirlo de otros.','Consultas de SPEI/CEP.','Se usa junto con otros datos según la consulta.','Cliente tiene clave de rastreo y quiere saber qué pasó.','“¿Dónde reviso mi transferencia?”','Usa clave/referencia y los datos correctos del pago.'),
        S('Estatus SPEI','Estados como en proceso, liquidado, rechazado, devuelto u otros que describen dónde está el pago.','Saber si el dinero sigue procesándose, fue aceptado o regresó.','Cuando una transferencia no parece llegar.','Interpreta el estado actual y sigue el proceso correspondiente.','“Devuelto” indica que el importe regresó/procede a regresar según el estado.','“No llegó.”','No respondas solo con “espere”; primero consulta el estatus.',null,'Los nombres/efectos operativos se validan en la fuente vigente de Banxico/CUC.'),
        S('OPI','Orden de Pago Internacional para enviar o recibir recursos entre países, según servicio.','Realizar transferencias internacionales.','Envíos/recepciones fuera del sistema doméstico normal.','Puede requerir banco, beneficiario, moneda y códigos internacionales.','Cliente quiere recibir dólares desde otro país.','“Me mandaron dinero del extranjero.”','Pregunta país, moneda, banco origen/destino y tipo de operación.'),
        S('SWIFT / BIC','Código para identificar instituciones financieras en operaciones internacionales.','Dirigir correctamente una transferencia entre bancos.','OPI y transferencias internacionales.','Se captura/valida según el banco receptor y el país.','Remitente necesita SWIFT del banco receptor.','“¿SWIFT es mi CLABE?”','No; SWIFT identifica banco/institución y CLABE identifica cuenta en México.'),
        S('IBAN, ABA y Transit','Identificadores bancarios usados en distintos países/sistemas.','Completar datos necesarios de una transferencia internacional.','Dependiendo del país destino/origen.','No todos se usan en todos los países.','Europa puede usar IBAN; EE. UU. puede usar ABA.','“¿Cuál me piden?”','Identifica país y banco; no inventes un formato universal.'),
        S('Banco corresponsal','Institución intermediaria que puede participar en una transferencia internacional.','Conectar bancos que no liquidan directamente entre sí.','Algunas OPI.','Puede intervenir en ruta, tiempos y costos.','Transferencia pasa por un banco intermediario antes del receptor.','“¿Por qué aparece otro banco?”','Puede ser corresponsal; revisa detalle de la OPI.')
      ]
    },
    {
      id:'llamada',title:'Cómo pensar una llamada completa y venta cruzada',level:'Bloque 21 · Trabajo real',
      source:'Síntesis Manual 2022 + capacitación pública BBVA 2026',
      intro:'No necesitas memorizar 500 respuestas. Necesitas una secuencia mental para ubicar el problema, resolver con el proceso vigente y después detectar una oportunidad pertinente.',
      memory:['Producto → intención → estado → sondeo → autenticación → sistema → CUC → explicación → cierre.'],
      related:['Sondeo','Tipificación','CUC','Aclaración','Venta cruzada','Cierre'],
      sections:[
        S('1. Identifica el producto','Define si habla de cuenta, TDD, TDC, crédito, seguro, cheque, nómina, transferencia o app.','Elegir reglas y proceso correctos.','Al inicio de casi cualquier llamada.','Haz una pregunta corta si la frase es ambigua.','“Mi tarjeta no pasa.” → preguntar si es débito o crédito.','“Tengo un problema con mi cuenta.”','Ubica producto antes de entrar al detalle.'),
        S('2. Identifica la intención','Define qué quiere: consultar, pagar, modificar, cancelar, aclarar, bloquear, contratar o dar seguimiento.','Evitar resolver algo diferente a lo que pidió.','Después de identificar producto.','Resume en una frase lo que entendiste.','“Quiere saber por qué aparece este cargo, ¿correcto?”','“Necesito ayuda.”','Convierte “ayuda” en una intención concreta.'),
        S('3. Sondea hechos','Pregunta lo necesario para entender fecha, importe, canal, estatus y contexto.','Clasificar bien antes de operar.','Movimientos, fraude, transferencias y rechazos especialmente.','Pregunta por hechos verificables y evita sugerir respuestas.','“No reconozco” → comercio, fecha, adicional, suscripción, duplicado.','“Me robaron.”','Aclara si fue tarjeta, teléfono, datos o dinero y qué movimientos existen.'),
        S('4. Autentica cuando corresponda','Cumple el nivel de seguridad del proceso.','Proteger datos y acciones.','Antes de consultar o ejecutar procesos que lo exijan.','Usa MAU/CUC vigente.','Cambio de teléfono puede exigir un flujo específico.','“Ya me conoce el banco.”','Explica la protección y sigue el control.'),
        S('5. Revisa sistema y CUC','Combina lo que ves en sistema con el documento/proceso vigente.','Tomar decisiones con información actual.','Antes de dar instrucciones operativas o plazos.','Busca por producto + intención + palabra clave.','TDD + rechazo + restricción.','“¿Qué hago ahora?”','No respondas desde memoria vieja si el dato puede cambiar.'),
        S('6. Explica simple','Traduce el resultado a lenguaje cotidiano.','Que el cliente entienda qué pasó y qué sigue.','Después de revisar.','Una idea por vez: qué ocurrió → qué significa → siguiente paso.','“El movimiento está en tránsito; todavía se está procesando.”','“No entendí.”','Evita acrónimos si el cliente no los necesita.'),
        S('7. Cierra y confirma','Verifica que la duda principal quedó resuelta y deja expectativa real.','Reducir llamadas repetidas y confusión.','Al final de la solución.','Resume acción, plazo solo si está validado y canal de seguimiento.','“Hoy quedó reportado con folio X; puede consultarlo por…”','“Entonces, ¿qué sigue?”','Responde con un siguiente paso concreto.'),
        S('8. Venta cruzada pertinente','Oferta adicional relacionada con una necesidad real del cliente.','Aportar valor sin distraer de la atención principal.','Después de resolver o cuando una necesidad aparece naturalmente.','Sondea necesidad y explica beneficio, costo y condiciones; acepta un no.','Cliente recién compró auto → explorar seguro de auto si existe oferta pertinente.','“No me interesa.”','Agradece y cierra; no insistas de forma invasiva.'),
        S('Mapa rápido de oferta','Nómina → portabilidad/préstamo si aplica; TDC → EFI/incremento si hay oferta; patrimonio/riesgo → seguro; necesidad de liquidez → crédito adecuado.','Relacionar producto con necesidad, no vender al azar.','Solo cuando exista pertinencia y oferta autorizada.','Primero necesidad, después producto.','Cliente menciona gastos imprevistos y tiene una oferta preaprobada.','“Necesito dinero.”','No asumas qué producto: pregunta monto, propósito y capacidad; luego revisa opciones.',null,'Nunca inventes una oferta ni prometas aprobación.')
      ]
    }
  ];

  guideTopics.splice(0,guideTopics.length,...topics);
  const version='course-v3-certification';
  if(localStorage.getItem('bancaCourseVersion')!==version){
    localStorage.setItem('bancaCourseVersion',version);
    localStorage.setItem('bancaGuideIndex','0');
    if(typeof guideIndex!=='undefined') guideIndex=0;
  }

  if(typeof renderGuideOverview==='function') renderGuideOverview();
  if(typeof renderGuideNav==='function') renderGuideNav();
  if(typeof showGuideTopic==='function') showGuideTopic(0,false);
})();