// v21 · Segunda explicación + analogías para estudiar sin perderse.
(function(){
  if(typeof guideTopics==='undefined' || !Array.isArray(guideTopics)) return;

  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const map={
    'banco':['Es la empresa que organiza el dinero y los servicios financieros: guarda, mueve, presta y protege.','Imagínalo como una plaza enorme: dentro hay “locales” distintos. Uno es cuentas, otro tarjetas, otro préstamos, otro seguros.'],
    'cliente':['Eres tú como persona dentro del banco; tus cuentas y tarjetas son cosas que tienes, no “tú”.','Como en un videojuego: tú eres el jugador y tus cuentas, tarjetas y créditos son los objetos de tu inventario.'],
    'producto bancario':['Es cada cosa concreta que el banco te ofrece o que tú contratas.','Piensa en un menú: cuenta, TDC, préstamo y seguro son platillos distintos; aunque los pida la misma persona, cada uno tiene reglas diferentes.'],
    'cuenta':['Es el lugar donde el banco lleva el registro de tu dinero y movimientos.','La cuenta es la casa; la tarjeta es una llave para entrar y usar lo que hay dentro. Si cambias la llave, la casa sigue existiendo.'],
    'saldo':['Es la cantidad que hay o que se debe en ese producto en ese momento.','Como revisar tu cartera: el número que ves te dice cuánto hay. En crédito, en cambio, puede decir cuánto debes.'],
    'cargo y abono':['Cargo normalmente resta dinero o aumenta deuda; abono normalmente mete dinero o reduce deuda.','Dos flechas: cargo ↓ te quita o te hace deber más; abono ↑ te mete dinero o te ayuda a deber menos.'],
    'disponible':['Es lo que sí puedes usar ahora mismo, no necesariamente todo lo que ves como saldo.','Tienes 10 manzanas, pero 3 ya están apartadas para un pedido. Ves 10, pero solo 7 están libres para comerte.'],

    'numero de cliente':['Es el dato que identifica a la persona, no a una tarjeta o cuenta específica.','Tú eres un alumno con una matrícula; puedes cursar cinco materias, pero tu matrícula sigue identificándote a ti.'],
    'numero de contrato':['Identifica el acuerdo/producto que tienes contratado con el banco.','Como el número de contrato de tu internet: identifica ese servicio y sus reglas, no tu casa ni tu persona completa.'],
    'numero de cuenta':['Es el número propio de una cuenta.','Como el número de departamento dentro de un edificio: señala exactamente cuál cuenta es.'],
    'clabe':['Es la dirección bancaria de 18 dígitos que sirve para mandar dinero entre bancos en México.','Como una dirección para paquetería: si alguien de “otra colonia” bancaria quiere mandarte un paquete de dinero, necesita la dirección correcta.'],
    'numero de tarjeta':['Identifica la tarjeta/plástico, no toda la cuenta.','La tarjeta es como una llave con número propio; si te dan otra llave, tu casa puede seguir siendo la misma.'],
    'bin iin':['Son los primeros dígitos que ayudan a reconocer qué tipo de tarjeta/emisor es.','Como ver el prefijo de un teléfono y saber de qué zona viene antes de leer todo el número.'],
    'cvv nip y token':['Son tres llaves de seguridad distintas y no sirven para lo mismo.','Piensa en tres cerraduras: una para ciertas compras, otra para ATM/operaciones y otra que crea una llave nueva de un solo uso.'],
    'tid tarjeta instantanea definitiva':['Es una tarjeta que ciertos procesos pueden entregar de forma inmediata; el uso exacto depende del producto actual.','Como cuando te imprimen una credencial al momento en vez de mandártela días después.'],

    'tus productos en la app':['La app junta en una pantalla las cosas que tienes con el banco.','Como la pantalla de inicio de una consola: ves varios juegos, pero entrar a uno no significa estar dentro de los demás.'],
    'consulta de saldo y movimientos':['Sirve para ver cuánto tienes/debes y qué operaciones han ocurrido.','Como revisar el historial de pedidos: ves qué pasó, cuándo y por cuánto.'],
    'estado de cuenta digital':['Es el resumen formal de un periodo, no solo una lista de lo que pasó hoy.','Como el resumen mensual de Spotify: junta todo un periodo; tus movimientos recientes serían solo “lo que escuchaste hoy”.'],
    'tarjeta digital':['Es otra forma de usar tu misma tarjeta/producto para compras digitales, con datos de seguridad propios según el servicio.','Como tener una llave digital en el celular además de la llave física de tu casa.'],
    'retiro sin tarjeta':['Te deja sacar efectivo sin meter el plástico, usando el mecanismo generado por el canal.','Como recoger un pedido con un código: no llevas la tarjeta, llevas la clave que demuestra qué retiro vas a cobrar.'],
    'oportunidades ofertas':['Son invitaciones/ofertas que el banco muestra a ciertos clientes; verlas no significa que el dinero ya sea suyo.','Como cuando una tienda te muestra “tienes esta promoción disponible”: existe la oferta, pero todavía no has comprado nada.'],

    'autenticacion':['Es comprobar que de verdad eres tú antes de dejarte ver o cambiar información sensible.','Como el portero de un edificio: saber tu nombre no basta; tiene que verificar que sí eres quien dices ser.'],
    'mau':['Es la guía que le dice al asesor qué validación de identidad corresponde según el proceso.','Como un reglamento de seguridad: según la puerta que quieras abrir, indica qué llave se necesita.'],
    'biometria':['Usa una característica tuya, como rostro, huella o voz, para ayudarte a demostrar identidad.','Tu cara o huella funcionan como una llave que no tienes que memorizar.'],
    'autenticar vs identificar':['Identificar es decir quién eres; autenticar es demostrarlo.','Tu ex puede saber tu nombre, cumpleaños y dónde vives; eso no significa que pueda hacerse pasar por ti ante el banco xd.'],
    'regla de seguridad':['Si una validación no se cumple, no se brinca “por ayudar”.','Como el cinturón de seguridad: no se quita porque tengas prisa; existe justo para cuando algo sale mal.'],

    'tarjeta de debito tdd':['Usa el dinero que ya tienes en tu cuenta.','Es como pagar con dinero que ya está en tu cartera, solo que la cartera es digital/bancaria.'],
    'cuenta con chequera':['Es una cuenta que, además de otros medios, permite emitir cheques.','Como una caja de herramientas que incluye martillo; otras cuentas pueden tener herramientas diferentes y no traer ese martillo.'],
    'cuenta sin chequera':['Es una cuenta que funciona sin cheques como medio de pago.','Tu celular puede mandar mensajes aunque no tenga fax; no tener chequera no significa que la cuenta no pueda hacer otras cosas.'],
    'niveles de cuenta':['Son categorías regulatorias que pueden cambiar requisitos o límites, no rangos VIP.','Como niveles de verificación en una app: mientras más completo está tu expediente, pueden cambiar las capacidades permitidas.'],
    'udis':['Es una unidad cuyo valor en pesos cambia; no es una cantidad fija de pesos.','Como decir “dos litros” en vez de “$40”: la unidad es una medida; su valor en dinero puede cambiar.'],
    'cuenta activa bloqueada e inactiva':['Son estados distintos: una cuenta puede existir pero tener restricciones o llevar tiempo sin usarse.','Como una cuenta de Netflix: puede existir, estar pausada o estar cerrada; no es lo mismo cada estado.'],
    'cancelacion por inactividad':['Es cuando un producto termina por reglas de falta de uso que aplican a ese producto específico.','Como un casillero que una escuela puede cerrar tras mucho tiempo sin uso, pero primero hay que revisar las reglas de ESE casillero.'],
    'cajeros practicajas y corresponsales':['Son lugares/canales físicos distintos donde puedes hacer ciertas operaciones.','Como comprar comida: restaurante, autoservicio y entrega a domicilio sirven para comer, pero cada canal deja hacer cosas diferentes.'],

    'saldo retenido':['Es dinero apartado temporalmente por una operación que aún no termina de quedar definitiva.','Apartas $300 para una pizza. Ese dinero sigue ligado a ti, pero ya no está libre para gastarlo en otra cosa mientras se confirma el pedido.'],
    'movimiento en transito':['La operación ya empezó, pero todavía está en camino de quedar aplicada o liberada.','Como un Uber que dice “en camino”: el viaje existe, pero todavía no llegó al destino.'],
    'movimiento aplicado':['La operación ya terminó de contabilizarse en el producto.','El paquete ya no dice “en reparto”: ahora dice “entregado”.'],
    'declinado rechazado':['La operación se intentó, pero no fue autorizada o completada.','Como pasar a un antro y que el guardia diga “hoy no entras”: intentaste entrar, pero la entrada no ocurrió.'],
    'doble cargo aparente':['Dos movimientos parecidos no siempre son dos cobros finales; uno puede seguir pendiente.','Como ver dos boletos en una app: uno dice “reservado” y otro “comprado”. Parecen dos, pero primero hay que revisar el estado de cada uno.'],
    'que preguntar':['Primero junta hechos: qué producto, cuánto, cuándo, dónde y qué estatus aparece.','Como detective: antes de decir quién fue, revisas las pistas.'],

    'restriccion':['Es una limitación que impide usar algo de cierta manera.','Como tener un videojuego instalado pero con una función bloqueada hasta cumplir una condición.'],
    'bloqueo':['Impide operar total o parcialmente por una causa concreta.','Como congelar una tarjeta de acceso: el edificio sigue ahí, pero esa llave no abre hasta resolver el motivo.'],
    'tarjeta rechazada':['La compra/retiro no pasó en ese intento; todavía falta saber por qué.','Como una puerta que no abrió: puede ser la llave, el seguro, el horario o la puerta. No adivinas la causa sin revisar.'],
    'limite de uso':['Es un tope de cuánto se puede hacer en cierta operación o periodo.','Tienes una botella de 1 litro: aunque tengas 5 litros de agua disponibles, esa botella solo carga 1 a la vez.'],
    'inactividad':['Significa que el producto lleva tiempo sin uso; no significa automáticamente que ya esté cancelado.','Como una cuenta de red social que no abres en meses: primero revisas si sigue activa antes de decir que desapareció.'],

    'cargo no reconocido':['Es un movimiento que el cliente no identifica; primero se investiga antes de afirmar fraude.','Como encontrar una bolsa de papitas en tu recibo y no recordar haberla comprado: antes de acusar al cajero, revisas si alguien de tu casa la agregó.'],
    'phishing':['Correo o página falsa que intenta robar datos haciéndose pasar por alguien legítimo.','Como una persona con uniforme falso tocando tu puerta para pedirte las llaves de tu casa.'],
    'smishing':['Es phishing por SMS/mensajes.','El mismo disfraz del phishing, pero ahora te llega por mensaje de texto.'],
    'vishing':['Es fraude por llamada donde alguien se hace pasar por una entidad confiable.','Como si tu ex te hablara desde otro número fingiendo ser soporte para sacarte un código xd.'],
    'spoofing':['Hace que un número o remitente falso parezca legítimo.','Es como guardar a alguien con el nombre “Mamá” en otro teléfono: que diga Mamá en pantalla no significa que realmente sea ella.'],
    'pharming':['Te redirige a un sitio falso aunque creas que vas al verdadero.','Pones la dirección correcta del restaurante, pero alguien cambió el letrero y terminas entrando a una copia falsa.'],
    'que revisar antes de tipificar':['Primero confirma hechos y contexto; después decides si es fraude, aclaración u otra cosa.','Como médico: no receta antes de preguntar síntomas.'],

    'cheque':['Es una orden escrita para que el banco pague una cantidad desde una cuenta.','Como darle al banco una nota firmada: “de mi dinero, págale $X a esta persona”.'],
    'cheque al portador':['No señala un beneficiario específico cuando esa modalidad aplica.','Como un boleto que no trae nombre: quien lo presenta puede tener derechos según las reglas aplicables.'],
    'cheque nominativo a la orden':['Sí dice a quién va dirigido el pago.','Como un paquete que trae nombre del destinatario.'],
    'endoso':['Es pasar a otra persona los derechos de un cheque cuando el tipo de cheque lo permite.','Como transferir un boleto a nombre de otra persona, pero solo si ese boleto permite transferencia.'],
    'cheque cruzado':['Está marcado para que se deposite en cuenta en lugar de cobrarse en efectivo.','Como un cupón que dice “solo válido en compra en línea”: ya trae una restricción sobre cómo usarlo.'],
    'cheque certificado y de caja':['Son cheques con respaldo/emisión bancaria diferente al cheque común.','Como comparar una promesa escrita por ti con un vale emitido o respaldado por la propia institución.'],
    'proteccion liberacion y suspension':['Son controles para permitir o impedir que un cheque se pague.','Como un candado: proteger = está cerrado; liberar = abrir para que pase; suspender = dejarlo bloqueado por un problema como robo/extravío.'],
    'cheque de otro banco y saldo a buen cobro':['Puede verse depositado, pero primero necesita validarse antes de que el dinero quede realmente libre.','Es como recibir un billete grande y ponerlo en la caja, pero todavía falta revisar que sea auténtico antes de gastarlo.'],
    'cheque devuelto':['Es un cheque que no pudo cobrarse/aplicarse y regresa con un motivo.','Como un paquete que vuelve al remitente con una etiqueta que explica por qué no se entregó.'],

    'estado de cuenta edc':['Es el resumen formal de un periodo de tu producto.','Como tu recibo mensual completo: junta lo que pasó durante ese ciclo, no solo lo de hoy.'],
    'periodo del edc':['Son las fechas que ese estado de cuenta está resumiendo.','Como un examen que solo cubre capítulos 1 al 5: el capítulo 6 no aparece porque pertenece al siguiente periodo.'],
    'envio consulta digital':['Es obtener el estado de cuenta por un canal autorizado.','Como descargar tu recibo de luz en PDF en vez de esperar la hoja física.'],
    'fecha de corte':['Es el día en que se cierra el “mes” de la tarjeta para armar el estado de cuenta.','Como cerrar la cuenta de una fiesta a medianoche: lo que compres después ya entra a la siguiente cuenta.'],
    'que revisar en un edc':['Primero periodo y producto; luego saldos, movimientos, cargos y abonos.','Como leer un ticket: primero asegúrate de que sea TU ticket y de la fecha correcta antes de revisar cada artículo.'],

    'actualizacion de correo':['Cambiar el email registrado donde corresponda.','Como cambiar tu dirección de correo para que las cartas nuevas lleguen al buzón correcto.'],
    'actualizacion de telefono':['Cambiar el número registrado; puede afectar contacto, alertas o seguridad.','Cambiar de celular no es solo comprar otro aparato: también tienes que avisar a los servicios que todavía mandan códigos al número viejo.'],
    'actualizacion de domicilio':['Cambiar la dirección registrada.','Como actualizar tu dirección en Amazon después de mudarte para que los paquetes no lleguen a la casa vieja.'],
    'alertas bbva':['Son avisos sobre actividad o eventos del producto.','Como las notificaciones de WhatsApp: te avisan que pasó algo, pero el aviso no es el evento en sí.'],
    'datos vs seguridad':['Algunos datos también participan en la protección de acceso, por eso no siempre se cambian como cualquier dato simple.','Cambiar tu foto de perfil no es igual que cambiar el número donde recibes códigos de acceso.'],

    'pago de servicios':['Es pagar desde el banco un recibo u obligación.','Como pagar la luz desde la app en vez de ir con efectivo a una ventanilla.'],
    'cie':['Es un esquema de convenio/referencia para dirigir correctamente ciertos pagos a empresas.','Como poner número de pedido y sucursal en un paquete: esos datos ayudan a que el pago llegue al concepto correcto.'],
    'domiciliacion':['Das permiso para que un servicio cobre automáticamente de una cuenta conforme al acuerdo.','Le dices a CFE: “cada mes cóbrate de aquí sin que yo tenga que entrar a pagar”.'],
    'cargo recurrente':['Un comercio cobra periódicamente a una tarjeta que tiene autorizada.','Netflix guardó la autorización de tu tarjeta y cada mes presenta otro cobro.'],
    'pago duplicado':['Pueden existir dos pagos reales o un pago manual más uno automático; hay que comparar.','Pagaste la pizza por app y, sin acordarte, también le diste efectivo al repartidor: primero revisa de dónde salió cada pago.'],
    'pago no aplicado':['El cliente ve que pagó, pero la empresa todavía no reconoce ese pago o el movimiento tuvo otro resultado.','Como mandar una transferencia y que el vendedor diga “a mí no me aparece”: toca revisar comprobante, datos y estatus.'],

    'tramite por fallecimiento':['Es el proceso especial para manejar productos de una persona que falleció.','Es como una cuenta con candado legal: no porque seas familiar puedes entrar y sacar cosas; primero hay que acreditar quién puede hacer qué.'],
    'beneficiario':['Es la persona designada para recibir un beneficio cuando corresponde.','Como dejar escrito quién recibe un premio si ocurre cierta situación; ser familiar no te vuelve automáticamente la persona designada.'],
    'sucesion':['Es el proceso legal para transmitir bienes/derechos de alguien que falleció.','Como repartir formalmente las cosas de una casa: no basta con que todos sepan “de quién era”; hay un proceso para determinar a quién corresponde.'],
    'cuentas y saldos':['El dinero del titular fallecido sigue un trámite especial para llegar a quien corresponda.','No es como usar la tarjeta de alguien porque conoces el NIP; el dinero tiene que seguir la ruta legal/bancaria correcta.'],
    'seguros de vida':['Pueden pagar un beneficio a beneficiarios si el fallecimiento está cubierto y se cumplen condiciones.','Es como dejar un paraguas económico para tu familia por si un día tú ya no puedes sostenerlos.'],
    'creditos y fallecimiento':['Una deuda no se explica con una regla única; hay que revisar el crédito y si existe cobertura asociada.','Como un celular con garantía: no puedes decir qué pasará sin revisar qué plan/contrato tenía ese equipo.'],

    'cuenta de nomina':['Es la cuenta donde llega el sueldo del trabajo.','Es como el buzón donde tu empresa deposita tu quincena.'],
    'portabilidad de nomina':['Hace que la nómina que llega a un banco se mande automáticamente al banco que elegiste.','Como reenvío de correo: las cartas siguen llegando primero a tu casa vieja y de ahí se redirigen a la nueva.'],
    'banco origen y destino':['Origen recibe primero la nómina; destino es donde el cliente quiere terminar recibiéndola.','Como un vuelo con escala: sales del origen y terminas en el destino, aunque pases por el primer aeropuerto.'],
    'portabilidad no recibida':['La nómina llegó al origen, pero la transferencia esperada al destino no aparece.','Como un paquete que sí llegó al centro de distribución, pero todavía no llegó a tu casa.'],
    'cancelacion cambio de portabilidad':['Es quitar o modificar la instrucción automática de envío de nómina.','Como cancelar el reenvío de correspondencia para que deje de mandarse a otra dirección.'],

    'movilidad de saldos':['Es un nombre interno que todavía hay que verificar exactamente en CUC antes de memorizarlo.','Piensa en una caja con etiqueta borrosa: sabes que habla de “mover saldos”, pero no adivinas qué hay dentro hasta leer la ficha oficial.'],
    'saldo a favor en tdc':['Es dinero que quedó a favor del cliente en la tarjeta porque abonó más de lo que debía o hubo un ajuste/devolución.','Debías $500 y pagaste $700: es como darle $200 de más a alguien; ahora hay que ver cómo se maneja ese excedente.'],
    'traspaso':['Es mover recursos entre productos cuando el proceso lo permite.','Como pasar agua de una botella a otra: primero hay que confirmar que ambas botellas acepten ese movimiento.'],
    'transferencia equivocada':['Es dinero enviado al destino incorrecto; no es lo mismo que mover saldo entre tus productos.','Como mandar un paquete a la dirección equivocada: una vez enviado, recuperar o corregir depende del estado y proceso.'],
    'linea de credito disponible':['Es crédito que el banco todavía te permite usar; no es dinero tuyo depositado.','Es como el límite de una tarjeta de regalo prestada: puedes usar hasta cierto monto, pero después tienes que devolverlo.'],

    'credito de consumo':['Es dinero que el banco te presta para necesidades personales y que debes devolver.','Tu amigo te presta $5,000 para arreglar tu laptop; puedes usarlo ahora, pero queda una deuda y un plan para regresarlo.'],
    'capital':['Es el dinero principal que te prestaron, separado de los costos del crédito.','Si te prestan 10 manzanas y luego debes devolver 11 por el costo, las 10 originales son el capital.'],
    'plazo':['Es cuánto tiempo tienes para terminar de pagar.','Como escoger si una serie la ves en 6, 12 o 24 noches: mientras más tiempo, más se reparte, pero cambia la experiencia/costo.'],
    'pago fijo mensualidad':['Es el pago periódico que corresponde al plan del crédito.','Como la mensualidad del gimnasio: sabes que cada periodo toca cubrir una cantidad según el contrato.'],
    'saldo insoluto':['Es el capital que todavía te falta devolver.','Te prestaron 10 manzanas y ya regresaste 4 de capital: quedan 6 manzanas de saldo insoluto.'],
    'capacidad de pago':['Es cuánto puede pagar una persona sin que sus demás obligaciones hagan inviable el crédito.','No compras una consola de $20,000 solo porque hoy traes $1,000; revisas cuánto ganas y qué otros gastos tienes.'],

    'efi efectivo inmediato':['Es una forma de convertir parte de la línea disponible de una TDC en efectivo financiado, si tienes oferta.','Es como sacar agua de una reserva prestada: el dinero llega a tu cuenta, pero viene de crédito y luego tienes que pagarlo.'],
    'oferta preaprobada':['Es una invitación disponible para ese cliente; todavía falta aceptar/contratar.','Como un cupón que aparece en tu app: tenerlo no significa que ya compraste el producto.'],
    'linea disponible usada por efi':['EFI toma capacidad de la línea de TDC.','Si tu límite es una pizza de 8 rebanadas y EFI usa 3, te quedan 5 rebanadas de capacidad hasta que pagues.'],
    'tasa fija preferencial':['Es el porcentaje de costo que aplica a esa disposición según la oferta.','Es el precio de rentar ese dinero; no memorices un precio genérico porque cada oferta puede ser distinta.'],
    'plazo y pagos':['Define en cuántos periodos devolverás el EFI y cómo se distribuyen los pagos.','Como dividir una compra grande en varias quincenas: eliges el ritmo permitido y cada periodo toca una parte.'],
    'ife vs efi':['Para el producto de efectivo desde TDC, lo verificado públicamente es EFI; “IFE” debe confirmarse si aparece en tu material.','Como escuchar mal el nombre de alguien: antes de aprendértelo para el examen, miras cómo está escrito en la lista oficial.'],

    'tarjeta de credito tdc':['Usa dinero prestado por el banco dentro de una línea; después tienes que pagarlo.','Es como una cartera prestada con límite: puedes comprar ahora, pero luego debes reponer lo que usaste según las reglas.'],
    'linea de credito':['Es el máximo de crédito que el banco te autorizó usar.','Te prestan una cubeta con capacidad de 20 litros: no significa que los 20 sean tuyos; solo es el máximo que puedes utilizar.'],
    'fecha de corte':['Cierra el periodo que se usará para armar el estado de cuenta.','Como cerrar la cuenta de una fiesta: lo que consumas después del cierre se va a la siguiente cuenta.'],
    'fecha limite de pago':['Es el último día indicado para cubrir lo que corresponda del periodo.','Como la fecha límite de una tarea: entregarla después ya cambia las consecuencias.'],
    'pago minimo':['Es lo mínimo que debes cubrir para mantenerte al corriente, pero deja deuda pendiente.','Debes $10,000 y le das a tu ex $500 para que deje de reclamarte ESTE mes xd. No significa que ya quedaste tablas.'],
    'ppngi':['Es el monto del periodo que debes cubrir para no generar intereses ordinarios sobre el saldo aplicable, según tu estado de cuenta.','Aquí ya no das una abonadita: pagas la cuenta del periodo que te marca el estado para no financiar esa parte.'],
    'cascada de pagos':['Es el orden en que el banco reparte tu pago entre distintas “cajas” de deuda.','Como echar agua en vasos colocados en fila: primero se llena el vaso que va antes y después el siguiente.'],
    'saldo revolvente':['Es deuda que sigue financiándose al siguiente ciclo y puede generar intereses.','Como dejar una pestaña abierta: no terminaste esa cuenta, así que sigue viva para el siguiente mes.'],
    'tasa de interes':['Es el porcentaje que indica el precio de usar dinero prestado.','La tasa es la etiqueta del precio: “rentar este dinero cuesta X%”.'],
    'interes':['Es el dinero que termina cobrándose por financiar la deuda según tasa, tiempo y reglas del producto.','La tasa es la receta; el interés es lo que finalmente salió servido en pesos.'],
    'comision':['Es un cobro por un servicio, evento u operación específica; no es lo mismo que interés.','Como pagar envío aparte de lo que cuesta la pizza: es otro concepto del cobro.'],
    'anualidad administracion de tarjeta':['Es una comisión periódica por administrar la tarjeta cuando ese producto la cobra.','Como la membresía del gimnasio: puede cobrarse por tener el servicio aunque ese día no hayas ido a entrenar.'],
    'cat':['Es un indicador para comparar el costo integral de créditos; no es solo la tasa.','Una hamburguesa cuesta $100, pero agregas envío, servicio y otros costos. El CAT intenta darte una mirada más completa del “combo” del crédito.'],
    'meses sin intereses msi':['Divide una compra en mensualidades sin interés de esa promoción si cumples sus condiciones.','Una pizza de 12 rebanadas: en lugar de pagarla toda hoy, pagas una rebanada cada mes; sigue costando lo mismo si respetas la promo.'],
    'puntos bbva y promociones':['Son beneficios que pueden acumularse o aplicarse según tarjeta, compra y campaña.','Como puntos de una cafetería: no toda compra ni toda promoción funciona igual, así que siempre revisas las reglas actuales.'],

    'seguro':['Es un acuerdo para protegerte económicamente frente a ciertos riesgos definidos.','Comprar un paraguas antes de que llueva: pagas por tener protección, no porque quieras que llueva.'],
    'poliza':['Es el documento que dice exactamente qué seguro tienes y bajo qué reglas.','Es el “manual del paraguas”: te dice qué lluvia aguanta, cuánto cubre y cuándo no aplica.'],
    'prima':['Es lo que pagas por mantener el seguro.','Es el precio del paraguas/protección.'],
    'cobertura':['Es cada cosa específica que el seguro sí protege.','Si tu paraguas protege lluvia, esa es la cobertura; que un perro lo muerda es otra situación distinta.'],
    'suma asegurada':['Es el tope o beneficio establecido para una cobertura.','Como una alcancía con límite: puede haber hasta cierta cantidad disponible para ese evento, pero no significa que siempre te den todo.'],
    'deducible':['Es la parte que te toca pagar en ciertos siniestros antes o junto con lo que cubra la aseguradora.','Reparar cuesta $20,000 y tu póliza dice que una parte te corresponde: esa parte es tu “entrada” al gasto.'],
    'siniestro':['Es el evento que ocurrió y que podría estar cubierto por el seguro.','El seguro es el extintor; el siniestro es cuando de verdad hay fuego y toca usarlo.'],
    'beneficiario':['Es quien recibe el beneficio cuando la cobertura lo establece.','Como poner el nombre de quién recibe un premio si ocurre cierta condición.'],
    'asegurado contratante y beneficiario':['Asegurado = quien está protegido; contratante = quien compra/paga; beneficiario = quien recibe el beneficio cuando aplica.','En una fiesta: uno paga el pastel, otro cumple años y otro puede llevarse una rebanada; no siempre son la misma persona.'],
    'vigencia y renovacion':['Vigencia es el tiempo durante el cual el seguro está activo; renovación extiende/inicia otro periodo según condiciones.','Como una suscripción: mientras está vigente funciona; si venció, primero hay que revisar si se renovó.'],
    'exclusiones':['Son situaciones que el seguro dice expresamente que NO cubre.','Tu paraguas puede aguantar lluvia, pero no significa que sirva como paracaídas.'],
    'seguro de vida':['Protege económicamente a beneficiarios ante fallecimiento cubierto y puede tener otras coberturas según póliza.','Es dejar un colchón económico para que tu familia no quede sin apoyo si tú faltas.'],
    'seguro de auto':['Protege riesgos del vehículo y responsabilidad según el plan contratado.','Como ponerle armadura al carro, pero la armadura tiene piezas específicas: no cubre todo por arte de magia.'],
    'seguro de salud gastos medicos':['Ayuda con determinados gastos o servicios de salud según la cobertura.','Como una red de apoyo para que una enfermedad/accidente no te caiga completo al bolsillo.'],
    'seguro de hogar y objetos':['Protege vivienda o pertenencias frente a riesgos definidos.','Como poner diferentes escudos a tu casa y cosas: uno puede proteger robo, otro daños, dependiendo de lo contratado.'],
    'seguros bbva disponibles':['Hay seguros para necesidades distintas; “seguro” no es un único producto.','Como una tienda de fundas: no compras la misma funda para celular, auto y casa; primero preguntas qué quieres proteger.'],
    'venta responsable de seguros':['Primero detectas una necesidad real y después explicas una opción con sus límites y costos.','No le vendes paraguas a alguien solo porque entró a la tienda; primero preguntas si vive donde llueve y qué necesita proteger.'],

    'transferencia':['Es mover dinero de una cuenta a otra.','Como mandar un paquete: hay un origen, un destino, una cantidad y un estado del envío.'],
    'spei':['Es el sistema que procesa muchas transferencias interbancarias en México.','Piensa en una autopista por la que viaja el dinero entre bancos.'],
    'cep':['Es el comprobante electrónico que ayuda a demostrar/consultar datos de un SPEI cuando está disponible.','Como el comprobante de entrega del paquete: te da evidencia de qué operación se procesó.'],
    'clave de rastreo':['Es el identificador para seguir una transferencia SPEI.','Como el número de guía de Mercado Libre para rastrear tu paquete.'],
    'estatus spei':['Te dice en qué punto está el pago: procesándose, liquidado, devuelto, rechazado, etc.','Igual que paquetería: “en tránsito”, “entregado” y “devuelto” significan cosas distintas.'],
    'opi':['Es una orden/transferencia de dinero internacional.','Es mandar un paquete a otro país: entran más datos, monedas y bancos en el camino.'],
    'swift bic':['Identifica al banco/institución en transferencias internacionales.','CLABE sería la dirección de la casa; SWIFT es más parecido a identificar la empresa de paquetería/banco.'],
    'iban aba y transit':['Son identificadores usados por distintos países o sistemas bancarios.','Como códigos postales de países distintos: no todos usan el mismo formato.'],
    'banco corresponsal':['Es un banco intermediario que ayuda a conectar una transferencia internacional.','Como un vuelo con escala: el dinero puede pasar por otro aeropuerto/banco antes de llegar al destino.'],

    '1 identifica el producto':['Antes de resolver, descubre de qué cosa habla el cliente.','Si alguien dice “no prende”, primero preguntas si habla del celular, la TV o el carro.'],
    '2 identifica la intencion':['Descubre qué quiere lograr: consultar, cambiar, cancelar, aclarar, contratar, etc.','No es lo mismo “mi pizza llegó fría” que “quiero cancelar mi pedido”; el objeto es el mismo, la necesidad no.'],
    '3 sondea hechos':['Haz preguntas cortas para saber qué ocurrió de verdad.','Modo detective: fecha, monto, canal, estado y contexto antes de acusar al culpable.'],
    '4 autentica cuando corresponda':['Cumple la validación necesaria antes de mostrar o cambiar información sensible.','Antes de abrir la puerta, el portero revisa que sí seas residente.'],
    '5 revisa sistema y cuc':['Comprueba lo que muestra el sistema y usa el proceso vigente.','Como cocinar con receta actual: no usas una foto de la receta de hace cuatro años si los ingredientes cambiaron.'],
    '6 explica simple':['Traduce lo técnico a una idea que el cliente pueda repetir con sus palabras.','Si no puedes explicarlo con manzanas, todavía falta simplificarlo.'],
    '7 cierra y confirma':['Deja claro qué pasó y qué sigue.','Como terminar una cita de médico sabiendo qué tienes que hacer al salir, no solo con palabras técnicas en la cabeza.'],
    '8 venta cruzada pertinente':['Ofrece algo adicional solo si encaja con una necesidad real.','Si alguien compra tacos, quizá tiene sentido ofrecer bebida; no le vendes un refrigerador solo porque ya está en la caja.'],
    'mapa rapido de oferta':['Relaciona necesidad con producto en lugar de ofrecer al azar.','Primero escuchas “qué le duele” y luego buscas la herramienta adecuada, no sacas todas las herramientas a la vez.']
  };

  const topicFallback={
    fundamentos:'Quédate con la función básica y con qué objeto/persona estás hablando.',
    identificadores:'Pregunta siempre: “¿este número identifica a la persona, al producto, a la cuenta o a la operación?”',
    app:'Piensa primero en qué pantalla/producto está viendo el cliente.',
    autenticacion:'La idea central es comprobar identidad antes de permitir algo sensible.',
    debito:'En débito normalmente estás hablando del dinero que ya está en la cuenta.',
    movimientos:'Primero decide si el movimiento está pendiente, aplicado o rechazado.',
    restricciones:'No confundas una limitación con fraude o cancelación.',
    fraudes:'Primero protege y sondea; después clasifica.',
    cheques:'Piensa quién lo emite, quién lo cobra, si puede pagarse y en qué estado está.',
    edc:'Ubica producto, periodo y movimiento antes de explicar el documento.',
    actualizacion:'Primero identifica qué dato cambia y qué servicio depende de él.',
    pagos:'Primero distingue pago manual, automático a cuenta o recurrente a tarjeta.',
    fallecimiento:'Producto + quién solicita + trámite vigente; no se opera como una cuenta normal.',
    nomina:'Sueldo entra por un origen; portabilidad puede reenviarlo a otro banco.',
    movilidad:'No adivines el significado interno: identifica qué saldo se mueve y entre qué productos.',
    consumo:'Te prestan capital y lo devuelves durante un plazo con el costo que corresponda.',
    efi:'Es crédito de TDC convertido en efectivo financiado, no dinero gratis.',
    tdc:'Compra ahora con crédito; luego importa cuánto debes, cuándo cortó y cuánto pagas.',
    seguros:'Pregunta qué riesgo quiere proteger y luego revisa qué cubre la póliza.',
    transferencias:'Origen + destino + identificador + estatus.',
    llamada:'Producto + intención + hechos + seguridad + proceso + explicación + cierre.'
  };

  guideTopics.forEach(topic=>{
    (topic.sections||[]).forEach(section=>{
      const hit=map[norm(section.t)];
      section.easy=hit?.[0] || topicFallback[topic.id] || 'Quédate con una sola idea: identifica qué es, para qué sirve y qué cambia en el caso del cliente.';
      section.analogy=hit?.[1] || 'Piensa en el concepto como una pieza de un mapa: primero ubica qué representa y después con qué otras piezas se conecta.';
    });
  });
})();